### ISSUE TITLE
eliminate annoying NPE from TomcatServerSpec on Tomcat.stop()

### ISSUE THREAD

**Issue by bfritz** [http4s/http4s#1154]
When `TomcatServerSpec` cleans up, it calls `Tomcat.stop()` which pollutes the console with:
```
Apr 27, 2017 5:19:26 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Tomcat
Apr 27, 2017 5:19:26 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
WARNING: JDBC driver de-registration failed for web application [ROOT]
java.lang.NullPointerException
	at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc(WebappClassLoaderBase.java:1652)
	at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1585)
	at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1537)
	at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5572)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

One example of many, many examples:
https://travis-ci.org/http4s/http4s/jobs/226484309#L3834

Likely a missing null check upstream in `WebappClassLoaderBase.clearReferencesJdbc()` and I plan to raise an upstream issue.  Opening here so I have a concrete case to reference.

**Comment by rossabaker** [comment]
:+1: That thing has been annoying for a long time.

**Comment by bfritz** [comment]
Agreed.  Linking to wrong version, but the code is the same in 8.5.14...

Their [getResourceAsStream()](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/loader/WebappClassLoaderBase.java#L1093) has `return null;` for the I-give-up case.

Then they do [this](https://github.com/apache/tomcat/blob/trunk/java/org/apache/catalina/loader/WebappClassLoaderBase.java#L1562):
```
try (InputStream is = getResourceAsStream(
        "org/apache/catalina/loader/JdbcLeakPrevention.class")) {
    int read = is.read(classBytes, offset, classBytes.length-offset);
```

My hunch is it's this bug:
https://bz.apache.org/bugzilla/show_bug.cgi?id=56050

And was closed without resolution because the line number in the stack trace was off by a few lines.  (The Ubuntu release might have had patches applied.)

Hoping to reproduce with minimal Java test case and then report to the Tomcat team.

**Comment by bfritz** [comment]
The reason we see this in `TomcatServerSpec` but the rest of the world is not complaining...

If I pause [this code](https://github.com/bfritz/tomcat-clearReferencesJdbc-npe/blob/master/src/test/java/com/bfritz/test/TomcatTest.java) in a debugger and inspect[1]:
```
ClassLoader.getSystemClassLoader().getResource("org/apache/catalina/loader/JdbcLeakPrevention.class").toExternalForm()
```
the value is:
```
jar:file:/home/brad/.m2/repository/org/apache/tomcat/tomcat-catalina/8.5.14/tomcat-catalina-8.5.14.jar!/org/apache/catalina/loader/JdbcLeakPrevention.class
```

If I do the same with [TomcatServerSpec](https://github.com/http4s/http4s/blob/master/tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala) and inspect:
```
ClassLoader.getSystemClassLoader().getResource("org/apache/catalina/loader/JdbcLeakPrevention.class")
```
the value is:
```
null
```

Still trying to figure out what sbt/specs2/http4s classloader tricks are making that the case.

[1] Technically, Tomcat is doing the lookup with `sun.misc.Launcher$AppClassLoader.getResourceAsStream()`, but pretty sure `ClassLoader.getSystemClassLoader()` is a fair surrogate.)

**Comment by rossabaker** [comment]
I haven't seen this in a while.  Maybe was fixed by the silence system error work.
