### ISSUE TITLE
Blaze Client 0.17x POST failure

### ISSUE THREAD

**Issue by mseddon** [http4s/http4s#1172]
Under 0.16 everything works fine, but when I switch to the `0.17-M2` or `0.17-M1` release, attempting a simple POST triggers the following error:

```
[error] (run-main-0) java.io.IOException: Failed to connect to endpoint: RequestKey(https,duckduckgo.com)
java.io.IOException: Failed to connect to endpoint: RequestKey(https,duckduckgo.com)
        at org.http4s.client.blaze.BlazeClient$.$anonfun$apply$5(BlazeClient.scala:47)
        at fs2.Task.$anonfun$flatMap$2(Task.scala:40)
        at fs2.util.Attempt$.apply(Attempt.scala:12)
        at fs2.Task.$anonfun$flatMap$1(Task.scala:40)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at fs2.internal.Future.$anonfun$flatMap$1(Future.scala:17)
        at fs2.internal.Future.step(Future.scala:53)
        at fs2.internal.Future.listen(Future.scala:30)
        at fs2.internal.Future.$anonfun$listen$3(Future.scala:34)
        at fs2.internal.Future.$anonfun$listen$3$adapted(Future.scala:34)
        at fs2.internal.Trampoline.$anonfun$map$1(Trampoline.scala:10)
        at fs2.internal.Trampoline$.run(Trampoline.scala:31)
        at fs2.internal.Trampoline.run(Trampoline.scala:12)
        at fs2.internal.Trampoline.run$(Trampoline.scala:12)
        at fs2.internal.Trampoline$FlatMap.run(Trampoline.scala:18)
        at fs2.Task$.$anonfun$async$4(Task.scala:247)
        at fs2.Strategy$$anon$5$$anon$6.run(Strategy.scala:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Reproduction [here](https://github.com/mseddon/blaze-client-error).  May be worth mentioning I'm running Windows 10 here, not tried any other platforms just yet.

**Comment by rossabaker** [comment]
Works for me on OSX.  I'm struggling to think what would be different on 0.17 as far as connections go.  Does it fail connecting to arbitrary hosts?  How about hitting something over http instead of https?

**Comment by mseddon** [comment]
Yes, it seems https is what is triggering the issue- reliably i get the 'cannot connect to endpoint' exception with https, http seems fine, for both localhost and remote servers.  Did a quick sanity check, and can confirm `0.16.0a-M1` is still working fine for me.

**Comment by ChristopherDavenport** [comment]
I think we are going to see some regressions as a result of http4s/blaze#71 The introduction of tail recursion means on self-signed certificates or other non-trusted certs it will hang the program.

I've found this by accident a couple of times since we made the switch. I have no idea what is different on this topic in `0.17`, however I think this may be the wrong layer of abstraction. As blaze hanging on a self-signed cert is probably not behavior we want.

**Comment by lancewalton** [comment]
I'm seeing the same kind of problem with POSTs from BlazeClient (0.16.0a-M1). For the same URL it sometimes works, & then a moment later it fails with the above error.

The URL I'm posting too is on my own machine, but looks like this: http://81.140.188.251:14329/individuals

The error says:

Exception in thread "main" java.io.IOException: Failed to connect to endpoint: RequestKey(http,81.140.188.251:14329)
[error] 	at org.http4s.client.blaze.BlazeClient$.$anonfun$apply$5(BlazeClient.scala:50)
[error] 	at scalaz.concurrent.Task.$anonfun$flatMap$2(Task.scala:35)
[error] 	at scalaz.concurrent.Task$.Try(Task.scala:457)

**Comment by rossabaker** [comment]
I'm curious whether this happens on blaze-0.12.6.  That version is used by on 0.15.13, and will be on 0.16.0-M3 and 0.17.0-M3 later today.  Or you can add a direct dependency, as it's compatible with earlier blaze-0.12.x.

**Comment by ChristopherDavenport** [comment]
Has anyone attempted the newer version with updated blaze to see if the new version of blaze helped remedy the situation?

**Comment by eklavya** [comment]
Just tried with the test project mseddon provided. Works fine on MacOS with 0.17.0-M3.

**Comment by rossabaker** [comment]
Since I couldn't reproduce it originally, it would be great if someone who saw this before could try again on the latest stack.

**Comment by vladimir-lu** [comment]
I can reproduce with 0.17.0-M3 on both Win7 Ultimate, Enterprise and Win10 (not sure which edition).

I believe this is a bug in blaze's `ByteBufferHead.writeRequest(data: Seq[ByteBuffer]): Future[Unit]` method (well maybe the source of the bug is not there exactly but that's where the first problem appears). If you turn on debug logging:

```
2017-07-11 00:00:00 DEBUG Stage:46 - ByteBufferHead starting up at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ByteBufferHead sending inbound command: Connected
2017-07-11 00:00:00 DEBUG Stage:46 - SSLStage starting up at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage SSLStage sending inbound command: Connected
2017-07-11 00:00:00 DEBUG Stage:45 - Stage started up. Beginning read buffering
2017-07-11 00:00:00 DEBUG Stage:187 - SSL Read Request Status: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ReadBufferStage sending inbound command: Connected
2017-07-11 00:00:00 DEBUG Stage:46 - Http1Connection starting up at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:46 - ClientTimeoutStage starting up at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:101 - Connection was idle. Running.
2017-07-11 00:00:00 DEBUG Stage:122 - Beginning request: POST https://duckduckgo.com/
2017-07-11 00:00:00 DEBUG Stage:187 - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2017-07-11 00:00:00 WARN  Stage:30 - Channel IOException not known to be a disconnect error
java.io.IOException: An invalid argument was supplied
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.write0(Native Method)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.access$900(WindowsAsynchronousSocketChannelImpl.java:43)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$WriteTask.run(WindowsAsynchronousSocketChannelImpl.java:778)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.implWrite(WindowsAsynchronousSocketChannelImpl.java:916)
	at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
	at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:416)
	at org.http4s.blaze.channel.nio2.ByteBufferHead.org$http4s$blaze$channel$nio2$ByteBufferHead$$go$2(ByteBufferHead.scala:59)
	at org.http4s.blaze.channel.nio2.ByteBufferHead.writeRequest(ByteBufferHead.scala:73)
	at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:96)
	at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:94)
	at org.http4s.blaze.pipeline.stages.SSLStage.channelWrite(SSLStage.scala:21)
	at org.http4s.blaze.pipeline.stages.SSLStage.syncWrite(SSLStage.scala:243)
	at org.http4s.blaze.pipeline.stages.SSLStage.writeRequest(SSLStage.scala:49)
	at org.http4s.blaze.pipeline.stages.SSLStage.writeRequest(SSLStage.scala:21)
	at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:84)
	at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:82)
	at org.http4s.client.blaze.ReadBufferStage.channelWrite(ReadBufferStage.scala:14)
	at org.http4s.client.blaze.ReadBufferStage.writeRequest(ReadBufferStage.scala:21)
	at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:84)
	at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:82)
	at org.http4s.client.blaze.ClientTimeoutStage.channelWrite(ClientTimeoutStage.scala:17)
	at org.http4s.client.blaze.ClientTimeoutStage.writeRequest(ClientTimeoutStage.scala:73)
	at org.http4s.client.blaze.ClientTimeoutStage.writeRequest(ClientTimeoutStage.scala:17)
	at org.http4s.blaze.pipeline.Tail.channelWrite(Stages.scala:84)
	at org.http4s.blaze.pipeline.Tail.channelWrite$(Stages.scala:82)
	at org.http4s.client.blaze.Http1Connection.channelWrite(Http1Connection.scala:26)
	at org.http4s.blaze.util.IdentityWriter.writeBodyChunk(IdentityWriter.scala:46)
	at org.http4s.blaze.util.IdentityWriter.writeEnd(IdentityWriter.scala:52)
	at org.http4s.blaze.util.EntityBodyWriter.$anonfun$writeEntityBody$1(EntityBodyWriter.scala:52)
	at fs2.Task$.$anonfun$fromFuture$1(Task.scala:254)
	at fs2.Task$.$anonfun$fromFuture$1$adapted(Task.scala:254)
	at fs2.Task$.$anonfun$async$2(Task.scala:247)
	at fs2.Task$.$anonfun$async$2$adapted(Task.scala:246)
	at fs2.internal.Future.listen(Future.scala:34)
	at fs2.internal.Future.$anonfun$listen$3(Future.scala:34)
	at fs2.internal.Future.$anonfun$listen$3$adapted(Future.scala:34)
	at fs2.internal.Trampoline.$anonfun$map$1(Trampoline.scala:10)
	at fs2.internal.Trampoline$.run(Trampoline.scala:31)
	at fs2.internal.Trampoline.run(Trampoline.scala:12)
	at fs2.internal.Trampoline.run$(Trampoline.scala:12)
	at fs2.internal.Trampoline$FlatMap.run(Trampoline.scala:18)
	at fs2.Task$.$anonfun$async$4(Task.scala:247)
	at fs2.Strategy$$anon$3$$anon$4.run(Strategy.scala:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ByteBufferHead sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - SSLStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage SSLStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ReadBufferStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ReadBufferStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ClientTimeoutStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ClientTimeoutStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:120 - Stage Http1Connection sending outbound command: Disconnect
2017-07-11 00:00:00 DEBUG Stage:56 - ClientTimeoutStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:120 - Stage ClientTimeoutStage sending outbound command: Disconnect
2017-07-11 00:00:00 DEBUG Stage:56 - ReadBufferStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:120 - Stage ReadBufferStage sending outbound command: Disconnect
2017-07-11 00:00:00 DEBUG Stage:56 - SSLStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:120 - Stage SSLStage sending outbound command: Disconnect
2017-07-11 00:00:00 DEBUG Stage:124 - closeWithError(EOF)
2017-07-11 00:00:00 DEBUG Stage:56 - Http1Connection shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:124 - closeWithError(EOF)
2017-07-11 00:00:00 DEBUG Stage:187 - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ByteBufferHead sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - SSLStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage SSLStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ReadBufferStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ReadBufferStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ClientTimeoutStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ClientTimeoutStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:124 - closeWithError(EOF)
2017-07-11 00:00:00 DEBUG Stage:187 - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ByteBufferHead sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - SSLStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage SSLStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ReadBufferStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ReadBufferStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:56 - ClientTimeoutStage shutting down at Tue Jul 11 00:00:00 BST 2017
2017-07-11 00:00:00 DEBUG Stage:236 - Stage ClientTimeoutStage sending inbound command: Disconnected
2017-07-11 00:00:00 DEBUG Stage:124 - closeWithError(EOF)
Exception in thread "main" java.io.IOException: Failed to connect to endpoint: RequestKey(https,duckduckgo.com)
	at org.http4s.client.blaze.BlazeClient$.$anonfun$apply$5(BlazeClient.scala:47)
	at fs2.Task.$anonfun$flatMap$2(Task.scala:40)
	at fs2.util.Attempt$.apply(Attempt.scala:12)
	at fs2.Task.$anonfun$flatMap$1(Task.scala:40)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at fs2.internal.Future.$anonfun$flatMap$1(Future.scala:17)
	at fs2.internal.Future.step(Future.scala:53)
	at fs2.internal.Future.listen(Future.scala:30)
	at fs2.internal.Future.$anonfun$listen$3(Future.scala:34)
	at fs2.internal.Future.$anonfun$listen$3$adapted(Future.scala:34)
	at fs2.internal.Trampoline.$anonfun$map$1(Trampoline.scala:10)
	at fs2.internal.Trampoline$.run(Trampoline.scala:31)
	at fs2.internal.Trampoline.run(Trampoline.scala:12)
	at fs2.internal.Trampoline.run$(Trampoline.scala:12)
	at fs2.internal.Trampoline$FlatMap.run(Trampoline.scala:18)
	at fs2.Task$.$anonfun$async$4(Task.scala:247)
	at fs2.Strategy$$anon$5$$anon$6.run(Strategy.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1
```

After adding some extra debug statements to that method the error only occurs when the seq of buffers is empty. 

If I change the line: https://github.com/http4s/blaze/blob/b053e11f6f1c82828eb88af0d2c9d081489f63c7/core/src/main/scala/org/http4s/blaze/channel/nio2/ByteBufferHead.scala#L73 to read instead of `go(0)` to `if (srcs.nonEmpty) go(0) else p.trySuccess(())` then the program does not fail anymore.

I guess that error message comes from https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/windows/native/sun/nio/ch/WindowsAsynchronousSocketChannelImpl.c#L186 where it tries to get a pointer to the array of buffers in (but it's an empty array): `WSABUF* lpWsaBuf = (WSABUF*) jlong_to_ptr(address);` I didn't debug it though.

I have not figured out yet why it's passing an empty array of buffers in the first place - so if anyone could enlighten me on that that would be most appreciated.

**Comment by kevinmeredith** [comment]
@mseddon, did you encounter this error on 0.15 at all? Did you resolve the cause of this issue?

**Comment by rossabaker** [comment]
@bryce-anderson Do you still have Windows, or are you all Mac now?  What do you think about two comments above?

**Comment by bryce-anderson** [comment]
My windows machine is in a closet but looks like an easy workaround. I'd planned on putting up a PR this evening, or @vladimir-lu could do so if he's interested since it will basically be his work.

**Comment by bryce-anderson** [comment]
Sadly, travis-ci doesn't have a windows host that we could use for regression testing.

**Comment by ChristopherDavenport** [comment]
I could investigate into appveyor for windows builds.

**Comment by bryce-anderson** [comment]
https://github.com/http4s/blaze/pull/104 should fix this.
