### ISSUE TITLE
NoSuchMethodError: cats.implicits$.catsSyntaxFlatten

### ISSUE THREAD

**Issue by pathikrit** [http4s/http4s#1463]
My code compiles and runs but it borks on something like this:

```scala
import io.circe._
import io.circe.literal._
import io.circe.generic.auto._
import io.circe.syntax._

import fs2.Task

import org.http4s._
import org.http4s.circe._
import org.http4s.server._
import org.http4s.dsl._

case class Input(foo: String, bar: Int)
case class User(name: String, age: Int)

def replay(inputs: Seq[Input]) = Ok(input.asJson)

val service: HttpService = basicAuth(AuthedService[User] {
  case r @ (POST -> Root / "trades" as user) =>
    for {
      input <- r.req.as(jsonOf[Seq[Input]])
      resp <- replay(input)
    } yield resp
})
```

It crashes with:
```
java.lang.NoSuchMethodError: cats.implicits$.catsSyntaxFlatten(Ljava/lang/Object;Lcats/FlatMap;)Lcats/syntax/FlattenOps;
	at org.http4s.MessageOps$class.as(MessageOps.scala:91)
	at org.http4s.Request.as(Message.scala:144)
	at MyWebServer$$anonfun$1.applyOrElse(MyWebServer.scala:57)
	at MyWebServer$$anonfun$1.applyOrElse(MyWebServer.scala:51)
	at org.http4s.package$AuthedService$$anonfun$apply$3.apply(package.scala:77)
	at org.http4s.package$AuthedService$$anonfun$apply$3.apply(package.scala:77)
	at cats.data.Kleisli.apply(Kleisli.scala:71)
	at org.http4s.server.middleware.authentication.package$$anonfun$challenged$1$$anonfun$apply$1.apply(package.scala:14)
	at org.http4s.server.middleware.authentication.package$$anonfun$challenged$1$$anonfun$apply$1.apply(package.scala:12)
	at fs2.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:40)
	at fs2.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:40)
	at fs2.util.Attempt$.apply(Attempt.scala:12)
	at fs2.Task$$anonfun$flatMap$1.apply(Task.scala:40)
	at fs2.Task$$anonfun$flatMap$1.apply(Task.scala:38)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at fs2.internal.Future$$anonfun$flatMap$1.apply(Future.scala:17)
	at fs2.internal.Future$$anonfun$flatMap$1.apply(Future.scala:17)
	at fs2.internal.Future.step(Future.scala:53)
	at fs2.internal.Future.listen(Future.scala:30)
	at fs2.internal.Future.runAsync(Future.scala:69)
	at fs2.Task.unsafeRunAsync(Task.scala:100)
	at org.http4s.server.blaze.Http1ServerStage$$anonfun$runRequest$1.apply$mcV$sp(Http1ServerStage.scala:109)
	at fs2.Strategy$$anon$3$$anon$4.run(Strategy.scala:54)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I am on circe v0.8.0 and http4s 0.17.2

**Comment by rossabaker** [comment]
Did something else pull in a new version of cats?  You should be on cats-0.9 with that stack.

**Comment by pathikrit** [comment]
Yup I was depending on cat-effect 0.4 which was replacing cats-0.9 with cats-1.0. Downgrading to 0.3 worked.
