### ISSUE TITLE
Error in requestLoop() java.lang.NullPointerException

### ISSUE THREAD

**Issue by tobyweston** [http4s/http4s#1487]
Sorry, this is going to sound really vague but I get the following stacktrace pretty frequently on a server when (I assume) it accepts `PUT` requests.

I don't have much to go on here so thought I'd post an issue for a few pointers to help me debug. The server is pretty simple, started up like below and runs just a few `HttpService` endpoints.

```
  private def build(): Task[org.http4s.server.Server] = BlazeBuilder
    .withServiceExecutor(DefaultExecutorService)
    .bindHttp(port, "0.0.0.0")
    .mountService(services(), "/")
    .start
```

The `PUT` sends a simple JSON body. Not sure what else I can tell you...

The stack trace is below

```
[blaze-nio-fixed-selector-pool-2] ERROR org.http4s.blaze.pipeline.Stage - error in requestLoop()
java.lang.NullPointerException
	at org.http4s.internal.parboiled2.ParserInput$StringBasedParserInput.length(ParserInput.scala:97)
	at org.http4s.internal.parboiled2.Parser.__advance(Parser.scala:228)
	at org.http4s.internal.parboiled2.Parser.runRule$1(Parser.scala:140)
	at org.http4s.internal.parboiled2.Parser.phase0_initialRun$1(Parser.scala:150)
	at org.http4s.internal.parboiled2.Parser.__run(Parser.scala:203)
	at org.http4s.parser.Rfc2616BasicRules$.token(Rfc2616BasicRules.scala:84)
	at org.http4s.Method$.$anonfun$fromString$1(Method.scala:47)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.concurrent.TrieMap.getOrElse(TrieMap.scala:631)
	at org.http4s.Method$.fromString(Method.scala:47)
	at org.http4s.server.blaze.Http1ServerParser.collectMessage(Http1ServerParser.scala:48)
	at org.http4s.server.blaze.Http1ServerStage.runRequest(Http1ServerStage.scala:111)
	at org.http4s.server.blaze.Http1ServerStage.reqLoopCallback(Http1ServerStage.scala:97)
	at org.http4s.server.blaze.Http1ServerStage.$anonfun$requestLoop$1(Http1ServerStage.scala:74)
	at org.http4s.server.blaze.Http1ServerStage.$anonfun$requestLoop$1$adapted(Http1ServerStage.scala:74)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at org.http4s.blaze.util.Execution$$anon$1.execute(Executor.scala:27)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at org.http4s.blaze.channel.nio1.NIO1HeadStage.readReady(NIO1HeadStage.scala:61)
	at org.http4s.blaze.channel.nio1.SelectorLoop.run(SelectorLoop.scala:134)
```

**Comment by rossabaker** [comment]
Which version, so we can line up that stack trace?

**Comment by tobyweston** [comment]
sorry,  I'm on 2.12 / 0.16.3a 👍

**Comment by rossabaker** [comment]
It looks like a null string is being passed to parse the request, which definitely should not be.  Does this happen on each request?  Only under load?  What client is being used?  Can it be reproduced with other clients?

**Comment by tobyweston** [comment]
It's not very frequent, the app in question makes a request every 30 seconds and the log is only sparsely populated with these. I'm adding some more detail to that to get the exact frequency...

It's with the blaze client, my setup:

```
object BlazeHttpClient {

  private val DefaultTimeout: Duration = 5.minutes
  private val DefaultExecutor = {
    new ThreadPoolExecutor(1, getRuntime.availableProcessors() * 6, 60L, SECONDS, new LinkedBlockingQueue[Runnable](), TemperatureMachineThreadFactory("client"))
  }

  def apply() = SimpleHttp1Client(defaultConfig.copy(idleTimeout = DefaultTimeout, customExecutor = Some(DefaultExecutor)))
}
```

I can try swapping it out for another. I'm not sure as and when you'd use the `PooledHttp1Client`, is it worth trying that?

**Comment by ChristopherDavenport** [comment]
Well that will spin out of control under load. Generally always favor PooledHttp1Client.

**Comment by tobyweston** [comment]
Thanks, what's the schematics there, I'm guessing it reuses connections and will wait/block until one is free?

**Comment by ChristopherDavenport** [comment]
The semantics are to have a queue, where it semantically block, where in the simple is immediately triggers a new Task for each. Here is the [PoolManager](https://github.com/http4s/http4s/blob/release-0.16.x/client/src/main/scala/org/http4s/client/PoolManager.scala) and the [Simple/Basic](https://github.com/http4s/http4s/blob/release-0.16.x/client/src/main/scala/org/http4s/client/BasicManager.scala)

**Comment by rossabaker** [comment]
I have been threatening to deprecate `SimpleHttp1Client` because it sounds like a reasonable default and is actually terrible for production.  `PooledHttp1Client` is the correct one for production use.

That said, we should also have a better failure mode for this.  I'll see if I can reproduce tomorrow.

**Comment by tobyweston** [comment]
@rossabaker I can't reproduce with other clients, it seems intermittent and not under load per se. It'll happen once every 10-15 mins out of 2 requests a minute, so about 2-3% of requests fail.

**Comment by tobyweston** [comment]
Yep, switched to `PooledHttp1Client`. Never looking back 😜

**Comment by tobyweston** [comment]
I switched to Jetty to see if it made a difference. I can't tell if this is the same underlying problem or not, but I now get this occasional error. Can you advice if this is the same issue? Any thoughts? thx

```
Tue 09-Jan-201821:19:59.365[temperature-http-server-1]ERRORError processing request after response was committed
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:794) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:528) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:783) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:834) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpOutput$AsyncWrite.process(HttpOutput.java:1205) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) ~[temperature-machine-2.1.jar:2.1]
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:465) ~[temperature-machine-2.1.jar:2.1]
	at java.io.OutputStream.write(OutputStream.java:75) ~[?:1.8.0_65]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$3(ServletIo.scala:187) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$3$adapted(ServletIo.scala:183) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$10(ServletIo.scala:243) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$10$adapted(ServletIo.scala:243) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Task.$anonfun$map$3(Task.scala:42) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Task$.Try(Task.scala:457) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Task.$anonfun$map$2(Task.scala:42) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.$bslash$div.flatMap(Either.scala:135) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Task.$anonfun$map$1(Task.scala:42) ~[temperature-machine-2.1.jar:2.1]
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52) ~[temperature-machine-2.1.jar:2.1]
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52) ~[temperature-machine-2.1.jar:2.1]
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.$anonfun$unsafePerformListen$2(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Trampoline$.$anonfun$delay$1(Free.scala:356) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free$.$anonfun$suspend$2(Free.scala:27) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.$anonfun$resume$2(Free.scala:119) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.$anonfun$run$1(Free.scala:271) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go2$1(Free.scala:162) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go(Free.scala:165) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.run(Free.scala:271) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$.$anonfun$async$2(Future.scala:428) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$.$anonfun$async$2$adapted(Future.scala:428) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$9(ServletIo.scala:237) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.servlet.NonBlockingServletIo.$anonfun$initWriter$9$adapted(ServletIo.scala:232) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$.$anonfun$async$1(Future.scala:428) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$.$anonfun$async$1$adapted(Future.scala:428) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.$anonfun$unsafePerformListen$3(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.$anonfun$unsafePerformListen$3$adapted(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.$anonfun$map$1(Free.scala:99) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.resume(Free.scala:117) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go2$1(Free.scala:161) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go(Free.scala:165) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.run(Free.scala:271) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432) ~[temperature-machine-2.1.jar:2.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_65]
	at org.http4s.util.TrampolineExecutionContext$.execute(TrampolineExecutionContext.scala:27) ~[temperature-machine-2.1.jar:2.1]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_65]
	at scalaz.concurrent.Future$.$anonfun$apply$1(Future.scala:432) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$.$anonfun$apply$1$adapted(Future.scala:431) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.unsafePerformListen(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.$anonfun$unsafePerformListen$3(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future.$anonfun$unsafePerformListen$3$adapted(Future.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.$anonfun$map$1(Free.scala:99) ~[temperature-machine-2.1.jar:2.1]
	at scalaz.Free.resume(Free.scala:117) [temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go2$1(Free.scala:161) [temperature-machine-2.1.jar:2.1]
	at scalaz.Free.go(Free.scala:165) [temperature-machine-2.1.jar:2.1]
	at scalaz.Free.run(Free.scala:271) [temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432) [temperature-machine-2.1.jar:2.1]
	at scalaz.concurrent.Future$$anon$3.call(Future.scala:432) [temperature-machine-2.1.jar:2.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_65]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_65]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_65]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_65]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:272) ~[temperature-machine-2.1.jar:2.1]
	... 71 more
```

**Comment by tobyweston** [comment]
Update: I upgraded http4s from 0.16 to 0.18 and get the same issue 😢 

```
Sun 04-Feb-2018 19:43:53.709 [blaze-nio-fixed-selector-pool-1] ERROR error in requestLoop()
java.lang.NullPointerException: null
	at org.http4s.internal.parboiled2.ParserInput$StringBasedParserInput.length(ParserInput.scala:97) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.internal.parboiled2.Parser.__advance(Parser.scala:229) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.internal.parboiled2.Parser.runRule$1(Parser.scala:141) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.internal.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.internal.parboiled2.Parser.__run(Parser.scala:204) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.parser.Rfc2616BasicRules$.token(Rfc2616BasicRules.scala:89) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.Method$.$anonfun$fromString$1(Method.scala:48) ~[temperature-machine-2.1.jar:2.1]
	at scala.collection.MapLike.getOrElse(MapLike.scala:128) ~[temperature-machine-2.1.jar:2.1]
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126) ~[temperature-machine-2.1.jar:2.1]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.Method$.fromString(Method.scala:49) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.server.blaze.Http1ServerParser.collectMessage(Http1ServerParser.scala:52) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.server.blaze.Http1ServerStage.runRequest(Http1ServerStage.scala:123) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.server.blaze.Http1ServerStage.reqLoopCallback(Http1ServerStage.scala:102) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.server.blaze.Http1ServerStage.$anonfun$requestLoop$1(Http1ServerStage.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at org.http4s.server.blaze.Http1ServerStage.$anonfun$requestLoop$1$adapted(Http1ServerStage.scala:79) ~[temperature-machine-2.1.jar:2.1]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) [temperature-machine-2.1.jar:2.1]
	at org.http4s.blaze.util.Execution$$anon$1.execute(Executor.scala:27) [temperature-machine-2.1.jar:2.1]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68) [temperature-machine-2.1.jar:2.1]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284) [temperature-machine-2.1.jar:2.1]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284) [temperature-machine-2.1.jar:2.1]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284) [temperature-machine-2.1.jar:2.1]
	at org.http4s.blaze.channel.nio1.NIO1HeadStage.readReady(NIO1HeadStage.scala:61) [temperature-machine-2.1.jar:2.1]
	at org.http4s.blaze.channel.nio1.SelectorLoop.run(SelectorLoop.scala:134) [temperature-machine-2.1.jar:2.1]
```

**Comment by aeons** [comment]
Where in the code does this error happen?

**Comment by tobyweston** [comment]
In my code? I have no idea? The stack trace starts with the `SelectorLoop`. I'm running a http4s server which I'm assuming spins up `blaze-nio-fixed-selector-pool-1` serving requests.

Is it possible to somehow interfere with things when processing a request in a `HttpService`? Like could I be accidentally closing a connection somehow resulting in the NPE?

**Comment by aeons** [comment]
Ok, so it errors at startup? Or what happens to trigger it? I'm assuming it's in `temperature-machine`.

**Comment by aspic** [comment]
We are experiencing the same issue. This is consistent for for rather "large" (> 1MB) multi part requests. Maybe the size of the request could be an issue? We are also using the BlazeClient for constructing these requests.

**Comment by bryce-anderson** [comment]
@aspic, can you narrow this down to requests with a body, or are you seeing also with `GET`'s? There is some danger in how the current `Http1ServerStage` works (and presumably it affects the client as well) in that the request body can be consumed concurrently with the completion of a dispatch cycle so there could be some racy behavior if the body isn't being completely consumed within the service definition.

That may-or-may-not be this issue.

**Comment by aspic** [comment]
We are currently only experiencing this with requests with a body. But, we don't have a lot of GET requests between our http4s-client and server yet.

**Comment by aspic** [comment]
We are also experiencing this on GET requests, without any request body.

**Comment by bryce-anderson** [comment]
Thanks for the update @aspic, that will help narrow it down.

**Comment by bryce-anderson** [comment]
Another, simpler explanation is that there is a race between bytes from the socket reaching the servers read loop and the stage getting a `Disconnected` command and asking the parser to shutdown. If you're launching you application work on a different thread pool (a good idea) then that race becomes reasonably likely.

**Comment by bryce-anderson** [comment]
I'll try and craft a fix for the reset race. I'm going with 0.18 and it should roll into master relatively easy. @rossabaker, is that correct?

**Comment by rossabaker** [comment]
@bryce-anderson Yep.  release-0.18.x if you can do it compatibly, master if you can't.

**Comment by bryce-anderson** [comment]
I have a patch up for this (#1675), but I don't know if it's going to fix it. @aspic, @tobyweston, would either of you be willing to test the patch to see if it fixes things?

**Comment by aspic** [comment]
@bryce-anderson yes, absolutely :-) I'll just have to see if I can reproduce this somehow in a predictable manner first.

**Comment by bryce-anderson** [comment]
IF this is the bug, it might be a bit difficult to reproduce since it's intrinsically a race between threads.

**Comment by tobyweston** [comment]
Can do. My setup see a lot of them so happy to anecdotally comment on the lack of errors! What's the best way to get a JAR, can I update my `build.sbt` or is it build from source? Thanks btw 👍

**Comment by bryce-anderson** [comment]
Right now it's just a patch, based on the `release-0.18.x` branch. I'd suggest just checking it out and publishing local. I think that should publish a `0.18.1-SNAPSHOT`, but obviously you can change that to whatever you need.

**Comment by aspic** [comment]
Mm, it happens pretty consistently on one of our production applications. I can try this patch out tomorrow.

**Comment by bryce-anderson** [comment]
That PR has been merged into the `release-0.18.x` branch via commit c52f97462839f10b2baed4db456cc1c2d4949893, if that's you preferred way of giving it a test run.

**Comment by aspic** [comment]
We have been running with this fix in production for roughly 18 hours and haven't encountered the NPE yet. :-)

**Comment by rossabaker** [comment]
Since it's working in theory and in short practice, I'm going to close this. Please reopen if you see it again.

We'll release 0.18.1 soon. There is another minor fix and some dependency patches.
