### ISSUE TITLE
Server hanging on shutdown

### ISSUE THREAD

**Issue by BernardMarshall** [http4s/http4s#1512]
I have a sutuation where I am using 0.18.0-M4 and trying to shutdown the server in the overridden stream method. The cut down code to demonstrate the issue is:
```scala
import cats.effect.IO

import fs2.Stream

import org.http4s.util.StreamApp

object Main extends StreamApp[IO] {

  override def stream(
      args: List[String],
      requestShutdown: IO[Unit]): Stream[IO, Nothing] =
  /* Do initialisation which may fail and need to shutdown */
  sys.exit(0)
}
```
The idea is that some initialisation is done (e.g. start a number of services where any may fail). If the initialisation fails then the system should terminate. When the above code is run the server hangs in the shutdown hook code. The stack traces are:
```
"main" - Thread t@1
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <7e07db1f> (a scala.sys.ShutdownHookThread$$anon$1)
	at java.lang.Thread.join(Unknown Source)
	at java.lang.Thread.join(Unknown Source)
	at java.lang.ApplicationShutdownHooks.runHooks(Unknown Source)
	at java.lang.ApplicationShutdownHooks$1.run(Unknown Source)
	at java.lang.Shutdown.runHooks(Unknown Source)
	at java.lang.Shutdown.sequence(Unknown Source)
	at java.lang.Shutdown.exit(Unknown Source)
	- locked <2fa88e6> (a java.lang.Class)
	at java.lang.Runtime.exit(Unknown Source)
	at java.lang.System.exit(Unknown Source)
	at scala.sys.package$.exit(package.scala:40)
	at com.axiell.cdp.server.main.Main$.stream(Main.scala:17)
	at com.axiell.cdp.server.main.Main$.stream(Main.scala:11)
	at org.http4s.util.StreamApp.$anonfun$runStream$2(StreamApp.scala:62)
	at org.http4s.util.StreamApp$$Lambda$47/1199673596.apply(Unknown Source)
	at cats.effect.IO.$anonfun$flatMap$1(IO.scala:113)
	at cats.effect.IO$$Lambda$10/949057310.apply(Unknown Source)
	at cats.effect.internals.AndThen.processSuccess$1(AndThen.scala:48)
	at cats.effect.internals.AndThen.runLoop(AndThen.scala:65)
	at cats.effect.internals.AndThen.apply(AndThen.scala:34)
	at cats.effect.IO.unsafeStep(IO.scala:174)
	at cats.effect.IO.unsafeRunAsync(IO.scala:216)
	at cats.effect.IO.$anonfun$runAsync$1(IO.scala:169)
	at cats.effect.IO$$Lambda$37/1803669141.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at cats.effect.IO$.$anonfun$apply$1(IO.scala:370)
	at cats.effect.IO$$$Lambda$38/1836463382.apply(Unknown Source)
	at cats.effect.IO$.$anonfun$suspend$1(IO.scala:381)
	at cats.effect.IO$$$Lambda$8/209833425.apply(Unknown Source)
	at cats.effect.internals.AndThen.processSuccess$1(AndThen.scala:48)
	at cats.effect.internals.AndThen.runLoop(AndThen.scala:65)
	at cats.effect.internals.AndThen.apply(AndThen.scala:34)
	at cats.effect.IO.unsafeStep(IO.scala:175)
	at cats.effect.IO.unsafeRunTimed(IO.scala:264)
	at cats.effect.IO.unsafeRunSync(IO.scala:199)
	at org.http4s.util.StreamApp.main(StreamApp.scala:80)
	at com.axiell.cdp.server.main.Main.main(Main.scala)

   Locked ownable synchronizers:
	- None

"shutdownHook1" - Thread t@11
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <29eb5e05> (a cats.effect.internals.IOPlatform$OneShotLatch)
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at cats.effect.internals.IOPlatform$.$anonfun$unsafeResync$2(IOPlatform.scala:53)
	at cats.effect.internals.IOPlatform$$$Lambda$161/1372204843.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at cats.effect.internals.IOPlatform$.unsafeResync(IOPlatform.scala:53)
	at cats.effect.IO.unsafeRunTimed(IO.scala:268)
	at cats.effect.IO.unsafeRunSync(IO.scala:199)
	at org.http4s.util.StreamApp.$anonfun$addShutdownHook$2(StreamApp.scala:29)
	at org.http4s.util.StreamApp$$Lambda$48/2044903525.apply$mcV$sp(Unknown Source)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:34)

   Locked ownable synchronizers:
	- None
```
As can be seen the main thread is waiting for the shutdown thread to terminate. The shutdown thread is marked as async (I'm guessing because of StreamApp.scala:24?) and so it blocks on a latch waiting for the aysnc thread running the actual shutdown code to complete. Since the stream has not yet been returned by the stream method the execution of the stream termination code causes issues.

Should the above code work? If not then how do you handle the situation in the stream method where an error occurs (for whatever reason) and you need to terminate?

**Comment by aeons** [comment]
In my opinion the initialization code that may fail should return a failed stream, or a stream that emits an error exit code.

**Comment by ChristopherDavenport** [comment]
We could add a `Stream.emit(()) *> s2` which _might_ catch the above as it would be scoped into a stream. I'd need to actually test it but just a quick thought.

**Comment by BernardMarshall** [comment]
Thanks for the help. Returning an empty stream worked fine (I haven't got the codebase with the ExitCode in yet, but once that is available it will proivde a nice way to shutdown).
