### ISSUE TITLE
TimeoutException: Client response header timeout after 0 milliseconds.

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1774]
```scala
  import cats.effect.IO
  import cats.implicits._
  import fs2._
  import scala.concurrent.ExecutionContext.Implicits.global
  import scala.concurrent.duration._

  def fetch(client: Client[IO]) =
    client.expect[String]("https://httpbin.org/ip")

  Http1Client.stream[IO]().flatMap { client =>
    Scheduler[IO](1).flatMap { sc =>
      (Stream.eval(fetch(client)) ++ sc.sleep_[IO](1.seconds)).repeat
    }
  }.evalMap(s => IO(println(s))).compile.drain.unsafeRunSync
```

Runs about 5 requests, and then dies with:

```
[error] java.util.concurrent.TimeoutException: Client response header timeout after 0 milliseconds.
[error] 	at org.http4s.client.blaze.ClientTimeoutStage$$anon$1.run(ClientTimeoutStage.scala:45)
[error] 	at org.http4s.blaze.util.Execution$$anon$2.execute(Executor.scala:49)
[error] 	at org.http4s.blaze.util.TickWheelExecutor.schedule(TickWheelExecutor.scala:117)
[error] 	at org.http4s.client.blaze.ClientTimeoutStage.activateResponseHeaderTimeout(ClientTimeoutStage.scala:170)
[error] 	at org.http4s.client.blaze.ClientTimeoutStage.outboundCommand(ClientTimeoutStage.scala:93)
[error] 	at org.http4s.blaze.pipeline.Tail.sendOutboundCommand(Stages.scala:122)
[error] 	at org.http4s.blaze.pipeline.Tail.sendOutboundCommand$(Stages.scala:119)
[error] 	at org.http4s.client.blaze.Http1Connection.sendOutboundCommand(Http1Connection.scala:24)
[error] 	at org.http4s.client.blaze.Http1Connection.$anonfun$executeRequest$3(Http1Connection.scala:147)
```

Reported by @RibleStrype

**Comment by SystemFw** [comment]
can we reproduce with `IO` only, taking fs2 out of the picture?

**Comment by rossabaker** [comment]
A good one looks like this:

```
09:26:45.481 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Requesting connection: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:45.481 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Recycling connection: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:45.481 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - ClientTimeoutStage starting up at Wed Apr 11 09:26:45 EDT 2018
09:26:45.481 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Connection was idle. Running.
09:26:45.481 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Beginning request: GET https://httpbin.org/ip
09:26:45.482 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage Http1Connection sending outbound command: org.http4s.client.blaze.ClientTimeoutStage$RequestSendComplete$@62cf6d09
09:26:45.533 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 345 bytesProduced = 316, java.nio.HeapByteBuffer[pos=316 lim=16921 cap=16921]
09:26:45.533 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
09:26:45.534 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921]
09:26:45.534 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage Http1Connection sending outbound command: org.http4s.client.blaze.ClientTimeoutStage$ResponseHeaderComplete$@76d45be6
09:26:45.535 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Resetting org.http4s.client.blaze.Http1Connection after completing request.
09:26:45.535 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - ClientTimeoutStage shutting down at Wed Apr 11 09:26:45 EDT 2018
09:26:45.535 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Recycling connection: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:45.535 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Returning idle connection to pool: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

A bad one looks like this:

```
09:26:46.537 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Requesting connection: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:46.537 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Recycling connection: curAllocated=1 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:46.537 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - ClientTimeoutStage starting up at Wed Apr 11 09:26:46 EDT 2018
09:26:46.537 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Connection was idle. Running.
09:26:46.537 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Beginning request: GET https://httpbin.org/ip
09:26:46.538 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage Http1Connection sending outbound command: org.http4s.client.blaze.ClientTimeoutStage$RequestSendComplete$@62cf6d09
09:26:46.539 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Client stage is disconnecting due to response header timeout after 0 milliseconds.
09:26:46.539 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage ClientTimeoutStage sending outbound command: Disconnect
09:26:46.540 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - ReadBufferStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.540 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage ReadBufferStage sending outbound command: Disconnect
09:26:46.540 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - SSLStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.540 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - Stage SSLStage sending outbound command: Disconnect
09:26:46.540 [scala-execution-context-global-1242] DEBUG org.http4s.blaze.pipeline.Stage - closeWithError(EOF)
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage ByteBufferHead sending inbound command: Disconnected
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - SSLStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage SSLStage sending inbound command: Disconnected
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - ReadBufferStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage ReadBufferStage sending inbound command: Disconnected
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - ClientTimeoutStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage ClientTimeoutStage sending inbound command: Disconnected
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage Http1Connection sending outbound command: Disconnect
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - ClientTimeoutStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage ClientTimeoutStage sending outbound command: Disconnect
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - ReadBufferStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage ReadBufferStage sending outbound command: Disconnect
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - SSLStage shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Stage SSLStage sending outbound command: Disconnect
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - closeWithError(EOF)
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - Http1Connection shutting down at Wed Apr 11 09:26:46 EDT 2018
09:26:46.541 [anInnocuousThread] DEBUG org.http4s.blaze.pipeline.Stage - closeWithError(EOF)
09:26:46.543 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - expired requests: 0
09:26:46.543 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Dropped expired requests: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
09:26:46.543 [scala-execution-context-global-1242] DEBUG org.http4s.client.PoolManager - Invalidated connection, no pending requests. Shrinking pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

**Comment by rossabaker** [comment]
This runs indefinitely:

```scala
  Http1Client.stream[IO]().evalMap { client =>
    def io: IO[Unit] = for {
      s <- fetch(client)
      _ <- IO(println(s))
      _ <- Timer[IO].sleep(1.second)
      _ <- io
    } yield ()
    io
  }.compile.drain.unsafeRunSync
```

**Comment by rossabaker** [comment]
Fails:

```scala
  Http1Client.stream[IO]().flatMap { client =>
    (Stream.eval(fetch(client) <* Timer[IO].sleep(1.second))).repeat
  }.evalMap(s => IO(println(s))).compile.drain.unsafeRunSync
```

**Comment by rossabaker** [comment]
It works with async-http-client, to whose companion I've added a `stream` constructor.  This seems to be an interaction between fs2 and blaze-client.

**Comment by rossabaker** [comment]
Pinging @bryce-anderson, who may spot this quicker than I will.  Otherwise, I will dig deeper later today.

**Comment by tbrown1979** [comment]
I'm currently encountering this issue with a project I'm working on ^. Willing to help, but will have to spend some time looking into things

**Comment by bryce-anderson** [comment]
Do we know in which version this started happening, or has it always been happening?

**Comment by rossabaker** [comment]
Good question.  I haven't gone back in time.  I _think_ I reproduced on 0.18.8.  The repo will change moving backward in minor versions.

**Comment by bryce-anderson** [comment]
The problem is that the return value of the Kleisli [here](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala#L29) isn't referentially transparent and it's being reused in the Stream example. The [submit time](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala#L31) remains the same throughout all the requests and eventually times out. Adding a `F.suspend` to the body of the Kleisli fixes the stream example.

I'll put up a PR to fix it, but I don't know the best way to test it to prevent regressions.
