### ISSUE TITLE
Can't safely shut down TickWheelExecutor

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1821]
I tried moving a TickWheelExecutor into the blaze-client, so it could be shut down on the client shutdown, and we don't leak a thread.

Hilarity ensues:

```scala
java.lang.RuntimeException: TickWheelExecutor is shutdown
	at scala.sys.package$.error(package.scala:27)
	at org.http4s.blaze.util.TickWheelExecutor.schedule(TickWheelExecutor.scala:124)
	at org.http4s.blaze.util.TickWheelExecutor.schedule(TickWheelExecutor.scala:82)
	at org.http4s.client.blaze.ClientTimeoutStage.resetTimeout(ClientTimeoutStage.scala:164)
	at org.http4s.client.blaze.ClientTimeoutStage.$anonfun$checkTimeout$2(ClientTimeoutStage.scala:130)
```

This is inspired by @lbialy's work getting things running on graal, and having problems with the statically allocated thread.

**Comment by rossabaker** [comment]
My quick sketch looks like https://github.com/rossabaker/http4s/tree/issue-1821.

**Comment by armanbilge** [comment]
@OstapStrashevskii try putting everything inside of the `resource.use { ... ` block.
