### ISSUE TITLE
Exception on timeout listener registration

### ISSUE THREAD

**Issue by YulawOne** [http4s/http4s#2103]
I was benchmarking http4s with Monix and Jetty and i've noticed multiple errors in logs with following exception:
```
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.addListener(AsyncContextState.java:93)
	at org.http4s.servlet.AsyncHttp4sServlet.$anonfun$handleRequest$1(AsyncHttp4sServlet.scala:62)
	at org.http4s.servlet.AsyncHttp4sServlet.$anonfun$handleRequest$1$adapted(AsyncHttp4sServlet.scala:61)
	at monix.eval.internal.TaskCreate$.$anonfun$async$1(TaskCreate.scala:116)
	at monix.eval.internal.TaskCreate$.$anonfun$async$1$adapted(TaskCreate.scala:113)
	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:57)
	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:550)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:114)
	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:181)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

code:
```scala
object ApplicationHttp4s extends IOApp {
  implicit val scheduler: Scheduler = Scheduler.global

  def routes[F[_]: Sync] = new Http4sDsl[F] {
    val routes = HttpRoutes.of[F] {
      case GET -> Root / "api" / "index" =>
        Ok("Hello!")
    }
  }
  
  def stream[F[_]: ConcurrentEffect]: fs2.Stream[F, ExitCode] =
    JettyBuilder[F]
      .bindHttp(10080, "0.0.0.0")
      .mountService(routes[F].routes, "/")
      .serve

  def run(args: List[String]): IO[ExitCode] =
    stream[Task].compile.drain.as(ExitCode.Success).toIO
}
```

monix version - `3.0.0-RC2-d0feeba`
http4 version - `0.19.0-M2`
jdk version - `10.0.2`

it reproduces with `wrk -t1 -c1` benchmark configuration and it seems doesn't affect request itself but might slightly affect performance due throw.

**Comment by rossabaker** [comment]
Thanks!  I don't think this has anything to do with Monix, but it does show a flaw in the generic servlet layer.  See #2106 for a fix.
