### ISSUE TITLE
TimeoutException: Client response header timeout after 0 milliseconds. - Again

### ISSUE THREAD

**Issue by MarkusA380** [http4s/http4s#2142]
This issue is a continuation of [this issue](https://github.com/http4s/http4s/issues/1774), but using **0.19.0-M3** with `BlazeClientBuilder`.

The exception is as follows:

```
Exception in thread "main" java.util.concurrent.TimeoutException: Client response header timeout after 0 milliseconds.
        at org.http4s.client.blaze.ClientTimeoutStage$$anon$1.run(ClientTimeoutStage.scala:45)
        at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
        at org.http4s.blaze.util.TickWheelExecutor.schedule(TickWheelExecutor.scala:111)
        at org.http4s.client.blaze.ClientTimeoutStage.activateResponseHeaderTimeout(ClientTimeoutStage.scala:170)
        at org.http4s.client.blaze.ClientTimeoutStage.outboundCommand(ClientTimeoutStage.scala:93)
        at org.http4s.blaze.pipeline.Tail.sendOutboundCommand(Stages.scala:131)
        at org.http4s.blaze.pipeline.Tail.sendOutboundCommand$(Stages.scala:128)
        at org.http4s.client.blaze.Http1Connection.sendOutboundCommand(Http1Connection.scala:25)
        at org.http4s.client.blaze.Http1Connection.$anonfun$executeRequest$3(Http1Connection.scala:149)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:80)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:107)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:73)
        at monix.eval.Callback$BaseCallback.run(Callback.scala:246)
        at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:65)
        at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:31)
        at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:146)
        at monix.execution.internal.Trampoline.execute(Trampoline.scala:38)
        at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:65)
        at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
        at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
        at monix.execution.schedulers.AsyncScheduler.execute(AsyncScheduler.scala:29)
        at monix.eval.Callback$BaseCallback.onSuccess(Callback.scala:229)
        at monix.eval.Callback.apply(Callback.scala:64)
        at monix.eval.Callback.apply(Callback.scala:42)
        at org.http4s.syntax.AsyncOps$.$anonfun$fromFuture$2(AsyncSyntax.scala:19)
        at org.http4s.syntax.AsyncOps$.$anonfun$fromFuture$2$adapted(AsyncSyntax.scala:17)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
```

The snippet in question is:

```scala
  /** */
  private def withClient[A](f: Client[Task] => Task[A]) =
    BlazeClientBuilder.apply[Task](ExecutionContext.global)
      .withMaxTotalConnections(2)
      .resource
      .use(f)
```

The client successfully runs about ~30 requests (`client.expect[Json](...)`, see [here](https://circe.github.io/circe/api/io/circe/Json.html)) for ~20 seconds before the exception occurs.

Excuse any missing information or mistakes, I'm still learning.

**Comment by MarkusA380** [comment]
Some additional info:

When using the same code except for the following snippet, but with http4s 0.19.0-M2, the exception does not occur:

```scala
  /** */
  private def withClient[A](f: Client[Task] => Task[A]) =
    BlazeClientBuilder.apply[Task](ExecutionContext.global)
      .withRequestTimeout(5.seconds)
      .withIdleTimeout(maxTotalConnections = 2)
      .resource
      .use(f)
```

**Comment by rossabaker** [comment]
I think this is the same cause as the original bug.  The submit time is once again outside the delay:

```scala
      Resource.suspend {
        val key = RequestKey.fromRequest(req)
        val submitTime = Instant.now()
```

The fix is easy, but it would be great to expose this with a test first.

**Comment by rossabaker** [comment]
So the not-so-testable way to solve this is to put `submitTime` back in the same suspension as the rest of the resource.

The clean way to do this is to pass a `cats.effect.Timer` instance, and create a timeout stage based on it.  But this will add an effect to every read and write, and will be a (I think slight) performance hit.

**Comment by rossabaker** [comment]
Fixed by #2166.

**Comment by vlovgr** [comment]
I've been experiencing this issue as well, but when trying 0.19.1-SNAPSHOT, I'm now instead seeing the following message in the logs, and the request seems to never finish (hangs).

```
o.h.b.ResponseHeaderTimeoutStage: Cannot remove a disconnected stage ResponseHeaderTimeoutStage
```

Not sure if this two issues are related, @rossabaker? Should I open a separate issue for this?

**Comment by rossabaker** [comment]
That sounds like a separate issue.  Bonus points if it's reproducible.  We're fighting a few things that are hard to replicate.

**Comment by rossabaker** [comment]
Actually, that particular warning is fixed in https://github.com/http4s/blaze/pull/242.

**Comment by vlovgr** [comment]
Thanks for the quick reply @rossabaker! After doing a little bit more digging, I'm suspecting the hang to be this issue: https://github.com/http4s/http4s/issues/2068. If increasing `maxTotalConnections` to be strictly greater than the number of parallel requests, I'm no longer experiencing any hangs.
