### ISSUE TITLE
Abnormal NIO1HeadStage termination on timeout

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2156]
[Reported](https://gitter.im/http4s/http4s?at=5bb8b0f282893a2f3bab18b6) by @amsayk.  This is going to require a blaze release: https://github.com/http4s/blaze/pull/238

```
[info] [blaze-selector-0-1] ERROR o.h.b.c.n.NIO1HeadStage - Abnormal NIO1HeadStage termination 
[info] java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
[info] at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
[info] at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66) 
[info] at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
[info] at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193
[info] at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
[info] at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
[info] at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156) 
[info] at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
[info] [blaze-selector-0-1] ERROR o.h.s.b.Http1ServerStage$$anon$1 - Fatal Error: Error in requestLoop()
[info] java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
```

When that's released, we should race the response against an async task that is completed on an inbound timeout and produces a 503.

**Comment by rossabaker** [comment]
I have a unit test for this and I know how to fix it.
