### ISSUE TITLE
Abnormal NIO1HeadStage termination and Error in requestLoop() on client timeout

### ISSUE THREAD

**Issue by rlmark** [http4s/http4s#2229]
## Version 
We are using http4s version 0.20.0-M1 with blaze version 0.14.0-M9 

## Description
We are seeing the following pair of errors in the logs. The service completes the request successfully, so no errors are exposed to the client, but we believe these errors to be occurring on a per-client basis. So, when a client makes a request, they can make multiple requests to the service without triggering the exceptions, but once there is a pause in the rate of requests we see the errors in the logs. 

```
13:41:36.946 [blaze-selector-0-2] ERROR o.h.blaze.channel.nio1.NIO1HeadStage - Abnormal NIO1HeadStage termination
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
13:41:36.946 [blaze-selector-0-2] ERROR o.h.s.blaze.Http1ServerStage$$anon$1 - Fatal Error: Error in requestLoop()
java.util.concurrent.TimeoutException: Timeout of 30 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
```

Please let me know if there are additional details that would be helpful! Thank you!

**Comment by ptoussai** [comment]
I'm seeing the same errors in the log. It always happens after I just started the server, and after the first request (which is received correctly by the client without issue). At that point I haven't seen any real effect, besides the logs.
I'm not using an IOApp, and start the server using `val fiber = serverBuilder.resource.use(_ => IO.never).start.unsafeRunSync()`

**Comment by rossabaker** [comment]
What other timeout settings do you have?  Can someone share their full blaze configuration?  I'm having trouble reproducing this.

**Comment by jakubrozenbajger** [comment]
Every request to app result in following log.  
```
import cats.effect._
import cats.implicits._
import fs2.Stream
import org.http4s.implicits._
import org.http4s.server.blaze.BlazeServerBuilder
import org.http4s.{HttpRoutes, Response, Status}

object App extends IOApp {

  override def run(args: List[String]): IO[ExitCode] = {
    server[IO].compile.drain.as(ExitCode.Success)
  }

  def server[F[_] : ConcurrentEffect : Timer](implicit S: Sync[F]): Stream[F, ExitCode] = {
    import scala.concurrent.duration._
    BlazeServerBuilder[F]
      .bindHttp(8080, "localhost")
      .withIdleTimeout(3 second)
      .withHttpApp(HttpRoutes.of[F] { case _ => S.pure(Response[F](Status.Ok)) }.orNotFound)
      .serve
  }
}
```

```
[scala-execution-context-global-10] INFO  o.h.b.c.n.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8080 
[scala-execution-context-global-10] INFO  o.h.s.b.BlazeServerBuilder - 
  _   _   _        _ _     
 | |_| |_| |_ _ __| | | ___
 | ' \  _|  _| '_ \_  _(_-<
 |_||_\__|\__| .__/ |_|/__/
             |_| 
[scala-execution-context-global-10] INFO  o.h.s.b.BlazeServerBuilder - http4s v0.20.0-M1 on blaze v0.14.0-M9 started at http://127.0.0.1:8080/ 
[blaze-selector-0-1] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:59054 
[blaze-selector-0-1] ERROR o.h.b.c.n.NIO1HeadStage - Abnormal NIO1HeadStage termination 
java.util.concurrent.TimeoutException: Timeout of 3 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
[blaze-selector-0-1] ERROR o.h.s.b.Http1ServerStage$$anon$1 - Fatal Error: Error in requestLoop() 
java.util.concurrent.TimeoutException: Timeout of 3 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
[blaze-selector-0-1] ERROR o.h.b.c.n.NIO1HeadStage - Abnormal NIO1HeadStage termination 
java.util.concurrent.TimeoutException: Timeout of 3 seconds triggered. Killing pipeline.
	at org.http4s.blaze.pipeline.stages.TimeoutStageBase$$anon$1.run(TimeoutStageBase.scala:29)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:261)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:193)
	at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:200)
	at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:153)
	at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:156)
	at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:55)
[blaze-selector-0-0] INFO  o.h.b.c.ServerChannel - Closing NIO1 channel /127.0.0.1:8080 
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0-0 
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0-1 
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0-2 
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0-3 
[shutdownHook1] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0-4 

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```
BTW. Same issue with websockets, but when I send messages with delay between each message smaller than timeout then it works correctly.

**Comment by rossabaker** [comment]
Which client is this with?  OS?  This is what I get with `http http://localhost:8080/http4s/ping` on @jakubrozenbajger's example.  I get similar with curl.

```
[info] Running App 
16:35:20.287 [scala-execution-context-global-39] INFO  o.h.b.c.nio1.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8080
16:35:20.291 [blaze-selector-0-0] DEBUG o.h.blaze.channel.nio1.SelectorLoop - Channel initialized.
16:35:20.292 [scala-execution-context-global-39] INFO  o.h.server.blaze.BlazeServerBuilder - 
  _   _   _        _ _     
 | |_| |_| |_ _ __| | | ___
 | ' \  _|  _| '_ \_  _(_-<
 |_||_\__|\__| .__/ |_|/__/
             |_|
16:35:20.333 [scala-execution-context-global-39] INFO  o.h.server.blaze.BlazeServerBuilder - http4s v0.20.0-M1 on blaze v0.14.0-M9 started at http://127.0.0.1:8080/
16:35:26.652 [blaze-selector-0-1] DEBUG o.h.blaze.channel.nio1.SelectorLoop - Channel initialized.
16:35:26.653 [blaze-selector-0-1] DEBUG o.h.blaze.channel.nio1.NIO1HeadStage - Starting up.
16:35:26.653 [blaze-selector-0-1] DEBUG o.h.blaze.channel.nio1.NIO1HeadStage - Stage NIO1HeadStage sending inbound command: Connected
16:35:26.653 [blaze-selector-0-1] DEBUG o.h.b.p.stages.QuietTimeoutStage - Starting up.
16:35:26.654 [blaze-selector-0-1] DEBUG o.h.b.p.stages.QuietTimeoutStage - Stage QuietTimeoutStage sending inbound command: Connected
16:35:26.654 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Starting HTTP pipeline
16:35:26.691 [blaze-selector-0-1] INFO  o.h.b.c.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:46276
16:35:26.702 [scala-execution-context-global-38] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Websocket key: None
Request headers: Headers(Host: localhost:8080, Connection: keep-alive, Accept-Encoding: gzip, deflate, Accept: */*, User-Agent: HTTPie/0.9.9)
16:35:26.772 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - closeConnection()
16:35:26.772 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down HttpPipeline
16:35:26.772 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down.
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down HttpPipeline
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down.
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.b.p.stages.QuietTimeoutStage - Shutting down.
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.blaze.channel.nio1.NIO1HeadStage - Shutting down.
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.blaze.channel.nio1.NIO1HeadStage - Stage NIO1HeadStage sending inbound command: Disconnected
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.b.p.stages.QuietTimeoutStage - Shutting down.
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.b.p.stages.QuietTimeoutStage - Stage QuietTimeoutStage sending inbound command: Disconnected
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down HttpPipeline
16:35:26.773 [blaze-selector-0-1] DEBUG o.h.s.blaze.Http1ServerStage$$anon$1 - Shutting down.
```

**Comment by jakubrozenbajger** [comment]
Newest Chromium on Manjaro Linux. I'll try to debug tomorrow if you cannot reproduce this issue.

**Comment by rossabaker** [comment]
Aha!  It happens on Chrome and Firefox.

**Comment by rossabaker** [comment]
So it actually is a real timeout.  It's because the idleTimeout is not just the timeout for an active request, but for a persistent connection.  This is the server too loudly chasing off a persistent connection that the browser kept.

#2244 makes it quieter and less scary with the existing semantics.

#2245 opens a discussion about whether we're conflating settings and what smarter things we might do.
