### ISSUE TITLE
IdleTimeoutStage exception on the client

### ISSUE THREAD

**Issue by cquiroz** [http4s/http4s#2277]
I'm seeing an exception sometimes when doing client calls:

```
seqexec_web_server java.lang.Exception: This stage 'IdleTimeoutStage' isn't connected!
seqexec_web_server     at org.http4s.blaze.pipeline.Tail._stageDisconnected(Stages.scala:218)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:90)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
seqexec_web_server     at org.http4s.blazecore.IdleTimeoutStage.channelRead(IdleTimeoutStage.scala:12)
seqexec_web_server     at org.http4s.blazecore.IdleTimeoutStage.readRequest(IdleTimeoutStage.scala:35)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:88)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
```

**Comment by Daenyth** [comment]
> It's a known issue with unknown cause. I spent an entire flight chasing that and failed.
> A good example of "we've found the bugs in Blaze, but the ones that are left are hard to fix."

- https://gitter.im/http4s/http4s?at=5efe3854b8152d34847a4187

**Comment by rossabaker** [comment]
@Daenyth Had you seen this again when you bumped this?  Trying to get a feel for how fresh this is.
