### ISSUE TITLE
Unexpected behaviour of Retry middleware

### ISSUE THREAD

**Issue by mitallast** [http4s/http4s#2290]
I'm testing 0.19.0 and 0.20.M3 versions with same unexpected behaviour using Retry middleware.

I shutdown local server for emulate connection erros, with this scriptlet:
```scala

import cats.effect._
import org.http4s.client.blaze._
import org.http4s.client._
import org.http4s.client.middleware.{Retry, RetryPolicy}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

object ExampleApp extends App {

  implicit val cs: ContextShift[IO] = IO.contextShift(global)
  implicit val timer: Timer[IO] = IO.timer(global)

  val max = 2
  val policy = RetryPolicy[IO] { attempts: Int =>
    println(s"[test] retry attempts: $attempts")
    if (attempts >= max) None
    else Some(1.seconds)
  }

  val program = BlazeClientBuilder[IO](global).resource.use { client =>
    println(s"[test] retry use client")
    val retryClient = Retry[IO](policy)(client)
    retryClient.expect[String]("http://localhost:8080")
  }

  program.attempt.unsafeRunSync() match {
    case Right(res) =>
      println(s"[test] success: $res")
    case Left(ex) =>
      println(s"[test] error: $ex")
      ex.printStackTrace()
  }
}
```
I expected to see at least one attempt, but the exception was thrown right away:
```sh
sbt:test-http4s> run
[info] Running org.mitallast.ExampleApp
[test] retry use client
[test] error: java.net.ConnectException: Connection refused
java.net.ConnectException: Connection refused
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
        at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at sun.misc.InnocuousThread.run(InnocuousThread.java:74)
[success] Total time: 2 s, completed Nov 19, 2018 3:43:09 PM
```

using a debugger I discovered a potential problem, but not sure: 
https://github.com/typelevel/cats-effect/blob/v1.0.0/core/shared/src/main/scala/cats/effect/Resource.scala#L353

```scala
  override def attempt[A](fa: Resource[F, A]): Resource[F, Either[E, A]] =
    fa match {
      case Allocate(fa) =>
        Allocate[F, Either[E, A]](F.attempt(fa).map {
          case Left(error) => (Left(error), (_: ExitCase[Throwable]) => F.unit)
          case Right((a, release)) => (Right(a), release)
        })
      case Bind(source: Resource[F, Any], fs: (Any => Resource[F, A])) =>
        Suspend(F.pure(source).map { source =>
          Bind(attempt(source), (r: Either[E, Any]) => r match {
            case Left(error) => Resource.pure(Left(error))
            case Right(s) => attempt(fs(s))
          })
        })
      case Suspend(resource) =>
        Suspend(resource.map(_.attempt))
    }
```

At runtime of this application variable `fa` has type Suspend[IO[A]], means that variable `resourse` has type IO[A], means that IO.map() will be ignored on error, following the cats effect IO implementation and rules. 

PS. I'm not shure, is this problem related to http4s or cats-effect

**Comment by rossabaker** [comment]
It works against a `Client.fromHttpApp` that raises a `ConnectException` on the first request and succeeds on the next.  The blaze-client returns a `Suspend`ed resource.  I think you've identified the problematic line in cats-effect.  Still thinking about whether that's a problem in cats-effect or in our use of it. :thinking:

**Comment by mitallast** [comment]
Ok, thanks!
I'm try fix with PR https://github.com/typelevel/cats-effect/pull/421

**Comment by rossabaker** [comment]
Yes, I'm increasingly convinced that the cats-effect ticket is the proper solution.

**Comment by rossabaker** [comment]
Closing after the cats-effect fix.  Please reopen if it's still a problem in http4s.
