### ISSUE TITLE
Shutdown server on request

### ISSUE THREAD

**Issue by sameersingh** [http4s/http4s#231]
I need a server that I can terminate from client side using a request, and am struggling to get it working.

Here's what my attempt looks like:
````scala
object Server extends App {
  var task: Server = _
  val blaze = BlazeBuilder.bindHttp(8080)

  val service = HttpService {
    case req@GET -> Root / "hello" =>
      Ok("Hello, better world.")
    case req@GET -> Root / "shutdown" => {
      Task({ Thread.sleep(2000); task.shutdownNow(); }).runAsync(_ match { case -\/(e) => e.printStackTrace(); })
      Ok("Bye!")
    }
  }

  task = blaze.mountService(service).run
  task.awaitShutdown()
  println("Server shut down.") // I need to continue from here
}
````

When I send the `localhost:8080/shutdown` `POST` request, I get back a `Bye!` response, but the server doesn't terminate and the process never prints the `Server shut down.` string. Instead, I get the following (after 2 seconds):

````
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-0
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-1
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-2
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-3
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-4
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-5
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-6
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-7
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-8
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-9
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-10
[error] [pool-1-thread-2] INFO org.http4s.blaze.channel.nio1.SelectorLoop - Shutting down SelectorLoop FixedPoolLoop-11
[error] java.io.IOException: No such file or directory
[error] 	at sun.nio.ch.NativeThread.signal(Native Method)
[error] 	at sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:283)
[error] 	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
[error] 	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
[error] 	at org.http4s.blaze.channel.nio1.NIO1ServerChannelFactory$NIO1ServerChannel.close(NIO1ServerChannelFactory.scala:39)
[error] 	at org.http4s.server.blaze.BlazeBuilder$$anonfun$start$1$$anon$1$$anonfun$shutdown$1.apply(BlazeServer.scala:117)
[error] 	at org.http4s.server.blaze.BlazeBuilder$$anonfun$start$1$$anon$1$$anonfun$shutdown$1.apply(BlazeServer.scala:116)
[error] 	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
[error] 	at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:266)
[error] 	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
[error] 	at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$4.apply(Task.scala:274)
[error] 	at scalaz.concurrent.Task$.Try(Task.scala:379)
[error] 	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
[error] 	at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:274)
[error] 	at scalaz.concurrent.Future.step(Future.scala:110)
[error] 	at scalaz.concurrent.Future.listen(Future.scala:76)
[error] 	at scalaz.concurrent.Future.runAsync(Future.scala:143)
[error] 	at scalaz.concurrent.Future.run(Future.scala:160)
[error] 	at scalaz.concurrent.Task.run(Task.scala:97)
[error] 	at org.http4s.server.Server$class.shutdownNow(Server.scala:12)
[error] 	at org.http4s.server.blaze.BlazeBuilder$$anonfun$start$1$$anon$1.shutdownNow(BlazeServer.scala:115)
[error] 	at collective_ie.interactive.Server$$anonfun$1$$anonfun$2.apply(Http4sUI.scala:44)
[error] 	at collective_ie.interactive.Server$$anonfun$1$$anonfun$2.apply(Http4sUI.scala:44)
[error] 	at scalaz.concurrent.Task$.Try(Task.scala:379)
[error] 	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:281)
[error] 	at scalaz.concurrent.Task$$anonfun$apply$10.apply(Task.scala:281)
[error] 	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
[error] 	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:367)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
````

Any ideas how I can achieve this?

**Comment by bryce-anderson** [comment]
I'll take a look and see what I can find. Do you know if the server is still responsive, or it just fails to exit the ```task.awaitShutdown()``` call?

**Comment by bryce-anderson** [comment]
Note that if you use the NIO2 backend, it still logs an error, but completes the program as desired.
```scala
val blaze = BlazeBuilder.bindHttp(8080)
                          .withNio2(true)
```
I'll continue to dig into this further.

**Comment by sameersingh** [comment]
Yeah, I can reproduce the above with the NIO2 backend, thanks!

Without NIO2, the server is unresponsive and the connection is closed, just doesn't exit `awaitShutdown()`.

**Comment by bryce-anderson** [comment]
Commit https://github.com/http4s/blaze/commit/62277e11e5ac308d86bb416ff949b1fa3e5f8c72 appears to address your issues. Note that this is really a blaze issue and not directly a http4s issue. Does using NIO2 work for for the immediate future? If its not necessary, I'd liked to avoid the domino release effect.

**Comment by sameersingh** [comment]
Yes, NIO2 suffices. I'm an expert at ignoring Exceptions I don't understand :)

**Comment by Verneri** [comment]
It seems i have this problem with java 8 but not with java 7. (and i'm using http4s v0.7.0)
