### ISSUE TITLE
Inconsistent "Host header required for HTTP/1.1 request" error

### ISSUE THREAD

**Issue by LLCampos** [http4s/http4s#2487]
Hello :) 

Using version `0.20.0-M7`, but also happens on `0.19.0`. 

```scala
import cats.effect.{ContextShift, IO}
import org.http4s.Uri
import org.http4s.client.blaze.BlazeClientBuilder

import scala.concurrent.ExecutionContext.Implicits.global


object IssueBad extends App {
  private implicit val cs: ContextShift[IO] = IO.contextShift(global)

  val uri: Uri = Uri().withPath(s"http://localhost:8080")

  BlazeClientBuilder[IO](global).resource.use { client =>
    client.expect[String](uri)
  }.unsafeRunSync()
}
```

This fails for me with: 

```
Exception in thread "main" java.lang.IllegalArgumentException: Host header required for HTTP/1.1 request
	at org.http4s.client.blaze.Http1Connection.validateRequest(Http1Connection.scala:329)
	at org.http4s.client.blaze.Http1Connection.executeRequest(Http1Connection.scala:124)
	at org.http4s.client.blaze.Http1Connection.$anonfun$runRequest$1(Http1Connection.scala:103)
	at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$unsafeRegister$1(Deferred.scala:205)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$unsafeRegister$1$adapted(Deferred.scala:205)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$notifyReadersLoop$1(Deferred.scala:241)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I can fix it just by turning the `Uri` into a `String`:

```scala
import cats.effect.{ContextShift, IO}
import org.http4s.Uri
import org.http4s.client.blaze.BlazeClientBuilder

import scala.concurrent.ExecutionContext.Implicits.global


object IssueOK extends App {
  private implicit val cs: ContextShift[IO] = IO.contextShift(global)

  val uriString: String = Uri().withPath("http://localhost:8080").toString()

  BlazeClientBuilder[IO](global).resource.use { client =>
    client.expect[String](uriString)
  }.unsafeRunSync()
}
```

It also fails, since I don't have anything running at `localhost:8080`, but this error is expected.

```
Exception in thread "main" java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at java.lang.Thread.run(Thread.java:748)
```

I would expect that both pieces of code to have the same behavior.

**Comment by rossabaker** [comment]
I agree.  This relates to #2483.  But I think we can fix this one independently of that broader discussion.

**Comment by rossabaker** [comment]
On second glance, I think it's because you're using `Uri.withPath` and passing more than a path.  The client doesn't know there's a host embedded therein.  Try it with `Uri.fromString` or (since it's a literal) `Uri.uri`.

**Comment by LLCampos** [comment]
Thanks for the suggestions. :) But the truth is that both of the examples are using `Uri.withPath`, and one of them works. So, I would still say this is more than a "support" issue?

**Comment by rossabaker** [comment]
Okay, I think it's fair to call it a bug.  The URI type shouldn't allow incorrect paths like that.  We want to replace the type anyway.  We'll leave this open to make sure it works with the reformed type.

**Comment by kevinmeredith** [comment]
```scala
$amm
Loading...
Welcome to the Ammonite Repl 1.0.3
(Scala 2.12.4 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`org.http4s::http4s-core:0.20.0-M7` 
import $ivy.$                                  

@ import org.htt 
http4s
@ import org.http4s.Uri 
import org.http4s.Uri

@ Uri().withPath(s"http://localhost:8080") 
res2: Uri = Uri(None, None, "http://localhost:8080", Query(), None)
```

So the problem is that the entire URL, not the path, is being passed to `Uri#withUri`?

Additionally, is the root cause that there's no validation that the input `String` to `withPath` is a valid path?

Reference: https://github.com/http4s/http4s/blob/v0.20.0-M7/core/src/main/scala/org/http4s/Uri.scala#L16-L30

**Comment by kevinmeredith** [comment]
Could you please look at my [question](https://github.com/http4s/http4s/issues/2487#issuecomment-482803129), @rossabaker?

**Comment by rossabaker** [comment]
The problem is that `Uri.withPath` assumes the entire thing is a path, rather than noting that part of it should be the scheme and authority.  `URI` as a case class is tempting, but it allows this trap.

For some prior art, `java.net.URI` does not have setters on the individual components.  You have to reparse the entire `String`.  That's not efficient when constructing a `String`, but does neatly work around this issue.

**Comment by kevinmeredith** [comment]
Thanks, Ross, for the explanation. So the following seem to me to be possible courses of action:

1. Take `java.net.URI`'s approach, which means re-parsing the entire `String`
2. Validate the input to `Uri#withPath`'s input
3. Leave it as-is

1 would be a breaking change since `withPath`, along with maybe other methods, would be deleted. 2 would be a breaking change, I think, since it'd, I assume, change the return type of `Uri#withPath` to be an `Option[Uri]` or `Either[?, Uri]`? 

What are your thoughts, Ross?
