### ISSUE TITLE
Error during inactivity of SSL connections

### ISSUE THREAD

**Issue by retriku** [http4s/http4s#2744]
I have encountered error when after making a call to some SSL endpoint using Blaze Client, and then having some inactivity period (5-7minutes) client starts to log error `javax.net.ssl.SSLException: SSL Handshake WRAP produced 0 bytes: Status = OK HandshakeStatus = NEED_WRAP bytesConsumed = 0 bytesProduced = 0`.

To reproduce this, take http4s `quickstart` example (`$ sbt -sbt-version 1.2.8 new http4s/http4s.g8 -b 0.20`) and add SSL certifiacte to blaze server. Call `https://localhost:8080/joke`. Observe logs:
```[Thread-12] ERROR o.h.b.p.s.SSLStage - Handshake failure with no pending results 
javax.net.ssl.SSLException: SSL Handshake WRAP produced 0 bytes: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
	at org.http4s.blaze.pipeline.stages.SSLStage.sslHandshakeLoop$1(SSLStage.scala:206)
	at org.http4s.blaze.pipeline.stages.SSLStage.sslHandshake(SSLStage.scala:229)
	at org.http4s.blaze.pipeline.stages.SSLStage.$anonfun$sslHandshake$2(SSLStage.scala:209)
	at org.http4s.blaze.pipeline.stages.SSLStage.$anonfun$sslHandshake$2$adapted(SSLStage.scala:208)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:19)
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:18)
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:57)
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67)
	at org.http4s.blaze.util.Actor.$bang(Actor.scala:45)
	at org.http4s.blaze.util.SerialExecutionContext.execute(SerialExecutionContext.scala:25)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.completed(ByteBufferHead.scala:53)
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.completed(ByteBufferHead.scala:43)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```

You can also check https://github.com/retriku/quickstart-http4s-ssl for runnable code:
- sbt run
- https://localhost:8080/joke

Possibly duplicate of https://github.com/http4s/http4s/issues/2192

Setup
JVM: openjdk version "11.0.2" 2019-01-15
Scala: 2.12.8
Http4s: 0.20.6
Blaze: 0.14.6

**Comment by rossabaker** [comment]
Interesting that you're on JDK 11.  We saw this error a lot when we first started testing on it, but it seemed to be fixed.  Thanks for the report and the repo.  We'll take another look.

**Comment by exoego** [comment]
I saw similar `javax.net.ssl.SSLException: SSL Handshake WRAP produced 0 bytes: Status = OK HandshakeStatus = NEED_WRAP bytesConsumed = 0 bytesProduced = 0` while running [scala-steward](https://github.com/fthomas/scala-steward) to private repositories.
* JDK 11.0.2
* Scala 2.12.8
* http4s 0.10.10

It does not happen if running on JDK 8.

**Comment by rossabaker** [comment]
I never was able to identify what changed in the SSL Engine implementation in JDK 11. I imagine that might be a strong clue toward fixing it.

**Comment by sholokhov** [comment]
Hi!
We also see this issue with http4s client (JDK 11.0.4, Scala 2.12.9):
```
2019-08-23 10:21:23 o.h.b.p.s.SSLStage [ERROR] Handshake failure with no pending results
javax.net.ssl.SSLException: SSL Handshake WRAP produced 0 bytes: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
	at org.http4s.blaze.pipeline.stages.SSLStage.sslHandshakeLoop$1(SSLStage.scala:191) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.pipeline.stages.SSLStage.sslHandshake(SSLStage.scala:214) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.pipeline.stages.SSLStage.$anonfun$sslHandshake$2(SSLStage.scala:194) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.pipeline.stages.SSLStage.$anonfun$sslHandshake$2$adapted(SSLStage.scala:193) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64) ~[scala-library-2.12.9.jar:na]
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:19) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:18) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:57) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.reSchedule(Actor.scala:77) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:54) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.reSchedule(Actor.scala:77) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:54) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.reSchedule(Actor.scala:77) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:54) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.reSchedule(Actor.scala:77) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:54) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.reSchedule(Actor.scala:77) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:54) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:67) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.Actor.$bang(Actor.scala:45) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.util.SerialExecutionContext.execute(SerialExecutionContext.scala:25) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.Promise.complete(Promise.scala:53) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.Promise.complete$(Promise.scala:52) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.Promise.success(Promise.scala:86) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.Promise.success$(Promise.scala:86) ~[scala-library-2.12.9.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187) ~[scala-library-2.12.9.jar:na]
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.completed(ByteBufferHead.scala:53) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$1.completed(ByteBufferHead.scala:43) ~[org_http4s_blaze_core_2_12.jar:0.14.5]
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127) ~[na:na]
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219) ~[na:na]
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

It goes in infinite loop and drives GC crazy, so we have almost 100% CPU usage:
<img width="1649" alt="Screenshot 2019-08-23 at 12 39 35 PM" src="https://user-images.githubusercontent.com/2879049/63587202-9617e400-c5a3-11e9-8b39-b16106ac822f.png">

**Comment by Discipe** [comment]
I just got this exception by running `http4s/http4s.g8` example locally on JDK11. Switching to Java 8 helps, but this is weird: we have multiple web services based on http4s running in production on JDK11 and we never encounter such behavior. We didn't ever use JDK8 with http4s and I never saw "Handshake failure with no pending results" in our logs nor high CPU for such applications.

**Comment by Discipe** [comment]
I just got this exception by running http4s/http4s.g8 example locally on JDK11. Switching to Java 8 helps, but this is weird: we have multiple web services based on http4s running in production on JDK11 and we never encounter such behavior. We didn't ever use JDK8 with http4s and I never saw "Handshake failure with no pending results" in our logs nor high CPU for such applications.
For now, I'm clueless what could be the difference.

**Comment by ScalaWilliam** [comment]
I am having this issue as well. JDK 11, Scala 2.13. It happens often on the very first SSL usage within the app lifetime, and only then (so far).
