### ISSUE TITLE
async-http-client: duplicate handler

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2779]
Under load, sending requests with bodies with the async HTTP client backend fails intermittently:

```scala
[info] java.lang.IllegalArgumentException: Duplicate handler name: request-body-streamer
[info] 	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1066)
[info] 	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
[info] 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:204)
[info] 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
[info] 	at org.asynchttpclient.netty.request.body.NettyReactiveStreamsBody.write(NettyReactiveStreamsBody.java:63)
[info] 	at org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:426)
[info] 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithOpenChannel(NettyRequestSender.java:259)
[info] 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:141)
[info] 	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:113)
[info] 	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:241)
[info] 	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:210)
[info] 	at org.http4s.client.asynchttpclient.AsyncHttpClient$.$anonfun$allocate$4(AsyncHttpClient.scala:48)
[info] 	at org.http4s.client.asynchttpclient.AsyncHttpClient$.$anonfun$allocate$4$adapted(AsyncHttpClient.scala:47)
```

Similar to https://github.com/AsyncHttpClient/async-http-client/issues/1627.

**Comment by rossabaker** [comment]
[Reproduction](https://github.com/rossabaker/http4s-bugs/tree/issue-2779), based on a gist from @sherwinschiu.

**Comment by rossabaker** [comment]
I think the problem is that when the `NettySubscriber` cancels, the `StreamSubscriber` is under no obligation to send an `onComplete` or `onError` event.  The `NettySubscriber` should remove the channel handler when it cancels.  But cancellation is handled by the parent `HandlerSubscriber` from netty-reactive-streams, so there's no hook to clean up the resources.

**Comment by rossabaker** [comment]
Better discussion: https://github.com/AsyncHttpClient/async-http-client/issues/1660
