### ISSUE TITLE
NoSuchMethodError in MultipartParser in 0.21.0-SNAPSHOT

### ISSUE THREAD

**Issue by eikek** [http4s/http4s#2875]
Hello,

I'm trying http4s with fs2 2.0.0 using the current SNAPSHOT where this has been added recently. I know this is SNAPSHOT and very young stuff, and I hope I'm not bothering with something obvious. To me it looks very strange enough to write this….

I created this http4s Test code (basically the example from the website) where it tries to decode a multipart request:

``` scala
import org.http4s.multipart.Multipart
import cats.effect._, org.http4s._, org.http4s.dsl.io._, scala.concurrent.ExecutionContext.Implicits.global
import org.http4s.server.blaze._
import org.http4s.implicits._
import org.http4s.server.Router

object Test {
  implicit val cs: ContextShift[IO] = IO.contextShift(global)
  implicit val timer: Timer[IO] = IO.timer(global)

  val helloWorldService = HttpRoutes.of[IO] {
    case req @ POST -> Root / "file" =>
      for {
        mp   <- req.as[Multipart[IO]]
        resp <- Ok(s"ok: ${mp.parts.size}")
      } yield resp
  }

  val httpApp = Router("/" -> helloWorldService).orNotFound
  val serverBuilder = BlazeServerBuilder[IO].bindHttp(8088, "localhost").withHttpApp(httpApp)
  val fiber = serverBuilder.resource.use(_ => IO.never).start

  def main(args: Array[String]): Unit = {
    val f = fiber.unsafeRunSync()
    println("Hit some key to stop")
    Console.in.read()
    f.cancel.unsafeRunSync()
  }
}
```
If I then run this curl command:
``` bash
curl -XPOST -F file=@test.pdf http://localhost:8088/file
```
The request times out, because the server crashed with an `NoSuchMethodError` in the fs2 library:
```
Hit some key to stop
[scala-execution-context-global-13] INFO  o.h.b.c.n.NIO1SocketServerGroup - Service bound to address /127.0.0.1:8088 
[scala-execution-context-global-13] INFO  o.h.s.b.BlazeServerBuilder - 
  _   _   _        _ _
 | |_| |_| |_ _ __| | | ___
 | ' \  _|  _| '_ \_  _(_-<
 |_||_\__|\__| .__/ |_|/__/
             |_| 
[scala-execution-context-global-13] INFO  o.h.s.b.BlazeServerBuilder - http4s v0.21.0-SNAPSHOT on blaze v0.14.8 started at http://127.0.0.1:8088/ 
[blaze-selector-1] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:58678 
[blaze-selector-2] INFO  o.h.b.c.n.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:58684 
java.lang.NoSuchMethodError: fs2.Pull$.stream$extension(Lfs2/internal/FreeC;)Lfs2/internal/FreeC;
	at org.http4s.multipart.MultipartParser$.ignorePrelude(MultipartParser.scala:203)
	at org.http4s.multipart.MultipartParser$.$anonfun$parseToPartsStream$1(MultipartParser.scala:43)
	at org.http4s.multipart.MultipartParser$.$anonfun$parseToPartsStream$1$adapted(MultipartParser.scala:42)
	at fs2.Stream$.through$extension(Stream.scala:2596)
	at org.http4s.multipart.MultipartDecoder$.$anonfun$decoder$1(MultipartDecoder.scala:15)
	at org.http4s.EntityDecoder$$anon$7.decode(EntityDecoder.scala:168)
	at org.http4s.Message.attemptAs(Message.scala:204)
	at org.http4s.Message.attemptAs$(Message.scala:203)
	at org.http4s.Request.attemptAs(Message.scala:239)
	at org.http4s.Message.as(Message.scala:216)
	at org.http4s.Message.as$(Message.scala:214)
	at org.http4s.Request.as(Message.scala:239)
	at Test$$anonfun$1.applyOrElse(Test.scala:20)
	at Test$$anonfun$1.applyOrElse(Test.scala:16)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:310)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:306)
	at org.http4s.HttpRoutes$.$anonfun$of$2(HttpRoutes.scala:64)
	at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[scala-execution-context-global-28] INFO  o.h.s.b.Http1ServerStage$$anon$1 - HTTP body not read to completion. Dropping connection. 
```
I don't get why that happens looking at the code. It seems to me that this is in the fs2 library, but I'm not sure and I couldn't find an example to reproduce it only using imports from `fs2._` (which is probably caused by my inability).

What do you think? 

Thanks!

**Comment by eikek** [comment]
Soo…, never mind. It is some sbt/dependency problem in my setup.

**Comment by eikek** [comment]
For the record: The reason was that the snapshots on sonatype are not new enough. They are still referenceng fs2 1.1.0-M1. Sorry for the noise.
