### ISSUE TITLE
Removal of UrlCodingUtils in 0.20.12 causing NoClassDefFoundError at runtime

### ISSUE THREAD

**Issue by NAJ10** [http4s/http4s#2936]
Tried to upgrade a project from 0.20.11 to 0.20.12 today that uses Rho but get an exception at startup
java.lang.NoClassDefFoundError: org/http4s/util/UrlCodingUtils$
        at org.http4s.rho.bits.PathTree$.go$1(PathTree.scala:36)
        at org.http4s.rho.bits.PathTree$.splitPath(PathTree.scala:41)
        at org.http4s.rho.bits.PathTreeOps.org$http4s$rho$bits$PathTreeOps$$keyToPath(PathTree.scala:86)
        at org.http4s.rho.bits.PathTreeOps$Node.walkTree(PathTree.scala:215)
        at org.http4s.rho.bits.PathTreeOps$Node.walkTree$(PathTree.scala:214)
        at org.http4s.rho.bits.PathTreeOps$MatchNode.walkTree(PathTree.scala:278)
        at org.http4s.rho.bits.PathTreeOps$PathTree.getResult(PathTree.scala:78)
        at org.http4s.rho.CompileRoutes$.$anonfun$foldRoutes$2(CompileRoutes.scala:48)
        at cats.data.KleisliSemigroupK.$anonfun$combineK$1(Kleisli.scala:470)
        at cats.data.KleisliSemigroupK.$anonfun$combineK$1(Kleisli.scala:470)
        at cats.data.KleisliSemigroupK.$anonfun$combineK$1(Kleisli.scala:470)
        at cats.data.Kleisli.apply(Kleisli.scala:83)
        at kamon.http4s.middleware.server.KamonSupport$.$anonfun$kamonService$8(KamonSupport.scala:52)

Seems due to https://github.com/http4s/http4s/commit/8074594952b4e5cdef592540883215a1a12c799c

This is a binary compatibility break

**Comment by rossabaker** [comment]
You're correct.  We reasoned it was okay because it was `private[http4s]`, but usages can still leak out into our other repos like rho and jdk-http-client.  What we need to do is reinstate the old ones as deprecated and forward to the companion on `Uri`.  If someone can send a PR to series/0.20 with this, that would be great.  Otherwise, I'll get to it ASAP, and we'll cut another 0.20.x release.

**Comment by hamnis** [comment]
Fixed in `0.20.13`
