### ISSUE TITLE
When auth routes not found the route returns error 500 0.21.0-M5

### ISSUE THREAD

**Issue by robkler** [http4s/http4s#2974]
Router("/test" -> middleware(myRoute))

When I use middleware, any request that use your route, in this case "/test", will be authenticated, but when the route doesn't exist api return error 500:

```scala
scala.MatchError: AuthedRequest(_ ),Request(method=GET, uri=/test/adfafd, headers=Headers(X-Consumer-Groups: bank, X-Consumer-Username: 1, User-Agent: PostmanRuntime/7.19.0, Accept: */*, Cache-Control: no-cache, Postman-Token: f8e0c066-975c-46a6-9145-1a85a46242b1, Host: localhost:8080, Accept-Encoding: gzip, deflate, Connection: keep-alive))) (of class org.http4s.AuthedRequest)
	at service.AddressingService$.$anonfun$service$1(AddressingService.scala:17)
	at org.http4s.AuthedRoutes$.$anonfun$apply$2(AuthedRoutes.scala:21)
	at cats.effect.internals.IORunLoop$.liftedTree1$1(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:95)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bfdes** [comment]
I think you need to [call](https://github.com/http4s/http4s/blob/e9e0db4eccb70fb986f9856b06e4ceb3df39d752/core/src/main/scala/org/http4s/syntax/KleisliSyntax.scala#L31) `orNotFound` on the service block, otherwise you will get a regular `MatchError` / 500.
