### ISSUE TITLE
UnresolvedAddressException: null

### ISSUE THREAD

**Issue by tomasherman** [http4s/http4s#3066]
Hi,

we are getting this really unhelpful exception when trying to connect to address that does not exist:

```
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:130)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:305)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:210)
	at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:62)
	at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:63)
	at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:56)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback$WithLocals.syncOnSuccess(TaskRestartCallback.scala:176)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
	at monix.eval.internal.TaskCreate$CallbackForCreate.run(TaskCreate.scala:252)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:132)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.TracingScheduler$Base.execute(TracingScheduler.scala:53)
	at monix.execution.schedulers.StartAsyncBatchRunnable.run(StartAsyncBatchRunnable.scala:42)
	at monix.execution.schedulers.TracingRunnable.run(TracingRunnable.scala:33)
	at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
	at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

is there any way to improve it? Are we doing something wrong?

Thanks!

**Comment by manuelcueto** [comment]
Following the stacktrace suggests that the error handling for that exception does not happen inside http4s, but instead on blaze so i guess this issue would fit better in that repo

**Comment by tomasherman** [comment]
ok, i thought those were related

**Comment by rossabaker** [comment]
They're related, but the relevant code is in the other repo.  Conversation continued at https://github.com/http4s/blaze/issues/373.
