### ISSUE TITLE
Logger throws java.lang.NullPointerException

### ISSUE THREAD

**Issue by DenisNovac** [http4s/http4s#3116]
Hi everyone. I am getting this error:

```
java.lang.NullPointerException
	at cats.effect.internals.IOForkedStart$.apply(IOForkedStart.scala:46)
	at cats.effect.internals.IOStart$.$anonfun$apply$1(IOStart.scala:35)
	at cats.effect.internals.IOStart$.$anonfun$apply$1$adapted(IOStart.scala:28)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at cats.effect.Async$$anon$1.run(Async.scala:276)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Dependencies:

```
scalaVersion := "2.12.10"

val circeVersion = "0.12.3"

libraryDependencies ++= Seq(
  "io.circe" %% "circe-core",
  "io.circe" %% "circe-generic",
  "io.circe" %% "circe-parser"
).map(_ % circeVersion)

val http4sVersion = "0.20.16"
libraryDependencies ++= Seq(
  "org.http4s" %% "http4s-dsl" % http4sVersion,
  "org.http4s" %% "http4s-blaze-server" % http4sVersion,
  "org.http4s" %% "http4s-server" % http4sVersion,
  "org.http4s" %% "http4s-blaze-client" % http4sVersion,
  "org.http4s" %% "http4s-circe" % http4sVersion
)
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.30"
libraryDependencies += "org.slf4j" % "slf4j-api" % "1.7.30"

libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % Test


testOptions in Test += Tests.Argument(TestFrameworks.JUnit, "-a", "-v", "-s")
scalacOptions ++= Seq("-Ypartial-unification")
```

Code:

```
import cats.effect._
import cats.implicits._
import org.http4s.server.Router
import org.http4s.server.blaze.BlazeServerBuilder
import org.http4s.implicits._
import org.http4s.server.middleware.Logger

import scala.concurrent.ExecutionContext.Implicits.global


object MyApp extends IOApp{
  val port = 9000
  val host = "localhost"

  val calls = indexCall <+> addContact 

  val api = Router("/" -> calls).orNotFound
  val corsWrappedApi = CorsApiWrapper(api)
  val loggedApi = Logger.httpApp(true, true)(corsWrappedApi)


  implicit val cs: ContextShift[IO] = IO.contextShift(global)
  override def run(args: List[String]): IO[ExitCode] =
    BlazeServerBuilder[IO]
      .bindHttp(port, host)
      .withHttpApp(loggedApi)
      .serve
      .compile
      .drain
      .as(ExitCode.Success)
}
```
It happens on every body with JSON input to server. When i use swagger - it happens even if i just send GET without body at all.

When i use RequestLogger - GET without body works fine, but POST with body throws this:

```
java.lang.NullPointerException
	at cats.effect.internals.IOForkedStart$.apply(IOForkedStart.scala:46)
	at cats.effect.internals.IOStart$.$anonfun$apply$1(IOStart.scala:35)
	at cats.effect.internals.IOStart$.$anonfun$apply$1$adapted(IOStart.scala:28)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$.$anonfun$guaranteeCase$1(IOBracket.scala:100)
	at cats.effect.internals.IOBracket$.$anonfun$guaranteeCase$1$adapted(IOBracket.scala:98)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:341)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:119)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:355)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:376)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:316)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)


```

**Comment by rossabaker** [comment]
It doesn't happen without the Logger?  The stack trace doesn't include http4s, but it's plausible we're passing a null off to cats-effect.

**Comment by rossabaker** [comment]
It's referencing an uninitalized `ContextShift`.  Does it work if you convert `api`, `corsWrappedApi`, and `loggedApi` to defs or lazy vals?

I can't remember which scala flag turns the appropriate warning on, but I compile all my projects with [sbt-tpolecat](https://github.com/DavidGregory084/sbt-tpolecat).

**Comment by DenisNovac** [comment]
@rossabaker Lazy vals or defs actually works. Thank you!

Looks like this `implicit val cs: ContextShift[IO] = IO.contextShift(global)` used in api composition. I placed it at the top and logging start working without lazy vals. It's strange since i was able to start this code without cs at all before the first use of `StaticFile`. I will read warnings more carefully in future.

![image](https://user-images.githubusercontent.com/22966999/73126867-d60f4700-3fd9-11ea-9015-f1e9d90c977e.png)
