### ISSUE TITLE
examples-blaze fails under Java 7

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#313]
```shell
sbt -java-home /usr/lib/jvm/java-7-oracle 'examples-blaze/runMain com.example.http4s.blaze.ClientExample'
```
leads to

```
[error] Caused by: java.lang.UnsupportedClassVersionError: sun/security/ssl/ClientHandshaker : Unsupported major.minor version 52.0
[error] 	at sun.security.ssl.SSLEngineImpl.initHandshaker(SSLEngineImpl.java:472)
[error] 	at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:668)
[error] 	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1213)
[error] 	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1169)
[error] 	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
[error] 	at org.http4s.blaze.pipeline.stages.SSLStage.goWrite$1(SSLStage.scala:302)
[error] 	at org.http4s.blaze.pipeline.stages.SSLStage.writeLoop(SSLStage.scala:328)
[error] 	at org.http4s.blaze.pipeline.stages.SSLStage.syncWrite(SSLStage.scala:237)
[error] 	... 35 more
```

This is related to the apn_boot library requiring Java 8.  I'm fine stating that HTTP2 support requires Java 8, and hacking around this in the build.

I'd say it's time to revisit #158, but the fact that another user found it suggests to me that we'd still be leaving people behind.

CC: @jonoabroad

**Comment by rossabaker** [comment]
Fixed by #318.
