### ISSUE TITLE
AsyncHttpClient returns empty body on slow stream

### ISSUE THREAD

**Issue by denisovlev** [http4s/http4s#3509]
When I request a slow stream with AsyncHttpClient I get an empty body. The request times out but it does not throw an error. In the test below there are two cases: one checks that exception is thrown, another that we get the full result. Neither of the tests succeed.

There are two questions: 
1. How increase the timeout? Neither `setRequestTimeout` nor `setReadTimeout` seem to work
2. How to make sure it does not fail silently in case of timeout?

```scala
import java.util.Calendar

import cats.effect._
import cats.implicits._
import org.http4s.{HttpRoutes, Method, Request, Status, Uri}
import org.http4s.syntax._
import org.http4s.dsl.io._
import org.http4s.implicits._
import org.http4s.server.blaze._
import fs2.Stream
import fs2.text.utf8DecodeC
import org.http4s.client.Client
import org.http4s.client.asynchttpclient.AsyncHttpClient
import org.http4s.server.Server

import scala.concurrent.duration._
import org.scalatest.FunSuite

import scala.concurrent.ExecutionContext

class ExampleSuite extends FunSuite {

  val singleThreadExecutor = ExecutionContext.fromExecutor((task: Runnable) => task.run())
  implicit val contextShift = IO.contextShift(singleThreadExecutor)
  implicit val timer = IO.timer(singleThreadExecutor)

  val host = "localhost"
  val port = 4002
  val uri = Uri.unsafeFromString(s"http://$host:$port/test")

  val hang = Stream.awakeEvery[IO](120.seconds).take(5)

  val hangService = HttpRoutes.of[IO] {
    case GET -> Root / "test" => Ok(hang.map(_.toString))
    case POST -> Root / "test" => Ok(hang.map(_.toString))
  }.orNotFound

  def runServer(f: (Server[IO]) => IO[List[String]]): IO[List[String]] = {
    BlazeServerBuilder[IO]
      .bindHttp(port, host)
      .withHttpApp(hangService)
      .resource.use(f)
  }

  def runClient(f: (Client[IO]) => IO[List[String]]): IO[List[String]] = {
    AsyncHttpClient.resource[IO]().use(f)
  }

  def runRequest(client: Client[IO]): IO[List[String]] = {
    client.stream(Request[IO](Method.GET, uri)).flatMap { response =>
      Console.println(Calendar.getInstance().getTime, response)
      response.status match {
        case Status.Ok => response.body.chunks.through(utf8DecodeC)
        case _ => Stream.raiseError[IO](new Exception(response.status.reason))
      }
    }.compile.toList
  }

  test("should timeout") {
    val result = runServer { _ =>
      runClient { client =>
        runRequest(client)
      }
    }

    assertThrows[Exception] {
      result.unsafeRunSync()
    }
    // Expected exception java.lang.Exception to be thrown, but no exception was thrown
  }

  test("should succeed") {
    val result = runServer { _ =>
      runClient { client =>
        runRequest(client)
      }
    }

    assert(result.unsafeRunSync().size == 5)
    // List() had size 0 instead of expected size 5
  }

}

```

```scala
// build.sbt

name := "http4s-test"

version := "0.1"

scalaVersion := "2.12.6"

//val http4sVersion = "0.20.1"
val http4sVersion = "0.21.4"

libraryDependencies ++= Seq(
  "org.http4s" %% "http4s-dsl" % http4sVersion,
  "org.http4s" %% "http4s-blaze-server" % http4sVersion,
  "org.http4s" %% "http4s-blaze-client" % http4sVersion,
  "org.http4s" %% "http4s-async-http-client" % http4sVersion,
  "org.scalatest" % "scalatest_2.12" % "3.1.2" % "test"
)

scalacOptions ++= Seq("-Ypartial-unification")
```

**Comment by rossabaker** [comment]
It's late here, so I'll need to take a closer look tomorrow, but I appreciate the detailed repro.  That will make it much easier to get to the bottom of.

To be clear, you tried to set those timeout options in the `runClient` call?

**Comment by denisovlev** [comment]
So I did some more testing

**Server timeout**
I saw in the BlazeServer logs that it closes connection after 60 seconds.
```
11:20:45.804 [scala-execution-context-global-32] DEBUG org.http4s.blazecore.IdleTimeoutStage - Idle timeout after 60000 ms.
11:20:45.805 [scala-execution-context-global-32] DEBUG org.http4s.server.blaze.Http1ServerStage$$anon$1 - Shutting down due to idle timeout
```

Not sure if it is correct behavior for the server to close connection while streaming result. Anyway, I used this server just for testing so I fixed it by setting servers idle timeout to infinity.

```scala
def runServer(f: (Server[IO]) => IO[List[String]]): IO[List[String]] = {
    BlazeServerBuilder[IO]
      .withIdleTimeout(Duration.Inf)
      .bindHttp(port, host)
      .withHttpApp(hangService)
      .resource.use(f)
  }
```

**Client timeout**
This however did not fix the problem. I see timeout exception logged now and then it is swallowed somewhere apparently. Request still does not fail and returns result, this time one item.

```
java.util.concurrent.TimeoutException: Read timeout to localhost/127.0.0.1:4002 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.ReadTimeoutTimerTask.run(ReadTimeoutTimerTask.java:56)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at java.lang.Thread.run(Thread.java:748)
```

```
List("120014630836 nanoseconds") had size 1 instead of expected size 5
```

So I increased the read timeout now for the client.

  ```scala
def runClient(f: (Client[IO]) => IO[List[String]]): IO[List[String]] = {
    val defaultConfig = AsyncHttpClient.defaultConfig
    val config = new DefaultAsyncHttpClientConfig.Builder()
      .setMaxConnectionsPerHost(defaultConfig.getMaxConnectionsPerHost)
      .setMaxConnections(defaultConfig.getMaxConnections)
      .setRequestTimeout(Integer.MAX_VALUE)
      .setReadTimeout(240*1000) // 4 minutes
      .setThreadFactory(defaultConfig.getThreadFactory)
      .setCookieStore(defaultConfig.getCookieStore)
      .build()
    AsyncHttpClient.resource[IO](config).use(f)
  }
```

This time it actually succeeded, so increasing read timeout actually seems to work.

**Conclusion**
There is still a problem that when read timeout happens the exception is swallowed and result is returned.
There is a workaround: to set read timeout high enough so that it is not reached. Still, if it is reached, the client will silently return the incomplete result.

**Comment by rossabaker** [comment]
The `cb` is already completed with a response.  For streaming purposes, the response headers are available before the timeout happens, so I think the best we can do is to raise an error in the Stream body.

The reason it's not is because the error is going to `onThrowable` instead of being raised by the `Publisher`.  We need some way of getting an error into that `body` we create in `onStream`.
