### ISSUE TITLE
async-http-client: java.lang.IllegalStateException: This publisher only supports one subscriber

### ISSUE THREAD

**Issue by zkay** [http4s/http4s#3527]
👋 Hi there. We're seeing an issue when using the `async-http-client` module:

```
java.lang.IllegalStateException: This publisher only supports one subscriber
	at com.typesafe.netty.HandlerPublisher.subscribe(HandlerPublisher.java:167)
	at org.http4s.client.asynchttpclient.AsyncHttpClient$$anon$1.$anonfun$onStream$3(AsyncHttpClient.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:377)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:70)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:50)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:43)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:352)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:124)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I tried searching for this message and only found it mentioned in passing in a previous issue: https://github.com/http4s/http4s/issues/3354#issuecomment-620032795

In our application code this client is being introduced via `iClient                    <- AsyncHttpClient.stream[F]()` and used in other services that require a `Client[F]`.

This was occurring on `0.21.4`. We ended up dropping our usage of the module and switching back to `BlazeClientBuilder`, which fixed the issue.

**Comment by henricook** [comment]
We're also running on 0.21.1 until this is fixed. We have a similar structure to you zkay

**Comment by henricook** [comment]
I've updated my testing of this.

I have one AsyncHttpClient on 0.21.6. The client is shared across 50 or so test suites, running in parallel in a 2 thread thread-pool (so two at a time).

Fascinatingly on my local machine (Ubuntu 20.04, sbt 1.3.13. scala 2.13.1, non-dockerised) that runs fine, in fact it ends up using 10 threads or so in the pool because I have more cores locally. Even when I restrict the pool to two threads though, runs fine.

In my CI, based on the dockerised `openjdk:8-jdk` image with minimal alterations, many tests succeed but on average around 35 tests (in a 400 test suite) fail with the stack trace below. I can't imagine what else is different about the environments apart from that base OS.

```
java.lang.Error: received subscription in invalid state [UpstreamCompletion]
219 	at fs2.interop.reactivestreams.StreamSubscriber$.$anonfun$fsm$1(StreamSubscriber.scala:114)
220 	at cats.effect.concurrent.Ref$SyncRef.spin$1(Ref.scala:271)
221 	at cats.effect.concurrent.Ref$SyncRef.$anonfun$modify$1(Ref.scala:275)
222 	at monix.eval.internal.TaskRunLoop$.startLight(TaskRunLoop.scala:271)
223 	at monix.eval.Task.$anonfun$runAsyncOptF$1(Task.scala:812)
224 	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.bindContext(CanBindLocals.scala:115)
225 	at monix.execution.misc.CanBindLocals.isolate(CanBindLocals.scala:54)
226 	at monix.execution.misc.CanBindLocals.isolate$(CanBindLocals.scala:53)
227 	at monix.execution.misc.CanIsolateInstancesLevel0$SynchronousInstance$.isolate(CanBindLocals.scala:111)
228 	at monix.execution.misc.Local$.isolate(Local.scala:86)
229 	at monix.eval.Task.runAsyncOptF(Task.scala:811)
230 	at monix.eval.internal.TaskEffect$.execute(TaskEffect.scala:57)
231 	at monix.eval.internal.TaskEffect$.$anonfun$runAsync$1(TaskEffect.scala:40)
232 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
233 	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:193)
234 	at cats.effect.IO.unsafeRunTimed(IO.scala:327)
235 	at cats.effect.IO.unsafeRunSync(IO.scala:246)
236 	at cats.effect.SyncIO.unsafeRunSync(SyncIO.scala:51)
237 	at fs2.interop.reactivestreams.package$Runner.unsafeRunAsync(package.scala:68)
238 	at fs2.interop.reactivestreams.StreamSubscriber.onSubscribe(StreamSubscriber.scala:24)
239 	at com.typesafe.netty.HandlerPublisher.subscribe(HandlerPublisher.java:159)
240 	at org.http4s.client.asynchttpclient.AsyncHttpClient$$anon$1.$anonfun$onStream$3(AsyncHttpClient.scala:96)
241 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
242 	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
243 	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
244 	at monix.eval.internal.TaskRestartCallback$WithLocals.syncOnSuccess(TaskRestartCallback.scala:176)
245 	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:118)
246 	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
247 	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
248 	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.super$startLoop(TrampolineExecutionContext.scala:142)
249 	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.$anonfun$startLoop$1(TrampolineExecutionContext.scala:142)
250 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
251 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
252 	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.startLoop(TrampolineExecutionContext.scala:142)
253 	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
254 	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)
255 	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
256 	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
257 	at monix.execution.schedulers.TracingScheduler$Base.execute(TracingScheduler.scala:53)
258 	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:56)
259 	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:592)
260 	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:120)
261 	at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222)
262 	at monix.execution.schedulers.TracingRunnable.run(TracingRunnable.scala:33)
263 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
264 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
265 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
266 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
267 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
```

**Comment by harpresing** [comment]
Hi there,

I've created a repository with a test suite that replicates this issue: https://github.com/harpresing/async-http-client-error.

If someone accidentally does `response.bodyText.compile.foldMonoid map { ... }` on the same `Response[IO]` object twice, we see this error when using the AsyncHttpClient. It doesn't happen with the Blaze Client.

**Comment by rossabaker** [comment]
Thanks for the repro, @harpresing!

Compiling the body twice is undefined behavior: we can't memoize the body for a second read and still do proper streaming.  It might work erratically, or differently on different backends.

The question is then, could the original app be consuming the body twice, thus showing the same symptom that Harpreet reproduced?
