### ISSUE TITLE
Improve or remove failed request logging in JettyClient

### ISSUE THREAD

**Issue by nigredo-tori** [http4s/http4s#3817]
Here's an example of a log message I get when using the Jetty Client:
```scala
2020-11-09 18:13:38 [ent@66301ca5-36] ERROR o.h.c.j.ResponseListener - Failed request
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:313)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:62)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:639)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:501)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
This is surprisingly unhelpful - it contains no information about which request has failed, and where in my application that happened. The message should at least contain the URL in question - this information is available whan creating a `ResponseListener`.

Also, I don't think exceptions here should be logged in the first place, at least not with the `ERROR` level. They are propagated to the calling code, which *should* log them as it sees fit. The calling code is also an objectively better place to log these, since it sees them **after** `IO` augments them with tracing data.

**Comment by ashwinbhaskar** [comment]
I would vote for removing the failed request logging. I am not sure how to improve the logging in this case

**Comment by rossabaker** [comment]
I agree with propagating the failure.  I guess the question is whether to enhance the `ConnectException` with more information, or assume that request info is present close enough to where the failure occurred that we can just propagate this message.

**Comment by nigredo-tori** [comment]
I don't think enhancing the exception would be worth it. The `Request` value has to be near where the `Client` is used, so it should be easy for the calling code to get the necessary information from there. And augmenting the exception with extra data by wrapping it in another one can break error handling logic in the calling code. So I think we should just delete this logging statement and call it a day.
