### ISSUE TITLE
UrlFormLifter does not work with Jetty

### ISSUE THREAD

**Issue by Pyppe** [http4s/http4s#386]
Using `UrlFormLifter` with `JettyBuilder` does not work. All requests throw exception at runtime.

For example, the following:
```scala
val service = UrlFormLifter(HttpService {
  case req => Ok(req.multiParams.asJson)
})
```
throws `java.lang.NegativeArraySizeException` at runtime:
```
java.lang.NegativeArraySizeException: null
	at scodec.bits.ByteVector$class.toArray(ByteVector.scala:544) ~[scodec-bits_2.11-1.0.9.jar:na]
	at scodec.bits.ByteVector$Chunk.toArray(ByteVector.scala:1208) ~[scodec-bits_2.11-1.0.9.jar:na]
	at scalaz.stream.text$$anonfun$2.apply(text.scala:58) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.text$$anonfun$2.apply(text.scala:58) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:53) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$map$1.apply(Process.scala:53) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Emit.flatMap(Process.scala:577) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Append.extend(Process.scala:628) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Append.flatMap(Process.scala:617) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$3.apply(Process.scala:47) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$3.apply(Process.scala:47) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.stream.process1$Await1$$anonfun$unapply$1$$anonfun$apply$37.apply(process1.scala:818) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.process1$Await1$$anonfun$unapply$1$$anonfun$apply$37.apply(process1.scala:818) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.process1$Await1$$anonfun$unapply$1.apply(process1.scala:818) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.process1$Await1$$anonfun$unapply$1.apply(process1.scala:818) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.process1$.go$6(process1.scala:197) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.process1$.feed(process1.scala:202) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:145) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:139) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Emit.flatMap(Process.scala:577) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:617) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:143) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:139) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Emit.flatMap(Process.scala:577) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:617) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:143) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$pipe$1.apply(Process.scala:139) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$1.apply(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.flatMap(Process.scala:46) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Emit.flatMap(Process.scala:577) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$flatMap$4.apply(Process.scala:48) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$go$1$1.apply(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Util$.Try(Util.scala:38) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.go$1(Process.scala:84) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.step(Process.scala:97) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$Append.step(Process.scala:617) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$class.go$3(Process.scala:470) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:479) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.stream.Process$$anonfun$go$3$3.apply(Process.scala:478) ~[scalaz-stream_2.11-0.7.3a.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Task$.Try(Task.scala:386) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58) ~[scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future.step(Future.scala:110) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future.listen(Future.scala:75) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:113) [http4s-servlet_2.11-0.9.0.jar:0.9.0]
	at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:108) [http4s-servlet_2.11-0.9.0.jar:0.9.0]
	at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future.listen(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:113) [http4s-servlet_2.11-0.9.0.jar:0.9.0]
	at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:108) [http4s-servlet_2.11-0.9.0.jar:0.9.0]
	at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future.listen(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.resume(Free.scala:73) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go2$1(Free.scala:118) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.go(Free.scala:122) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.Free.run(Free.scala:172) [scalaz-core_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380) [scalaz-concurrent_2.11-7.1.3.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

However, the same code works if `BlazeBuilder` is used.

**Comment by Pyppe** [comment]
Also, as the stack-trace suggests, the culprit is `NonBlockingServletIo`. Using Jetty with `BlockingServletIo` seems to work OK.

**Comment by bryce-anderson** [comment]
I'm not 100% sure, but I bet the problem is [here](https://github.com/http4s/http4s/blob/master/servlet/src/main/scala/org/http4s/servlet/ServletIo.scala#L78) where we could be getting a `-1` from the read operation. I don't have time to properly patch it atm but will take a closer look later unless someone gets to it first.
