### ISSUE TITLE
Docs build is timing out on main

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3933]
First observed after merge of #3903. We don't get any logs -- build just times out after six hours.

**Comment by rossabaker** [comment]
```
error: /home/ross/src/http4s/docs/src/main/mdoc/client.md:333:1: null
httpClient.expect[AuthResponse](postRequest)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
java.lang.NullPointerException
	at org.http4s.client.DefaultClient.expectOr(DefaultClient.scala:80)
	at org.http4s.client.DefaultClient.expect(DefaultClient.scala:98)
	at repl.MdocSession$App.<init>(client.md:290)
	at repl.MdocSession$.app(client.md:3)
```

Oops:

```scala
// See the JSON page for details on how to define this
implicit val authResponseEntityDecoder: EntityDecoder[IO, AuthResponse] = null
```
