### ISSUE TITLE
Timeout exception in the ember parser when using fs2 >= `2.4.0`

### ISSUE THREAD

**Issue by BalmungSan** [http4s/http4s#4458]
I was not sure if I should report this here or in the **fs2** repo, but I guess it made more sense to report it here first and move it to **fs2** if we can take **ember** out of the equation.

The error is very simple, if using an **ember** server _(with `tls`)_ and the **fs2** jar in the classpath is the version `2.4.0` _(or superior)_ then calling the endpoints will fail with the underlying error:

> java.util.concurrent.TimeoutException: 5 seconds
	at timeout @ org.http4s.ember.core.Parser$Request$.$anonfun$parser$8(Parser.scala:394)
	at flatMap @ org.http4s.ember.core.Parser$Request$.parser(Parser.scala:363)
	at flatMap @ org.http4s.ember.server.internal.ServerHelpers$.runApp(ServerHelpers.scala:132)
	at map @ org.http4s.ember.server.internal.ServerHelpers$.$anonfun$runConnection$2(ServerHelpers.scala:198)

### MCVE

```scala
// scala 2.13.4

import $ivy.`org.typelevel::cats-effect:2.3.1`
import $ivy.`co.fs2::fs2-io:2.5.0` // Replace with 2.3.0 to fix the problem.
import $ivy.`org.http4s::http4s-ember-server:0.21.19`
import $ivy.`org.http4s::http4s-dsl:0.21.19`

import cats.effect.{Blocker, IO}
import fs2.Stream
import fs2.io.tls.TLSContext
import org.http4s.ember.server.EmberServerBuilder

import java.nio.file.Paths

object Main {
  implicit val cs = IO.contextShift(scala.concurrent.ExecutionContext.global)
  implicit val timer = IO.timer(scala.concurrent.ExecutionContext.global)

  val app = {
    import org.http4s.dsl.io._
    import org.http4s.HttpRoutes
    import org.http4s.server.Router
    import org.http4s.syntax.kleisli._ // Provides the orNotFound method.

    val test = HttpRoutes.of[IO] {
      case GET -> Root / "test" => Ok("OK")
    }

    Router(
      "/" -> test
    ).orNotFound
  }

  val keystorePassword = "password".toCharArray

  def tlsContextR(blocker: Blocker) =
    TLSContext.fromKeyStoreFile[IO](
      file = Paths.get("./keystore.jks"),
      keyPassword = keystorePassword,
      storePassword = keystorePassword,
      blocker = blocker
    )

  def serverR(blocker: Blocker, tlsContext: TLSContext) =
    EmberServerBuilder
      .default[IO]
      .withHost("0.0.0.0")
      .withPort(8080)
      .withHttpApp(app)
      .withTLS(tlsContext)
      .withBlocker(blocker)
      .withErrorHandler {
        case e =>
          IO(e.printStackTrace()).as(org.http4s.Response.timeout[IO])
      }.build

  val program =
    for {
      blocker <- Stream.resource(Blocker[IO])
      tlsContext <- Stream.eval(tlsContextR(blocker))
      server <- Stream.resource(serverR(blocker, tlsContext))
      _ <- Stream.eval(IO(println(s"Server has started at ${server.address}")))
      _ <- Stream.never[IO] >> Stream.emit(())
    } yield ()

  def run(): Unit = {
    program.compile.drain.unsafeRunSync()
  }
}

@main
def main(): Unit = {
  Main.run()
}
```

To generate the `keystore.jks` file run the following command:

```bash
keytool -genkey -keyalg RSA -alias selfsigned -keystore keystore.jks -storepass password -validity 360 -keysize 2048
```

----

There is something really weird about this and it is that when using the original code that produced the error it was only reproducible by querying the endpoint using **Postman** or **Axios** _(a **NodeJS** http client, which was actually the one that identified the problem)_ but it worked if using **curl**, **chrome** or **vertx-web-client**.
But, using this minimal snippet even using **curl** I can reproduce the problem.

**Comment by mpilquist** [comment]
Can you paste the result of a failed curl with the `-v` parameter? This example works fine for me on latest OS X release with built-in curl and running on `openjdk version "11.0.9" 2020-10-20`. I suspect this is related to cipher suite selection or TLS version.

**Comment by mpilquist** [comment]
Also works fine on `openjdk version "1.8.0_272"` and when forcing TLS 1.0, 1.1, and 1.2.

**Comment by mpilquist** [comment]
I can reproduce by using Safari -- I still get the 200 OK but also get the exception logged. One notable difference is Safari is using TLS 1.3 whereas my version of curl doesn't have support for 1.3.

**Comment by BalmungSan** [comment]
Hi @mpilquist thanks for looking into this!

If I use **fs2** `2.5.0` and remove the `withErrorHanlder` I got this output using **curl**.
It seems you are right about the `tls` version.

```
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=test; ST=test; L=test; O=test; OU=test; CN=Luis-Miguel Mej�a-Su�rez
*  start date: Feb 17 23:30:09 2021 GMT
*  expire date: Feb 12 23:30:09 2022 GMT
*  issuer: C=test; ST=test; L=test; O=test; OU=test; CN=Luis-Miguel Mej�a-Su�rez
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

This is the output if I use **fs2** `2.3.0`

```
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=test; ST=test; L=test; O=test; OU=test; CN=Luis-Miguel Mej�a-Su�rez
*  start date: Feb 17 23:30:09 2021 GMT
*  expire date: Feb 12 23:30:09 2022 GMT
*  issuer: C=test; ST=test; L=test; O=test; OU=test; CN=Luis-Miguel Mej�a-Su�rez
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 18 Feb 2021 14:26:43 GMT
< Connection: keep-alive
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 2
< 
* Connection #0 to host localhost left intact
OK
```

Also, note that I am running using:

> openjdk version "11.0.9" 2020-10-20
> OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
> OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

But the original code was also tested using **AdoptOpenjdk** `8`.

**Comment by mpilquist** [comment]
Hm, so this seems like a bug in ember server then -- maybe something in `withErrorHandler` that doesn't properly cleanup the outstanding parser/request handler?

**Comment by BalmungSan** [comment]
@mpilquist no no, I removed the `withErrorHandler` to get the original `500` exit code instead of the `timeout` I configured.
With or without the error handler the error is reproduced if I use **fs2** >= `2.4.0` and fixed if I use `2.3.0`

**Comment by BalmungSan** [comment]
@mpilquist let's make this even weirder. I just tried again with **curl**, without changing anything and it started to work! 😕
However, it still fails when called from **postman**.

Also, right now if I use the flags `--tlsv1.3 --tls-max 1.3` with **curl** it always fails, but if I use `--tlsv1.2 --tls-max 1.2` then it always works.
_(The even weirder thing is that if I do not specify the flags, according to the debug output it used `tls` version `1.3`, but somehow it works)_

**Comment by mpilquist** [comment]
Well at least we've narrowed it down to TLS1.3. Could you try an fs2-io only reproduction which binds a TLS port? This example server+client test might help get started: https://github.com/typelevel/fs2/blob/main/io/src/test/scala/fs2/io/net/tls/TLSSocketSuite.scala#L111-L138

**Comment by BalmungSan** [comment]
@mpilquist I tried to reproduce it using only **fs2** but I was not lucky.
Here is the code, maybe I am missing something stupid.

```scala
// scala 2.13.4

import $ivy.`org.typelevel::cats-effect:2.3.1`
import $ivy.`co.fs2::fs2-io:2.5.0`

import cats.effect.{Blocker, IO, Resource}
import fs2.Stream
import fs2.io.tcp.{Socket, SocketGroup}
import fs2.io.tls.TLSContext

import java.net.InetSocketAddress
import java.nio.file.Paths

object Main {
  implicit val cs = IO.contextShift(scala.concurrent.ExecutionContext.global)
  implicit val timer = IO.timer(scala.concurrent.ExecutionContext.global)

  val keystorePassword = "password".toCharArray

  def tlsContextR(blocker: Blocker) =
    TLSContext.fromKeyStoreFile[IO](
      file = Paths.get("./keystore.jks"),
      keyPassword = keystorePassword,
      storePassword = keystorePassword,
      blocker = blocker
    )

  def createSslSocket(client: Resource[IO, Socket[IO]], tlsContext: TLSContext) = {
    val sslSocketR =
      for {
        socket <- client
        sslSocket <- tlsContext.server[IO](
          socket,
          logger = Some(msg => IO(println(s"Log: ${msg}")))
        )
      } yield sslSocket

    Stream.resource(sslSocketR)
  }

  val responseData =
    """HTTP/1.1 200 OK
      |Connection: close
      |Content-Type: text/plain; charset=UTF-8
      |Content-Length: 2
      |
      |OK""".stripMargin

  val response = Stream.emit(responseData).through(fs2.text.utf8Encode[IO])

  val program =
    for {
      blocker <- Stream.resource(Blocker[IO])
      tlsContext <- Stream.eval(tlsContextR(blocker))
      sg <- Stream.resource(SocketGroup[IO](blocker))
      serverAddress <- Stream.eval(IO(new InetSocketAddress("0.0.0.0", 8080)))
      serverAndAddress <- Stream.resource(sg.serverResource[IO](serverAddress))
      (address, server) = serverAndAddress
      _ <- Stream.eval(IO(println(s"Server has started at ${address}")))
      client <- server
      sslSocket <- createSslSocket(client, tlsContext)
      _ <- response.through(sslSocket.writes())
    } yield ()

  def run(): Unit = {
    program.compile.drain.unsafeRunSync()
  }
}

@main
def main(): Unit = {
  Main.run()
}
````

**Comment by mpilquist** [comment]
Very strange -- when I run the original ember server example with Postman, it always fails if TLSv1.2 is enabled but passes if I disable 1.2 in Postman settings. With the fs2-only example, it always works in Postman.

Another thing I noticed with ember example and Postman -- Postman reports that the request timed out after a few seconds but the server logs a connection error immediately:

```scala
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:395)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at async @ fs2.io.package$.asyncYield(io.scala:245)
	at guarantee @ fs2.io.package$.asyncYield(io.scala:245)
	at flatMap @ fs2.io.tcp.SocketGroup.$anonfun$apply$8(SocketGroup.scala:291)
	at void @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$3(StreamForking.scala:86)
	at flatTap @ fs2.io.tls.TLSEngine$$anon$1.wrap(TLSEngine.scala:94)
	at flatMap @ fs2.io.tcp.SocketGroup.getBufferOf$1(SocketGroup.scala:260)
	at flatMap @ fs2.io.tcp.SocketGroup.fs2$io$tcp$SocketGroup$$read0$1(SocketGroup.scala:290)
	at apply @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$1(StreamForking.scala:44)
	at unsafeRunSync @ Main$.run(Main.scala:62)
	at acquire @ org.http4s.ember.server.internal.StreamForking$.runInner$1(StreamForking.scala:78)
	at apply @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$1(StreamForking.scala:44)
	at withPermit @ fs2.io.tls.TLSEngine$$anon$1.read(TLSEngine.scala:124)
	at flatMap @ fs2.io.tls.TLSEngine$$anon$1.read1(TLSEngine.scala:139)
```

**Comment by mpilquist** [comment]
I added some logging and noticed that the client connection is closed before the TLSEngine has flushed all events out to the network:

```scala
[info] running Main
09:09:54.649 [scala-execution-context-global-112] INFO  Main - Ember-Server service bound to address: /0.0.0.0:8080
Server has started at /0.0.0.0:8080
09:10:08.243 [scala-execution-context-global-112] TRACE Main - wrap result: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 0
09:10:08.243 [scala-execution-context-global-124] TRACE Main - wrap result: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 0
09:10:08.256 [scala-execution-context-global-112] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_TASK
bytesConsumed = 517 bytesProduced = 0
09:10:08.284 [scala-execution-context-global-124] TRACE Main - wrap result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 7 sequenceNumber = 0
09:10:08.284 [scala-execution-context-global-112] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
09:10:08.287 [scala-execution-context-global-112] TRACE Main - wrapHandshake result: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 166 sequenceNumber = 0
09:10:08.291 [scala-execution-context-global-123] TRACE Main - wrapHandshake result: Status = CLOSED HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 7 sequenceNumber = 1
09:10:08.292 [scala-execution-context-global-123] TRACE Main - wrap result: Status = CLOSED HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0
09:10:08.293 [scala-execution-context-global-124] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 6 bytesProduced = 0
09:10:08.294 [scala-execution-context-global-124] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_TASK
bytesConsumed = 517 bytesProduced = 0
WITH ERROR HANDLER: java.io.IOException: Connection reset by peer
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:395)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at async @ fs2.io.package$.asyncYield(io.scala:245)
	at guarantee @ fs2.io.package$.asyncYield(io.scala:245)
	at flatMap @ fs2.io.tcp.SocketGroup.$anonfun$apply$8(SocketGroup.scala:291)
	at void @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$3(StreamForking.scala:86)
	at flatTap @ fs2.io.tls.TLSEngine$$anon$1.wrap(TLSEngine.scala:94)
	at flatMap @ fs2.io.tcp.SocketGroup.getBufferOf$1(SocketGroup.scala:260)
	at flatMap @ fs2.io.tcp.SocketGroup.fs2$io$tcp$SocketGroup$$read0$1(SocketGroup.scala:290)
	at apply @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$1(StreamForking.scala:44)
	at unsafeRunSync @ Main$.run(Main.scala:64)
	at acquire @ org.http4s.ember.server.internal.StreamForking$.runInner$1(StreamForking.scala:78)
	at apply @ org.http4s.ember.server.internal.StreamForking$.$anonfun$forking$1(StreamForking.scala:44)
	at withPermit @ fs2.io.tls.TLSEngine$$anon$1.read(TLSEngine.scala:124)
	at flatMap @ fs2.io.tls.TLSEngine$$anon$1.read1(TLSEngine.scala:139)
09:10:08.435 [scala-execution-context-global-123] TRACE Main - wrap result: Status = CLOSED HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0
09:10:08.480 [scala-execution-context-global-112] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
09:10:08.482 [scala-execution-context-global-112] TRACE Main - wrapHandshake result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 160 sequenceNumber = 1
09:10:08.483 [scala-execution-context-global-112] TRACE Main - wrapHandshake result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 6 sequenceNumber = 2
09:10:08.496 [scala-execution-context-global-112] TRACE Main - wrapHandshake result: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 1270 sequenceNumber = 0
09:10:08.508 [scala-execution-context-global-112] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 58 bytesProduced = 0
09:10:08.510 [scala-execution-context-global-112] TRACE Main - wrapHandshake result: Status = OK HandshakeStatus = FINISHED
bytesConsumed = 0 bytesProduced = 88 sequenceNumber = 0
09:10:08.513 [scala-execution-context-global-112] TRACE Main - unwrapHandshake result: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 228 bytesProduced = 206
09:10:08.514 [scala-execution-context-global-112] TRACE Main - wrap result: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0



WITH ERROR HANDLER: java.util.concurrent.TimeoutException: 5 seconds
java.util.concurrent.TimeoutException: 5 seconds
	at timeout @ org.http4s.ember.core.Parser$Request$.$anonfun$parser$8(Parser.scala:394)
	at flatMap @ org.http4s.ember.core.Parser$Request$.parser(Parser.scala:363)
	at flatMap @ org.http4s.ember.server.internal.ServerHelpers$.runApp(ServerHelpers.scala:132)
	at map @ org.http4s.ember.server.internal.ServerHelpers$.$anonfun$runConnection$2(ServerHelpers.scala:198)
09:10:13.239 [scala-execution-context-global-124] TRACE Main - wrap result: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 115 bytesProduced = 153 sequenceNumber = 1
```

I noticed this same pattern with working exchanges as well. I suspect the reason it works sometimes is based on the cipher suite selection and exactly what wrapped text gets sent to the socket before the early shutdown occurs. Different protocols & cipher suites will emit wrapped text at different points.

**Comment by BalmungSan** [comment]
> when I run the original ember server example with Postman, it always fails if TLSv1.2 is enabled but passes if I disable 1.2 in Postman settings.

So exactly the opposite of my **curl** behaviour? I will try to play with the **postman** SSL settings to see what happens.

> Postman reports that the request timed out after a few seconds but the server logs a connection error immediately.

Yeah, **ember** has a default of `5` seconds to timeout on the headers, the value is configurable but even with `15` seconds it didn't work for me.
I have never seen that server connection error :(

This is what worries me the most about this issue, that it seems to behave differently from time to time.

> I added some logging

Thanks for all the hard work looking into this!
Let me know if I can do anything to help.

**Comment by RaasAhsan** [comment]
Can you reproduce on <= 0.21.16 ?

**Comment by BalmungSan** [comment]
@RaasAhsan yes, while the problem is obviously in **ember** what seems to trigger this is the **fs2** version in the classpath. I have reproduced / fixed this problem with multiple versions of **http4s** as long as **fs2** `2.4,0` _(or superior)_ is in the classpath, the error occurs and as soon as I force it to use version `2.3.0` it is fixed.

**Comment by mpilquist** [comment]
@BalmungSan Can you try with fs2 2.5.3, which was just released?

**Comment by BalmungSan** [comment]
@mpilquist yeah, I am waiting for it to reach **maven central**.

**Comment by BalmungSan** [comment]
@mpilquist I just tested it, it works!

Using the reproducible snippet now I can query it using **postman** and it answers without problems, _(although the exception is still logged after a couple of seconds)_.
Then I upgraded the version in the original / real code and I can confirm the issue is fixed!

Now, should I close this since it is technically fixed, or should we wait until a new version of **http4s** that depends on at least that version is released?

**Comment by BalmungSan** [comment]
Closed by https://github.com/http4s/http4s/releases/tag/v0.21.20

**Comment by rossabaker** [comment]
I'm sorry.  I didn't realize we were sitting on a user-reported bugfix for this long. Please give me a kick here or on Gitter if you're ever waiting like this again for something that already works.  Releases aren't that hard.

**Comment by BalmungSan** [comment]
@rossabaker No worries, as I said it was very easy to fix this in userland by just manually upgrading the **fs2** version. But I was not sure if I should have closed this when it was fixed in **fs2** or wait until it was _"fixed"_ by **http4s** directly.
Thanks for all the hard work!
