### ISSUE TITLE
StackOverflowException in Http4sServlet errorHandler with POST

### ISSUE THREAD

**Issue by mkokkola** [http4s/http4s#459]
The following stack trace comes out from Http4s when handling POST requests (size ~20kB). Could not be repeated systematically, but happens with enough repetition:

```
2015-11-30 15:15:55.763 [qtp1952473604-37] DEBUG org.eclipse.jetty.server.HttpInput - 
java.lang.StackOverflowError: null
        at org.http4s.servlet.Http4sServlet.org$http4s$servlet$Http4sServlet$$errorHandler(Http4sServlet.scala:117) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.Http4sServlet$$anonfun$service$3.apply(Http4sServlet.scala:70) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.Http4sServlet$$anonfun$service$3.apply(Http4sServlet.scala:68) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$runAsync$1.apply(Future.scala:142) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$runAsync$1.apply(Future.scala:142) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future.listen(Future.scala:76) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.resume(Free.scala:73) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go2$1(Free.scala:118) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go(Free.scala:122) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.run(Free.scala:172) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:117) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:112) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future.listen(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.resume(Free.scala:73) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go2$1(Free.scala:118) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go(Free.scala:122) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.run(Free.scala:172) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:117) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:112) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future.listen(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:52) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.resume(Free.scala:73) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go2$1(Free.scala:118) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.go(Free.scala:122) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.Free.run(Free.scala:172) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
       ...etc...
      at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1$$anonfun$apply$14.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:117) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at org.http4s.servlet.NonBlockingServletIo$$anonfun$reader$3.apply(ServletIo.scala:112) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
        at scalaz.concurrent.Future$$anonfun$async$1.apply(Future.scala:376) ~[meta-assembly-0.1-SNAPSHOT.jar:0.1-SNAPSHOT]
```

**Comment by bryce-anderson** [comment]
@mkokkola, what version of http4s are you using?

**Comment by mkokkola** [comment]
0.11.1

**Comment by bryce-anderson** [comment]
Classic `Task.async` non-stacksafe bug. I'll push a fix branch in a few seconds.

**Comment by rossabaker** [comment]
Closed by #460.

**Comment by mkokkola** [comment]
Thank you! Any ETA for releasing 0.11.2?

**Comment by bryce-anderson** [comment]
Pretty soon, a day or so I expect. We are trying to iron out some client issues atm but I think we're almost there. I suspect you need this sooner rather than later? If you don't mind snapshots, I believe 0.11.2-SNAPSHOT is published to sonatype snapshots.
