### ISSUE TITLE
Multipart Parsing seems to be broken when updating to 1.0.0-M21

### ISSUE THREAD

**Issue by L7R7** [http4s/http4s#4760]
I have a small project that reads a paginated HTTP resource that produces Multipart documents. I'm currently trying to upgrade from http4s 0.x to the latest 1.0.0 milestone. I got it to compile, but now the multipart parsing fails with an exception.

I put together a small project to demonstrate it: https://github.com/L7R7/http4s-multipart

In a nutshell, what i have is the following:

```scala
def responseToParts: Pipe[IO, Response[IO], Part[IO]] = _.flatMap { response =>
  findBoundary(response.headers) match {
    case Some(boundary) => response.body.unchunk.through(MultipartParser.parseToPartsStream(boundary))
    case None => Stream.raiseError[IO](new IllegalStateException("no boundary found"))
  }
}

def findBoundary(headers: Headers): Option[Boundary] =
   headers.find(_.is(`Content-Type`))
     .map(_.value)
     .flatMap { s =>
       s.split(";")
         .map(_.trim)
         .find(_.startsWith("boundary="))
         .map(_.replace("boundary=", "").replace("\"", ""))
     }
     .map(Boundary(_))
```

when I feed in the response, I get the following stacktrace:

```
[error] (run-main-0) org.http4s.MalformedMessageBodyFailure: Malformed message body: Malformed Malformed match
[error] org.http4s.MalformedMessageBodyFailure: Malformed message body: Malformed Malformed match
[error] 	at org.http4s.multipart.MultipartParser$.$anonfun$ignorePrelude$2(MultipartParser.scala:209)
[error] 	at fs2.Pull$$anon$1.cont(Pull.scala:149)
[error] 	at fs2.Pull$BindBind$$anon$7.<init>(Pull.scala:622)
[error] 	at fs2.Pull$BindBind.cont(Pull.scala:622)
[error] 	at fs2.Pull$BindBind$$anon$7.cont(Pull.scala:624)
[error] 	at fs2.Pull$.mk$1(Pull.scala:638)
[error] 	at fs2.Pull$.fs2$Pull$$viewL(Pull.scala:643)
[error] 	at fs2.Pull$.fs2$Pull$$go$1(Pull.scala:1118)
[error] 	at fs2.Pull$StepRunR$1.$anonfun$done$2(Pull.scala:884)
[error] 	at fs2.Pull$.$anonfun$compile$1(Pull.scala:805)
[error] 	at cats.effect.IOFiber.next$2(IOFiber.scala:358)
[error] 	at cats.effect.IOFiber.runLoop(IOFiber.scala:366)
[error] 	at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1134)
[error] 	at cats.effect.IOFiber.run(IOFiber.scala:145)
[error] 	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:397)
```

The same thing with the same Multipart Document n 0.21.22 works fine. The changelog doesn't say anything about whether I should change the code with the new version, so I don't know if I found a bug (or maybe the code shouldn't have worked with the old version?)

The sample project linked above contains the code for both versions, including a small server to test it

**Comment by L7R7** [comment]
Closing this. I found out that the boundary can be obtained like so:

```scala
def findBoundary(headers: Headers): Option[Boundary] =
  headers
    .get[`Content-Type`]
    .flatMap(_.mediaType.extensions.get("boundary"))
    .map(Boundary(_))
```

I don't know exacly why, but this seems to work
