### ISSUE TITLE
ForwardedRenderersSuite flake

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4834]
On v0.21.13 tag:

```
==> X org.http4s.headers.ForwardedRenderersSuite.Forwarded  0.167s munit.FailException: Failing seed: l8P8VpvBMrvLPHqn5jU_2S64ktyAmI4XuoUzLxrxN-C=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "l8P8VpvBMrvLPHqn5jU_2S64ktyAmI4XuoUzLxrxN-C="

Exception raised on property evaluation.
> Exception: org.http4s.ParseFailure: Invalid scheme: Invalid input '-', expected 's' or 'EOI' (line 1, column 5):
http-q-Wm
    ^
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:98)
Caused by: org.http4s.ParseFailure: Invalid scheme: Invalid input '-', expected 's' or 'EOI' (line 1, column 5):
http-q-Wm
    ^
```

**Comment by armanbilge** [comment]
Here's one in series/0.23: 9831b677803c6155cec8f3f3cad84866caa69794

<details>

```
==> X org.http4s.headers.ForwardedRenderersSuite.Forwarded  0.623s munit.ComparisonFailException: /home/runner/work/http4s/http4s/tests/shared/src/test/scala/org/http4s/headers/ForwardedRenderersSuite.scala:100
99: 
100:      assertEquals(Forwarded.parse(rendered.drop(headerInit.length)), Right(fwd))
101:    }
values are not the same
=> Diff (- obtained, + expected)
-Left(
-  value = ParseFailure(
-    sanitized = "Invalid Forwarded header",
-    details = """for="unknown:49692";host=":0";proto=HTTPS, host=":0";proto=HTTPS, for="14.1.128.128:54974";host=":1", for="unknown:__ME-_i.Vyp..U";host=":60766";proto=jIFwksXgSBbV0vt1E, for="_-BNcv-4._I._8_-U_:_Wql-K-o---HGt_9K--K.j-k__.wp7.DBJ40Q--.3_DQ_.-c..ZHMg_Z_XjM3WIJqID._-fN----UcG--_._";host=":62464";proto=http, for="unknown:_UO5-.JE-..JZI-__.iCb__tN.__l.-t-_z.-_8";host="fl:1";proto=https, for="unknown:__lH--.T_J_-.Lu.ZR_yrn-2.WRu--.9D.._R_1.._HD--h_-LX-_-rAQT..3Iv_.To_c-._Syoy-...m-";proto=https, for=_a_9L_A.N_L.-zG;host=":1", host="C-l9qJf-R-a---5--O--D-----O-W8W-H--hSM-hGJe-1--D-ZW-oU-b9I--olc.Dh-C--U-F----EL--Scec-xR-w--W-p-8.rs1-zF--E-c1-d--Eg-W3j-zQG----T--R3-r7Xa---d-pB---uqK----v--4Zm.OG.7N:1";proto=https, host="[9bb:257f:175:f6:c29f:677f:8048:529d]";proto=https, host="144.168.255.127:0", by="127.128.1.237:9396", for="[807f:16f:6151:1f1:1df:ff00:c58b:7cff]:_i__-v-lV.c-..rSa6Kh-.o.-.xc4KJ__o__7._Y.-oG.OTe1_zT.q..Jn--.___b_Z_8_1-";host="130.116.1.128:55976";proto=http, by="_-tx.5ws_0__-_Q._-UIly-_3t_y0l__H_UMn.t__-_-k__Sa1-._-..c_.D.:8650", for="[7f67:100:a6b2:1df:d6:ff01:1a6:2635]";host=":34073", for="_-cE_q_..pxXte._.-.-__-T__W_.._e-:0";host=":0";proto=HTTP, proto=https, for="_gM.d_Xk..--Z---Ah._excA-t_.F-.-Ig_O-.l.Aql.Wc-E-_.H-._HG-X.Da4w--uxaOV:_.._O-.o.0_-_Nu-X--h.l.rq.Bd8iLD--__.Xl_.-k_.--.5.-yPt...Pmw_..8.-__ciq-Z4KF_...2--_";host="1.56.252.127:50639";proto=http, for="_ZnNqPOo98MMA6t-.-OR_.gLBO_-sXU_D.g_S.Mv_.__..-.-.N8.b-m--o-:0";host="1.0.128.121:0";proto=HTTP, for="unknown:65535";host=":65535", for="_.B.__-_-_M_-P.-Ys..qy.uq8-.n.-B--q...W-E-..-_T23-7_sDu-2Al---B9M_:1";host="Ee.MR3--Qu-IPl--z-fw.g--TY--cO-4G-s--nJ-tYs-k----lo-5--W---Px--9---j-Y-----G8G---f-v:0";proto=https, for="_c-__9Z0._A.G_x-5-__-_h2-e_q-o_m-6Na-z.ky-H-6o-t0d.._.Vn:_Z7R.X.r..r";host=":61215";proto=https, for="1.36.42.127:0", for="unknown:22432";proto=http, for="[ff30:f01:8092:180:e501:268c:62:3]:_.Ml-._Q.6u._..X.Jq-_-B2-QIX.c_eAG-.-_LgYX-_.R._OxaXUj__5fW";host=tgQ5v-Ih3----3I----A;proto=http, for=60.230.0.127;proto=https, for="unknown:1";host="255.250.39.128:2651";proto=http, for="_..9.x0t04Fr.Z-5x_ru_5-_s--Kp6-._cO0_.Yy_pD_A..._dTx..j.F6---3.pU.KR-T_nt-.t.___.Gn.-V-.Y-_1m:_..";host="248.177.0.4:41474";proto=Q5Yp.BthnZfgu5GoKxkSP7X.7-j6FnSQ-VT91o3h+Timh6jR7XSAX4vTyE0TBlm1hmYCNoVDHAMlaM5+wt5aaGyr.vp, for="[1ce:afff:f7:7f6f:7fff:4e7f:f27f:63]";host="";proto=HTTPS, by="_mW_--.-_-AW..dvcW-_pydr9j_D3_-S2-__-T_K:36411", for="[8025:7f7f:ff53:ff80:276e:1ff:8080:f3c5]:0";proto=https, for="unknown:58497";host=":0";proto=F8fuT2i3AhTrqiAlNw7ftmMFSk-L.2uq4, for="unknown:_B.EK_S_h.d-._aEcFP-0K.__-SH-_M.vd_.-_kC.-.nzvECP7-h-CzwQU-_.iE45ysF--", for="_.C-dBWgjVZqPg-_8.__:51602";host=":0";proto=HTTPS, for="[1:4501:ff84:27f:f7ab:fffc:552:8057]:_3N.ZN2V7AL.e", for="[7cbb:8072:1ff:ee1a:6f01:ba80:ff00:977f]";proto=http, host=":35772", for="[ff54:877f:9e:9601:7f16:5480:8b24:7ffa]";proto=https, for="0.127.128.127:_0_Q69NV0_-_";proto=http, for="_et_M.Ro___bYnb--S.--..._y.BojYR-.0-C-_lXQ-OT.__k.-__.A_hRw..-A74.tk-.c:36488";host=":23489";proto=https, host="[95ca:ae78:ff00:ff87:a2bf:c000:9c00:cd56]:0", for="[ff01:25eb:12a:66a8:ff01:ffff:8080:808e]:29637";host="BLQ-VG-E-k----Yb--Uv-BSEJN---1-l-ji-Rni---j-xk--p7-23V.hPB.uu-D0-FA----o-9nPL-P-836-FUCD----U-4-P--Db-T-v-K--------I---aFs:54079", for="unknown:__.._F--.CRV";host=":34890", for="[12c:9680:95d0:b427:7f7f:983c:a8f:31]:_.9C8-2KNl7W__..Wnn.j_i.hKu-._3-.fwIDZ_-04T3_3KLH.-b-6__2T_k.YYQN99.AGE.G_.C3_m--V1acW", for="[ced3:807f:97b0:101:8327:6059:1ff:a406]:_--_-aI-gzY_saSYC.VL-_a._qbKX-k-R_T-cB9.--_WT_.A-Q_Gs.GD1z..m-G_.-.e_5R-__.Hd.x2.tx-5_y_Z-bg1_-._";host=":24466", for="unknown:_h-_Si2.._-a";host=":0", for="unknown:25519";proto=http, for="_.:45107";host=":0";proto=http, host="[7201:8000:3675:19f:1380:ff17:1e8:17f]:1", for="[1e4:7f01:2c88:1a:7f8b:a400:ffff:6b57]:35552";proto=nQtbf, for="[8049:1ff:847f:61ff:9e7f:f7ff:9ae2:101]:0";proto=https, for="128.142.127.123:_gwP.AR_fJlW-Sm7.gLe._z_0jz_iv_Uz-C-TxN.-";host="[d451:e3ff:ff7f:cc5d:ff:ffff:7f01:7a2d]:58949", host="[b8be:7f00:a800:ff01:ff19:507e:c080:808e]:0";proto=http, for="[8001:a5:5380:80e2:6801:8044:7e80:8a41]:0";host="", host=":1", for="__q..i-__-W-_PV.8:_-_l2j.";host=":31990";proto=NtrIXr+il50Fm6nNZR-tzpxpI0uJdDlxd7q0jiTlJ5-1MYCH0gIZ, host="[7f7f:ff83:8078:80ac:8b00:431c:87:64b7]", for="_-R..L_r__.e-N-N.Fa-o32.1oy_D_.bGK-.CVusJ_-x----4---a-__ZHM--9nm:_-_.-_f_A9_KF-7_v-_S.Nq-jkf-_r5cP78-";host="g6:0";proto=http, for="_fm0dK.-BpbsP_uF.-J_hJJw--R.H_-_ny4-.-UwX_yOk-El_.Jh_w-u...:0";host="[128e:4382:9201:1:ffff:7f7f:c780:17f]:17151";proto=https, for="_-3-_-Cg8._S_ti_6-.t.qc.MK.e_x.rFf_s_.g.-_.--Ao-i.L-.p-9-9_-x-yD-..k-:0";host="255.55.147.1:0", host="hBr-A---w2--u-Z-ua---F-5RI-l2I-x---wr:54828", for="0.128.85.255:0";proto=http, for="[95:7fff:87ca:e00:82:1bf:1da:12fd]:_6O_..g-i.__.s-I.e8X-Y-Vf._IGliJv-U_.-w__YX_Z_HX.__.-b..A.._s2.Hq58_..DCI-O0Wd9--Va.kpQ.-..";host=":0";proto=http, for="[55:6fc4:4480:b401:5d01:ff7f:7f7f:9ae1]:_._U_5--uN.fWTey2-Iita9V..-pJ.._-tZ_tE-.-EN-_iy__-d__vTy_S-.Yr.7_M_r-H--H_.I.kv-", for="_.wN_-r-_-.bE2z.._7r___n.B_B._X_-mkfZ8my1.-__u_--PJWqo.u8o8.t-:_zaEQN-.-m-.0.F--o.._TTd_6y";proto=http, for="unknown:__-0__9l.a-A-nPcct5_.bEHq._E_AgWS-tA---rh-JLA-..q1N_L--.-.-.wb-lZ---_._";host=":0";proto=HTTP, host="[a23b:d479:1c01:b07f:100:6800:7f0b:ffff]";proto=http, for="[101:c4:f900:bafd:7f00:7f80:3d8:ff18]:_NM-_gji-Id_iVe-Q-_d2__Yj.iTe_.j_qG-.";proto=http, for="unknown:25934";host="[8080:8001:6680:787f:3f01:8ed4:cc00:fef2]:33512", for="_cf_hT:_DJK_.e-._8MB2___7_iw-M.";host=":57592", for="unknown:_.-7.n7et.__Cdb-_-5-_jm-__Y.q-__-ym_t4._h_l-9_mF_..hi.E_9M__P-_";host="[4e01:e500:ff0f:a7b2:5b7f:ca01:4b8f:c87f]:65535", for="[2cc4:ff:80:3e8f:7f80:8000:a490:7889]:_aN_M--._9-1X--gi...zLtZl..uRs9_-_.N.m_V__1";host=":65535";proto=yLzkfP0elbL0, for="255.0.40.128:1";host="qv1--6R-ZLL-0s0-j.et.At:0";proto=http, for="unknown:12169";proto=https, for=_-._.s-.d_.bq.m.-KWt.__l..v-..C_EW..3-.rS--_T--.e--A-_-_.c..._K-C-4L-G._a.-p__Q.gJ__;host=":65535";proto=opqQ3oWve24Tc0-SwWOkWYe8ylf116kdGHmxO7DYvhLkOyBSoHEw7-9XfZ6aWX+7C.+YDXhRO7TftPpK22nY-MLBTgPy-j, for="_Yh___cnn4cTE7-e_--hv-.7.._b-ZH-.l-N---ktl_.nE--Nc.u_zu---.K-_zsNLA._.j_gFz.Q4--Als_dCB.--:_w_..1E-40";proto=https, for="127.1.127.255:65535";host="4.25.4.3SV-OzeE-u--c-Lm-Bo6R-o-eZqh--3w--m:0";proto=http, for="[1ff:ff8d:999c:e5a:4fff:3eb:e17f:c943]:_--.-R_-W-.Q.F._.-";host=":45495", for="_.-_._3I..qk_hL_.____T.-ha2S-_0OcK.m.-B._fl.._fN-Zz9t9tP:15274";host=":10879";proto=yve5rgQ4R.8EZHlgDLJH7BIlB36S.lGVB5Kw4G4wl-H1tLaG2VdOjHUiSf, for="unknown:_NrV--6_6.D_.-__.rA3.-DWgQa.U2-Z-n_rY_.4lIt-_g4jw9";host=":25573";proto=rO8fajxGqOxa+ZbZNzdfA3LjQSHXFBeVct2aM3H.3SO0T3NiMLbQM4gZYc2q64G, by="_.83-bMPua--ML_L-8o.f.d1_C.:_l_.-_-gBsM._-_-", proto=http, for="172.128.246.176:48476";host=":1";proto=http, for="unknown:_s_.dGBfa-wO_-_tEp_ZL-LN.--5N.l-fv__uN-J__Z_tpM_FKnZ";host="";proto=CnbMbPLefwir41uCg.CI0RLXEb5xAT2CfLjOlnmW, proto=https, for="127.255.115.45:65535";host="0.0.140.136:0", for="0.255.0.0:0";proto=https, host=":55379", for="[5c69:e700:9b05:707f:dd80:ff71:b980:d977]:1660"
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ^
-expectation:
-* must fail"""
+Right(
+  value = Forwarded(
+    values = NonEmptyList(
+      head = Element(
+        maybeBy = None,
+        maybeFor = Some(
+          value = Node(
+            nodeName = Unknown(),
+            nodePort = Some(
+              value = Port(
+                value = 49692
+              )
+            )
+          )
+        ),
+        maybeHost = Some(
+          value = Host(
+            host = RegName(
+              host = ∙
+            ),
+            port = Some(
+              value = 0
+            )
+          )
+        ),
+        maybeProto = Some(
+          value = Scheme(HTTPS)
+        )
+      ),
+      tail = List(
+        Element(
+          maybeBy = None,
+          maybeFor = None,
+          maybeHost = Some(
+            value = Host(
+              host = RegName(
+                host = ∙
+              ),
+              port = Some(
+                value = 0
+              )
+            )
+          ),
+          maybeProto = Some(
+            value = Scheme(HTTPS)
+          )
+        ),
+        Element(
+          maybeBy = None,
+          maybeFor = Some(
+            value = Node(
+              nodeName = Ipv4(
+                address = 14.1.128.128
+              ),
+              nodePort = Some(
+                value = Port(
+                  value = 54974
+                )
+              )
+            )
+          ),
+          maybeHost = Some(
+            value = Host(
+              host = RegName(
+                host = ∙
+              ),
+              port = Some(
+                value = 1
+              )
+            )
+          ),
+          maybeProto = None
+        ),
+        Element(
+          maybeBy = None,
+          maybeFor = Some(
+            value = Node(
+              nodeName = Unknown(),
+              nodePort = Some(
+                value = Obfuscated(
+                  value = "__ME-_i.Vyp..U"
+                )
+              )
+            )
+          ),
+          maybeHost = Some(
+            value = Host(
+              host = RegName(
+                host = ∙
+              ),
+              port = Some(
+                value = 60766
+              )
+            )
+          ),
+          maybeProto = Some(
+            value = Scheme(jIFwksXgSBbV0vt1E)
+          )
+        ),
+        Element(
+          maybeBy = None,
+          maybeFor = Some(
+            value = Node(
+              nodeName = Obfuscated(
+                value = "_-BNcv-4._I._8_-U_"
+              ),
+              nodePort = Some(
+                value = Obfuscated(
+                  value = "_Wql-K-o---HGt_9K--K.j-k__.wp7.DBJ40Q--.3_DQ_.-c..ZHMg_Z_XjM3WIJqID._-fN----UcG--_._"
+                )
+              )
+            )
+          ),
+          maybeHost = Some(
+            value = Host(
+              host = RegName(
+                host = ∙
+              ),
+              port = Some(
+                value = 62464
+              )
+            )
+          ),
+          maybeProto = Some(
+            value = Scheme(http)
+          )
+        ),
+        Element(
+          maybeBy = None,
+          maybeFor = Some(
+            value = Node(
+              nodeName = Unknown(),
+              nodePort = Some(
+                value = Obfuscated(
+                  value = "_UO5-.JE-..JZI-__.iCb__tN.__l.-t-_z.-_8"
+                )
+              )
+            )
+          ),
+          maybeHost = Some(
+            value = Host(
+              host = RegName(
+                host = fl
+              ),
+              port = Some(
+                value = 1
+              )
+            )
+          ),
+          maybeProto = Some(
+            value = Scheme(https)
+          )
+        ),
+        Element(
+          maybeBy = None,
+          maybeFor = Some(
+            value = Node(
+              nodeName = ...,
+              nodePort = ...
+            )
+          ),
+          maybeHost = ...,
+          maybeProto = ...
+        ),
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...,
+        ...
+      )
+    )
   )

Failing seed: 9eDHW9fDxWvnqaBG7QEmYcoh1UGfCQi8yQtE-Dv9q1A=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "9eDHW9fDxWvnqaBG7QEmYcoh1UGfCQi8yQtE-Dv9q1A="

Falsified after 98 passed tests.
> Forwarded: Forwarded(NonEmptyList(for="unknown:49692";host=":0";proto=HTTPS, host=":0";proto=HTTPS, for="14.1.128.128:54974";host=":1", for="unknown:__ME-_i.Vyp..U";host=":60766";proto=jIFwksXgSBbV0vt1E, for="_-BNcv-4._I._8_-U_:_Wql-K-o---HGt_9K--K.j-k__.wp7.DBJ40Q--.3_DQ_.-c..ZHMg_Z_XjM3WIJqID._-fN----UcG--_._";host=":62464";proto=http, for="unknown:_UO5-.JE-..JZI-__.iCb__tN.__l.-t-_z.-_8";host="fl:1";proto=https, for="unknown:__lH--.T_J_-.Lu.ZR_yrn-2.WRu--.9D.._R_1.._HD--h_-LX-_-rAQT..3Iv_.To_c-._Syoy-...m-";proto=https, for=_a_9L_A.N_L.-zG;host=":1", host="C-l9qJf-R-a---5--O--D-----O-W8W-H--hSM-hGJe-1--D-ZW-oU-b9I--olc.Dh-C--U-F----EL--Scec-xR-w--W-p-8.rs1-zF--E-c1-d--Eg-W3j-zQG----T--R3-r7Xa---d-pB---uqK----v--4Zm.OG.7N:1";proto=https, host="[9bb:257f:175:f6:c29f:677f:8048:529d]";proto=https, host="144.168.255.127:0", by="127.128.1.237:9396", for="[807f:16f:6151:1f1:1df:ff00:c58b:7cff]:_i__-v-lV.c-..rSa6Kh-.o.-.xc4KJ__o__7._Y.-oG.OTe1_zT.q..Jn--.___b_Z_8_1-";host="130.116.1.128:55976";proto=http, by="_-tx.5ws_0__-_Q._-UIly-_3t_y0l__H_UMn.t__-_-k__Sa1-._-..c_.D.:8650", for="[7f67:100:a6b2:1df:d6:ff01:1a6:2635]";host=":34073", for="_-cE_q_..pxXte._.-.-__-T__W_.._e-:0";host=":0";proto=HTTP, proto=https, for="_gM.d_Xk..--Z---Ah._excA-t_.F-.-Ig_O-.l.Aql.Wc-E-_.H-._HG-X.Da4w--uxaOV:_.._O-.o.0_-_Nu-X--h.l.rq.Bd8iLD--__.Xl_.-k_.--.5.-yPt...Pmw_..8.-__ciq-Z4KF_...2--_";host="1.56.252.127:50639";proto=http, for="_ZnNqPOo98MMA6t-.-OR_.gLBO_-sXU_D.g_S.Mv_.__..-.-.N8.b-m--o-:0";host="1.0.128.121:0";proto=HTTP, for="unknown:65535";host=":65535", for="_.B.__-_-_M_-P.-Ys..qy.uq8-.n.-B--q...W-E-..-_T23-7_sDu-2Al---B9M_:1";host="Ee.MR3--Qu-IPl--z-fw.g--TY--cO-4G-s--nJ-tYs-k----lo-5--W---Px--9---j-Y-----G8G---f-v:0";proto=https, for="_c-__9Z0._A.G_x-5-__-_h2-e_q-o_m-6Na-z.ky-H-6o-t0d.._.Vn:_Z7R.X.r..r";host=":61215";proto=https, for="1.36.42.127:0", for="unknown:22432";proto=http, for="[ff30:f01:8092:180:e501:268c:62:3]:_.Ml-._Q.6u._..X.Jq-_-B2-QIX.c_eAG-.-_LgYX-_.R._OxaXUj__5fW";host=tgQ5v-Ih3----3I----A;proto=http, for=60.230.0.127;proto=https, for="unknown:1";host="255.250.39.128:2651";proto=http, for="_..9.x0t04Fr.Z-5x_ru_5-_s--Kp6-._cO0_.Yy_pD_A..._dTx..j.F6---3.pU.KR-T_nt-.t.___.Gn.-V-.Y-_1m:_..";host="248.177.0.4:41474";proto=Q5Yp.BthnZfgu5GoKxkSP7X.7-j6FnSQ-VT91o3h+Timh6jR7XSAX4vTyE0TBlm1hmYCNoVDHAMlaM5+wt5aaGyr.vp, for="[1ce:afff:f7:7f6f:7fff:4e7f:f27f:63]";host="";proto=HTTPS, by="_mW_--.-_-AW..dvcW-_pydr9j_D3_-S2-__-T_K:36411", for="[8025:7f7f:ff53:ff80:276e:1ff:8080:f3c5]:0";proto=https, for="unknown:58497";host=":0";proto=F8fuT2i3AhTrqiAlNw7ftmMFSk-L.2uq4, for="unknown:_B.EK_S_h.d-._aEcFP-0K.__-SH-_M.vd_.-_kC.-.nzvECP7-h-CzwQU-_.iE45ysF--", for="_.C-dBWgjVZqPg-_8.__:51602";host=":0";proto=HTTPS, for="[1:4501:ff84:27f:f7ab:fffc:552:8057]:_3N.ZN2V7AL.e", for="[7cbb:8072:1ff:ee1a:6f01:ba80:ff00:977f]";proto=http, host=":35772", for="[ff54:877f:9e:9601:7f16:5480:8b24:7ffa]";proto=https, for="0.127.128.127:_0_Q69NV0_-_";proto=http, for="_et_M.Ro___bYnb--S.--..._y.BojYR-.0-C-_lXQ-OT.__k.-__.A_hRw..-A74.tk-.c:36488";host=":23489";proto=https, host="[95ca:ae78:ff00:ff87:a2bf:c000:9c00:cd56]:0", for="[ff01:25eb:12a:66a8:ff01:ffff:8080:808e]:29637";host="BLQ-VG-E-k----Yb--Uv-BSEJN---1-l-ji-Rni---j-xk--p7-23V.hPB.uu-D0-FA----o-9nPL-P-836-FUCD----U-4-P--Db-T-v-K--------I---aFs:54079", for="unknown:__.._F--.CRV";host=":34890", for="[12c:9680:95d0:b427:7f7f:983c:a8f:31]:_.9C8-2KNl7W__..Wnn.j_i.hKu-._3-.fwIDZ_-04T3_3KLH.-b-6__2T_k.YYQN99.AGE.G_.C3_m--V1acW", for="[ced3:807f:97b0:101:8327:6059:1ff:a406]:_--_-aI-gzY_saSYC.VL-_a._qbKX-k-R_T-cB9.--_WT_.A-Q_Gs.GD1z..m-G_.-.e_5R-__.Hd.x2.tx-5_y_Z-bg1_-._";host=":24466", for="unknown:_h-_Si2.._-a";host=":0", for="unknown:25519";proto=http, for="_.:45107";host=":0";proto=http, host="[7201:8000:3675:19f:1380:ff17:1e8:17f]:1", for="[1e4:7f01:2c88:1a:7f8b:a400:ffff:6b57]:35552";proto=nQtbf, for="[8049:1ff:847f:61ff:9e7f:f7ff:9ae2:101]:0";proto=https, for="128.142.127.123:_gwP.AR_fJlW-Sm7.gLe._z_0jz_iv_Uz-C-TxN.-";host="[d451:e3ff:ff7f:cc5d:ff:ffff:7f01:7a2d]:58949", host="[b8be:7f00:a800:ff01:ff19:507e:c080:808e]:0";proto=http, for="[8001:a5:5380:80e2:6801:8044:7e80:8a41]:0";host="", host=":1", for="__q..i-__-W-_PV.8:_-_l2j.";host=":31990";proto=NtrIXr+il50Fm6nNZR-tzpxpI0uJdDlxd7q0jiTlJ5-1MYCH0gIZ, host="[7f7f:ff83:8078:80ac:8b00:431c:87:64b7]", for="_-R..L_r__.e-N-N.Fa-o32.1oy_D_.bGK-.CVusJ_-x----4---a-__ZHM--9nm:_-_.-_f_A9_KF-7_v-_S.Nq-jkf-_r5cP78-";host="g6:0";proto=http, for="_fm0dK.-BpbsP_uF.-J_hJJw--R.H_-_ny4-.-UwX_yOk-El_.Jh_w-u...:0";host="[128e:4382:9201:1:ffff:7f7f:c780:17f]:17151";proto=https, for="_-3-_-Cg8._S_ti_6-.t.qc.MK.e_x.rFf_s_.g.-_.--Ao-i.L-.p-9-9_-x-yD-..k-:0";host="255.55.147.1:0", host="hBr-A---w2--u-Z-ua---F-5RI-l2I-x---wr:54828", for="0.128.85.255:0";proto=http, for="[95:7fff:87ca:e00:82:1bf:1da:12fd]:_6O_..g-i.__.s-I.e8X-Y-Vf._IGliJv-U_.-w__YX_Z_HX.__.-b..A.._s2.Hq58_..DCI-O0Wd9--Va.kpQ.-..";host=":0";proto=http, for="[55:6fc4:4480:b401:5d01:ff7f:7f7f:9ae1]:_._U_5--uN.fWTey2-Iita9V..-pJ.._-tZ_tE-.-EN-_iy__-d__vTy_S-.Yr.7_M_r-H--H_.I.kv-", for="_.wN_-r-_-.bE2z.._7r___n.B_B._X_-mkfZ8my1.-__u_--PJWqo.u8o8.t-:_zaEQN-.-m-.0.F--o.._TTd_6y";proto=http, for="unknown:__-0__9l.a-A-nPcct5_.bEHq._E_AgWS-tA---rh-JLA-..q1N_L--.-.-.wb-lZ---_._";host=":0";proto=HTTP, host="[a23b:d479:1c01:b07f:100:6800:7f0b:ffff]";proto=http, for="[101:c4:f900:bafd:7f00:7f80:3d8:ff18]:_NM-_gji-Id_iVe-Q-_d2__Yj.iTe_.j_qG-.";proto=http, for="unknown:25934";host="[8080:8001:6680:787f:3f01:8ed4:cc00:fef2]:33512", for="_cf_hT:_DJK_.e-._8MB2___7_iw-M.";host=":57592", for="unknown:_.-7.n7et.__Cdb-_-5-_jm-__Y.q-__-ym_t4._h_l-9_mF_..hi.E_9M__P-_";host="[4e01:e500:ff0f:a7b2:5b7f:ca01:4b8f:c87f]:65535", for="[2cc4:ff:80:3e8f:7f80:8000:a490:7889]:_aN_M--._9-1X--gi...zLtZl..uRs9_-_.N.m_V__1";host=":65535";proto=yLzkfP0elbL0, for="255.0.40.128:1";host="qv1--6R-ZLL-0s0-j.et.At:0";proto=http, for="unknown:12169";proto=https, for=_-._.s-.d_.bq.m.-KWt.__l..v-..C_EW..3-.rS--_T--.e--A-_-_.c..._K-C-4L-G._a.-p__Q.gJ__;host=":65535";proto=opqQ3oWve24Tc0-SwWOkWYe8ylf116kdGHmxO7DYvhLkOyBSoHEw7-9XfZ6aWX+7C.+YDXhRO7TftPpK22nY-MLBTgPy-j, for="_Yh___cnn4cTE7-e_--hv-.7.._b-ZH-.l-N---ktl_.nE--Nc.u_zu---.K-_zsNLA._.j_gFz.Q4--Als_dCB.--:_w_..1E-40";proto=https, for="127.1.127.255:65535";host="4.25.4.3SV-OzeE-u--c-Lm-Bo6R-o-eZqh--3w--m:0";proto=http, for="[1ff:ff8d:999c:e5a:4fff:3eb:e17f:c943]:_--.-R_-W-.Q.F._.-";host=":45495", for="_.-_._3I..qk_hL_.____T.-ha2S-_0OcK.m.-B._fl.._fN-Zz9t9tP:15274";host=":10879";proto=yve5rgQ4R.8EZHlgDLJH7BIlB36S.lGVB5Kw4G4wl-H1tLaG2VdOjHUiSf, for="unknown:_NrV--6_6.D_.-__.rA3.-DWgQa.U2-Z-n_rY_.4lIt-_g4jw9";host=":25573";proto=rO8fajxGqOxa+ZbZNzdfA3LjQSHXFBeVct2aM3H.3SO0T3NiMLbQM4gZYc2q64G, by="_.83-bMPua--ML_L-8o.f.d1_C.:_l_.-_-gBsM._-_-", proto=http, for="172.128.246.176:48476";host=":1";proto=http, for="unknown:_s_.dGBfa-wO_-_tEp_ZL-LN.--5N.l-fv__uN-J__Z_tpM_FKnZ";host="";proto=CnbMbPLefwir41uCg.CI0RLXEb5xAT2CfLjOlnmW, proto=https, for="127.255.115.45:65535";host="0.0.140.136:0", for="0.255.0.0:0";proto=https, host=":55379", for="[5c69:e700:9b05:707f:dd80:ff71:b980:d977]:1660"))
    at munit.ComparisonFailException.withMessage(ComparisonFailException.scala:55)
```

</details>
