### ISSUE TITLE
0.21.23 blaze-server possible regression

### ISSUE THREAD

**Issue by hamnis** [http4s/http4s#4856]
#4810 or #4796 may have caused a regression after upgrade.

We keep getting EOF exceptions in the log after upgrade.

I also see a few of 
 ```
java.lang.RuntimeException: TickWheelExecutor is shutdown
	at scala.sys.package$.error(package.scala:27)
	at org.http4s.blaze.util.TickWheelExecutor.schedule(TickWheelExecutor.scala:130)
	at org.http4s.blazecore.IdleTimeoutStage.org$http4s$blazecore$IdleTimeoutStage$$resetTimeout(IdleTimeoutStage.scala:81)
	at org.http4s.blazecore.IdleTimeoutStage$$anonfun$readRequest$1.applyOrElse(IdleTimeoutStage.scala:52)
	at org.http4s.blazecore.IdleTimeoutStage$$anonfun$readRequest$1.applyOrElse(IdleTimeoutStage.scala:52)
	at scala.concurrent.Future.$anonfun$andThen$1(Future.scala:500)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:439)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:80)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.tryFailure(Promise.scala:117)
	at scala.concurrent.Promise.tryFailure$(Promise.scala:117)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:104)
	at org.http4s.blaze.channel.nio1.NIO1HeadStage.org$http4s$blaze$channel$nio1$NIO1HeadStage$$doClose$1(NIO1HeadStage.scala:314)
	at org.http4s.blaze.channel.nio1.NIO1HeadStage$$anon$3.run(NIO1HeadStage.scala:344)
	at org.http4s.blaze.channel.nio1.SelectorLoop.executeTask(SelectorLoop.scala:85)
	at org.http4s.blaze.channel.nio1.NIO1HeadStage.doClosePipeline(NIO1HeadStage.scala:332)
	at org.http4s.blaze.channel.nio1.NIO1HeadStage.close(NIO1HeadStage.scala:301)
	at org.http4s.blaze.channel.nio1.SelectorLoop.$anonfun$killSelector$1(SelectorLoop.scala:228)
	at org.http4s.blaze.channel.nio1.SelectorLoop.$anonfun$killSelector$1$adapted(SelectorLoop.scala:224)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at org.http4s.blaze.channel.nio1.SelectorLoop.killSelector(SelectorLoop.scala:224)
	at org.http4s.blaze.channel.nio1.SelectorLoop.org$http4s$blaze$channel$nio1$SelectorLoop$$runLoop(SelectorLoop.scala:182)
	at org.http4s.blaze.channel.nio1.SelectorLoop$$anon$1.run(SelectorLoop.scala:59)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

downgrading to 0.21.22 resolves the issue

**Comment by rossabaker** [comment]
How easy is it to try with each of those reverted to narrow down which it is?

**Comment by hamnis** [comment]
Will get around to this on tuesday, there is a mandatory longweekend here in Norway, then I will try to reproduce and test with either reverted.

if we could ask the tickwheelExecutor if its alive, then we could partly avoid the shutdown message.
TickWheelExecutor.alive is private, so that would need a blaze-core change.

**Comment by rossabaker** [comment]
Are you getting this at the end, or in a running server?

**Comment by hamnis** [comment]
in a running server

**Comment by hamnis** [comment]
```{
  "insertId": "vd10ylg196avbs",
  "jsonPayload": {
    "message": "Error servicing request: GET /api/users/permits from 10.x.x.x",
    "@timestamp": "2021-05-19T13:36:05.603Z",
    "stack_trace": "org.http4s.blaze.pipeline.Command$EOF$: EOF\n",
    "logger_name": "org.http4s.server.service-errors",
    "thread_name": "scala-execution-context-global-33",
    "@version": "1"
  },

  "timestamp": "2021-05-19T13:36:05.603873874Z",
  "severity": "ERROR",  
  "receiveTimestamp": "2021-05-19T13:36:09.005021384Z"
}```

**Comment by RafalSumislawski** [comment]
#4810 was a blaze-client only change. That leaves us with either #4796 or something-else. Is there a chance you could grab a tcpdump / wireshark dump of the communication when the EOF happens?

**Comment by hamnis** [comment]
Seems like a combination of incorrectly configured timeouts and one message gotten at shutdown.
Reconfigured the server to have more sane configuration.

Will create a PR for the shutdown issue. Closing this for now.
