### ISSUE TITLE
Add models for unmodelled headers

### ISSUE THREAD

**Issue by bplommer** [http4s/http4s#5010]
Quite a few headers don't yet have typed models. The following are the unmodelled headers that have their own page on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers), excluding those marked as deprecated.

- [ ] Accept-CH
- [ ] Accept-Post
- [ ] Access-Control-Allow-Methods
- [ ] Access-Control-Allow-Origin
- [ ] Access-Control-Max-Age
- [ ] Access-Control-Request-Headers
- [ ] Access-Control-Request-Method
- [ ] Alt-Svc
- [ ] Clear-Site-Data
- [ ] Content-Security-Policy-Report-Only
- [ ] Content-Security-Policy
- [ ] Cross-Origin-Embedder-Policy
- [ ] Cross-Origin-Opener-Policy
- [ ] Cross-Origin-Resource-Policy
- [ ] Device-Memory
- [ ] Digest
- [ ] DNT
- [ ] Downlink
- [ ] Early-Data
- [ ] ECT
- [ ] Expect-CT
- [ ] Expect
- [ ] Feature-Policy
- [ ] From
- [ ] If-Range
- [ ] Keep-Alive
- [ ] Large-Allocation
- [ ] NEL
- [ ] Referrer-Policy
- [ ] RTT
- [ ] Save-Data
- [ ] Sec-Fetch-Dest
- [ ] Sec-Fetch-Mode
- [ ] Sec-Fetch-Site
- [ ] Sec-Fetch-User
- [ ] Server-Timing
- [ ] SourceMap
- [ ] TE
- [ ] Timing-Allow-Origin
- [ ] Tk
- [ ] Trailer
- [ ] Upgrade-Insecure-Requests
- [ ] Vary
- [ ] Via
- [ ] Want-Digest
- [ ] Warning
- [ ] X-Content-Type-Options
- [ ] X-DNS-Prefetch-Control
- [ ] X-Forwarded-Host
- [ ] X-Forwarded-Proto
- [ ] X-Frame-Options
- [ ] X-XSS-Protection

**Comment by rossabaker** [comment]
Thanks, @bplommer.  This is a great opportunity for anybody who wants to get their hands dirty with cats-parse.  Examples abound in the [headers package](https://github.com/http4s/http4s/tree/main/core/src/main/scala/org/http4s/headers), and I will be happy to coach anyone through.

If you'd like to work on these, please:
1. Pick one and leave a comment here so we don't duplicate work.
2. Branch off series/0.22.  These should all be additive as far as compatibility goes.
3. Open a PR.  If you're stuck, don't be shy to open a draft, and we'll help you through it.
4. GOTO 1

**Comment by zmccoy** [comment]
I'll grab the  X-Forwarded-Host.

**Comment by rcardin** [comment]
Can I take the `Access-Control-Max-Age` header?

**Comment by rossabaker** [comment]
@rcardin That would be wonderful.  Both yours and @zmccoy's have an interesting design point: they refer to seconds, which fit nicely as a `FiniteDuration`.  But if we use a `FiniteDuration` in the case class, they cease to round trip.  It's like using a `Double` in place of an `Int`.

I'm thinking maybe we should model those as a `Long` as the value, and have a convenience `toDuration` so people know that the `Long` means seconds.

**Comment by rcardin** [comment]
@rossabaker, I'm taking the implementation of the header `Age` as a reference. Is it correct?

**Comment by rossabaker** [comment]
Yes, I think an ADT would be appropriate for the `Access-Control-Max-Age`.

**Comment by rcardin** [comment]
@rossabaker, I'm stuck. If possible, I would use the "coaching card" right now. [Here](https://github.com/rcardin/http4s/blob/feature/5010--access-control-max-age-header/core/shared/src/main/scala/org/http4s/headers/%60Access-Control-Max-Age%60.scala) is what I've done until now. I cannot understand how to call the `Header.createRender` with an ADT.

If you can point me to some documentation of the parser, it would be great :)

**Comment by pektinasen** [comment]
Hey @rcardin , I'm not Ross Baker, and I have never contributed to this project or coached for that matter, but maybe I can still provide some feedback.

In createRendered you are supposed to give a function from `Access-Control-Max-Age` to `Long` (or any type that has a Renderer instance). Since you created an ADT with differented cases, you must pattern match on the different cases of your ADT when getting the max age.
Unfortunately age is private, and cannot be accessed in an anonymous function, even though it is defined in the companion object. So you either un-private it, or have to parse from duration again. I would also remove the duration and unsafeDuration from the trait and only implement it in the Cache case, but not sure how the ergonomics are when actually using the class then.

Here is my attempt at a parser for the -1 case, but not sure if that's an idiomatic way to do it. 
```
  private[http4s] val parser = AdditionalRules.NonNegativeLong.orElse(
    (Parser.char('-') ~ Parser.char('1')).as(-1L)
  ).map(unsafeFromLong)
```

**Comment by rcardin** [comment]
Many thanks, @pektinasen 🥇 ! I will try it asap.

**Comment by rcardin** [comment]
@pektinasen, did you mean something like this?
```scala
implicit val headerInstance: Header[`Access-Control-Max-Age`, Header.Single] =
  Header.createRendered(
    ci"Access-Control-Max-Age",
    {
      case Cache(age) => age
      case NoCaching => -1
    },
    parse
  )
```

**Comment by pektinasen** [comment]
yes.

**Comment by rossabaker** [comment]
I think `Parser.char('-') ~ Parser.char('1')` can be `Parser.string("-1")`.  I doubt it's measurably faster, but it's easier to read and easier to grep.

Please don't be afraid to open a draft PR when you need help.  It's easier to discuss there than the big ticket.

And many thanks to @pektinasen for jumping in!

**Comment by rcardin** [comment]
I will take the `Access-Control-Allow-Methods` header, if I can :)
Let me know.

**Comment by rossabaker** [comment]
@rcardin, yes, thank you!  And I have not forgotten yours or Zach's above. 😓

**Comment by rcardin** [comment]
@rossabaker, no rush. The PRs will not go anywhere :P

**Comment by coltfred** [comment]
#5294 is a PR for DNT (in case someone wants to edit the issue to add that link).

**Comment by coltfred** [comment]
#5296 adds accept-post header model.

**Comment by m3is0** [comment]
Can I get the ```Clear-Site-Data``` ?

**Comment by mfirry** [comment]
Hi, I wanted to help here and just noticed that `X-Forwarded-Host` is basically the same as `Host` (or am I missing something?). I wonder what's the "best" way to re-use `Host` to define `X-Forwarded-Host`. 
Sorry if it's a silly question.

**Comment by rcardin** [comment]
@mfirry, I read the header documentation on the Mozilla site, and it seems you're right. I don't think that _code reuse_ is a good choice. The two headers are similar but very distinct objects at the model level.

IMHO, the best way to proceed is to copy the code from the `Host` header. I don't know if @rossabaker has something to say about your question :)

**Comment by zmccoy** [comment]
With Keep-Alive merged and released we can mark that done on the checklist :) ` Keep-Alive (@zmccoy)`

**Comment by armanbilge** [comment]
@MichalBednarz fantastic!

**Comment by bednam** [comment]
In meantime I'll start working on the `Cross-Origin` trio, if you don't mind.

**Comment by gbrown3** [comment]
Hi all, I'd be interested in trying my hand at Accept-CH!

**Comment by armanbilge** [comment]
@gbrown3 thanks, assigned! FYI the review cycle for these contributions is currently extremely slow (sorry!) but they are very much appreciated.

**Comment by gbrown3** [comment]
> @gbrown3 thanks, assigned! FYI the review cycle for these contributions is currently extremely slow (sorry!) but they are very much appreciated.

No worries, the dev cycle will probably be pretty slow on my end since this will be my first time attempting to make an http4s contribution :)

**Comment by gbrown3** [comment]
Also, and this might be the wrong place for this, but has anyone else encountered the exception below when trying to start sbt on a fresh fork of http4s? I was able to start sbt on the main fork `series/0.23` branch just fine, but for some reason this consistently pops up on [my fresh fork](https://github.com/gbrown3/http4s):
```
java.util.NoSuchElementException: key not found: (0,23)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:107)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:105)
	at org.http4s.sbt.Http4sSitePlugin$.$anonfun$projectSettings$5(Http4sSitePlugin.scala:52)
```

**Comment by armanbilge** [comment]
@gbrown3 Your fresh fork doesn't seem to include the tags. You'll need those as well, they are used to determine previous versions for compatibility-checking.

**Comment by gbrown3** [comment]
@armanbilge that was exactly it, thank you! These are the steps I followed to update the tags for my fork, in case any other folks run into the same issue and happen to find this discussion when searching: https://gist.github.com/Saissaken/b555f2c0772bee56601f70df501b6c96

**Comment by gbrown3** [comment]
First PR is up! I would also be interested in taking a crack at `Content-Security-Policy` if that works for y'all.

**Comment by armanbilge** [comment]
@gbrown3 awesome!! Claimed 😉

**Comment by samspills** [comment]
Hey could someone tag me for `Cross-Origin-Resource-Policy` ? Thanks!

**Comment by satorg** [comment]
Would it make sense to add #6793 to the list of models?

**Comment by jcz2** [comment]
Hi, can I be assigned the `From` header? Thanks!

**Comment by armanbilge** [comment]
@jcz2 done, thanks!

**Comment by sierikov** [comment]
I'll try to take `X-Frame-Options` next.

**Comment by albertoadami** [comment]
Hi, I wanted to tacke the `X-XSS-Protection` header as first issue. Could I be assigned to it? Thanks

**Comment by jatcwang** [comment]
We at London Scala User Group wants to pick up a few for our hack nights.
We have started on 
 
* RTT (@jatcwang)
* Alt-Svc (@alstepan)

Can someone assign these to us? Thanks!

**Comment by jarmuszz** [comment]
Hi, can I grab `ECT`? Thanks :)

**Comment by alstepan** [comment]
> We at London Scala User Group wants to pick up a few for our hack nights. We have started on
> 
> * RTT ([@jatcwang](https://github.com/jatcwang))
> * Alt-Svc ([@alstepan](https://github.com/alstepan))
> 
> Can someone assign these to us? Thanks!

Alt-Svc pr: https://github.com/http4s/http4s/pull/7671
