### ISSUE TITLE
TickWheelExecutor causes OOM

### ISSUE THREAD

**Issue by danielleontiev** [http4s/http4s#5116]
blaze-core:0.15.1
My application is based on http4s-blaze-server:0.23.0

Application crashed: `java.lang.OutOfMemoryError: Java heap space`

Heap size was slowly increasing during ~ 1 week and then OOM occurred

![image](https://user-images.githubusercontent.com/24596613/130954593-8d7257af-4c7a-4043-ae87-3db2c5462938.png)

Looking at heap dump it seems TickWheelExecutor was keeping `Register` and `Cancel` objects infinitely

![image](https://user-images.githubusercontent.com/24596613/130954413-3ae35842-0fd4-44d0-958e-690a1fb582f2.png)

**Comment by rossabaker** [comment]
`TextFormat.write` is blocking IO.  You're shifting it off to a cached thread pool, but cancellation will still hang in Cats-Effect 3 until the effect completes.  I am surprised it would hang forever, but maybe?  If you wrapped it in `IO.interruptible`, I don't believe you could get into this state.

That said, we shouldn't block the executor thread on response cancellation, and didn't before http4s-0.23.  I believe #5118 will fix it, even if your response is not cancelable at all.

**Comment by rossabaker** [comment]
Hard to say without a reliable repro, but #5118 should fix this.  We're preparing a release train this week.  If it comes up again, please reopen.

**Comment by danielleontiev** [comment]
@rossabaker thank you a lot for the fix! I think not blocking scheduler thread should fix it. But I still was wondering why it has happened? I started to hack the example and did this:

 ```scala
import cats.effect.{ExitCode, IO, IOApp}
import io.prometheus.client.hotspot.DefaultExports
import org.http4s.HttpRoutes
import org.http4s.blaze.server.BlazeServerBuilder
import org.http4s.dsl.io._
import org.http4s.server.Router
import org.http4s.syntax.all._

import java.util.concurrent.Executors
import java.util.concurrent.atomic.AtomicInteger
import scala.concurrent.ExecutionContext

object Main extends IOApp {
  DefaultExports.initialize()

  val tp = Executors.newCachedThreadPool()
  val ec = ExecutionContext.fromExecutor(tp)

  val counter = new AtomicInteger()

  val metrics: HttpRoutes[IO] = HttpRoutes.of[IO] {
    case GET -> _ =>
      (if (counter.get() == 3) {
         IO {
           counter.incrementAndGet()
           scala.io.StdIn.readLine()
         }
       } else {
         IO.pure(counter.incrementAndGet().toString)
       })
        .flatMap(Ok(_))
  }

  val server = BlazeServerBuilder[IO](ec)
    .bindHttp(9090, "0.0.0.0")
    .withHttpApp(Router("/" -> metrics).orNotFound)
    .resource

  override def run(args: List[String]): IO[ExitCode] =
    server.useForever.as(ExitCode.Success)
}
```

This should block on 4'th call. After 60 seconds (default idle timeout) blaze-tick-wheel-executor becomes `WAITING` forever:

```java
"blaze-tick-wheel-executor" #27 daemon prio=5 os_prio=31 cpu=43.49ms elapsed=535.46s tid=0x00007f9b819b3000 nid=0x8603 waiting on condition  [0x000070000de3a000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11/Native Method)
        - parking to wait for  <0x000000070a4439c8> (a scala.concurrent.impl.CompletionLatch)
        at java.util.concurrent.locks.LockSupport.park(java.base@11/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11/AbstractQueuedSynchronizer.java:1039)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11/AbstractQueuedSynchronizer.java:1345)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:207)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.Await$$$Lambda$693/0x0000000800549c40.apply(Unknown Source)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.Await$.result(package.scala:124)
        at org.http4s.blaze.server.Http1ServerStage.$anonfun$cancel$1(Http1ServerStage.scala:331)
        at org.http4s.blaze.server.Http1ServerStage.$anonfun$cancel$1$adapted(Http1ServerStage.scala:330)
        at org.http4s.blaze.server.Http1ServerStage$$Lambda$692/0x000000080054a040.apply(Unknown Source)
        at scala.Option.foreach(Option.scala:437)
        at org.http4s.blaze.server.Http1ServerStage.cancel(Http1ServerStage.scala:330)
        at org.http4s.blaze.server.Http1ServerStage.stageShutdown(Http1ServerStage.scala:322)
        - locked <0x0000000700941be8> (a org.http4s.blaze.server.Http1ServerParser)
        at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:95)
        at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:94)
        at org.http4s.blaze.server.Http1ServerStage.closePipeline(Http1ServerStage.scala:86)
        at org.http4s.blaze.server.Http1ServerStage.$anonfun$initIdleTimeout$1(Http1ServerStage.scala:137)
        at org.http4s.blaze.server.Http1ServerStage.$anonfun$initIdleTimeout$1$adapted(Http1ServerStage.scala:132)
        at org.http4s.blaze.server.Http1ServerStage$$Lambda$305/0x0000000800354840.apply(Unknown Source)
        at org.http4s.blazecore.IdleTimeoutStage$$anon$1.run(IdleTimeoutStage.scala:80)
        at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:80)
        at org.http4s.blaze.util.TickWheelExecutor$Node.run(TickWheelExecutor.scala:271)
        at org.http4s.blaze.util.TickWheelExecutor$Bucket.checkNext$1(TickWheelExecutor.scala:207)
        at org.http4s.blaze.util.TickWheelExecutor$Bucket.prune(TickWheelExecutor.scala:213)
        at org.http4s.blaze.util.TickWheelExecutor.go$3(TickWheelExecutor.scala:168)
        at org.http4s.blaze.util.TickWheelExecutor.org$http4s$blaze$util$TickWheelExecutor$$cycle(TickWheelExecutor.scala:171)
        at org.http4s.blaze.util.TickWheelExecutor$$anon$1.run(TickWheelExecutor.scala:68)

   Locked ownable synchronizers:
        - None
```

Subsequent calls do not unblock it and atomic references with events starts growing:

![image](https://user-images.githubusercontent.com/24596613/131363811-8d376737-2878-42a0-a59d-1e26d9333924.png)

I've tried several time and it reproduces reliably.


The only thing that bothers me at that point is that I was thinking that the thread from cached pool should be still seen in thread dump locked performing blocking I/O. But with the example above it does not - cached pool is empty at the time I take thread dump (as was with my main application).

But I see the thread from computational pool that is locked:

```java
"io-compute-8" #22 daemon prio=5 os_prio=31 cpu=6.71ms elapsed=1091.37s tid=0x00007f9b80c2a000 nid=0x8e03 runnable  [0x000070000da2e000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(java.base@11/Native Method)
        at java.io.FileInputStream.read(java.base@11/FileInputStream.java:279)
        at java.io.BufferedInputStream.read1(java.base@11/BufferedInputStream.java:290)
        at java.io.BufferedInputStream.read(java.base@11/BufferedInputStream.java:351)
        - locked <0x00000007000b97c0> (a java.io.BufferedInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(java.base@11/StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(java.base@11/StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(java.base@11/StreamDecoder.java:178)
        - locked <0x0000000700aa1348> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(java.base@11/InputStreamReader.java:185)
        at java.io.BufferedReader.fill(java.base@11/BufferedReader.java:161)
        at java.io.BufferedReader.readLine(java.base@11/BufferedReader.java:326)
        - locked <0x0000000700aa1348> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(java.base@11/BufferedReader.java:392)
        at scala.io.StdIn.readLine(StdIn.scala:30)
        at scala.io.StdIn.readLine$(StdIn.scala:30)
        at scala.io.StdIn$.readLine(StdIn.scala:241)
        at Main$$anonfun$1.$anonfun$applyOrElse$1(Main.scala:37)
        at Main$$anonfun$1$$Lambda$746/0x00000008005d4840.apply(Unknown Source)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:383)
        at cats.effect.IOFiber.execR(IOFiber.scala:1126)
        at cats.effect.IOFiber.run(IOFiber.scala:125)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:306)

   Locked ownable synchronizers:
        - None
```

I think I am missing something, but the purpose of using cached thread pool was to shift blocking I/O to it. Why computational thread is blocked? 🤔 

I took another look at dead application's thread dump and it was the case too - one of the threads from computational pool was blocked on methods collection prometheus metrics.


I've changed `IO` to `IO.blocking` at the example and blocking computation has shifted:

```java
"io-blocking-0" #48 daemon prio=5 os_prio=31 cpu=2.06ms elapsed=72.86s tid=0x00007fb02f8d5000 nid=0xc00b runnable  [0x000070000d17a000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(java.base@11/Native Method)
        at java.io.FileInputStream.read(java.base@11/FileInputStream.java:279)
        at java.io.BufferedInputStream.read1(java.base@11/BufferedInputStream.java:290)
        at java.io.BufferedInputStream.read(java.base@11/BufferedInputStream.java:351)
        - locked <0x00000007003ad480> (a java.io.BufferedInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(java.base@11/StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(java.base@11/StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(java.base@11/StreamDecoder.java:178)
        - locked <0x000000070d69c908> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(java.base@11/InputStreamReader.java:185)
        at java.io.BufferedReader.fill(java.base@11/BufferedReader.java:161)
        at java.io.BufferedReader.readLine(java.base@11/BufferedReader.java:326)
        - locked <0x000000070d69c908> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(java.base@11/BufferedReader.java:392)
        at scala.io.StdIn.readLine(StdIn.scala:30)
        at scala.io.StdIn.readLine$(StdIn.scala:30)
        at scala.io.StdIn$.readLine(StdIn.scala:241)
        at Main$$anonfun$1.$anonfun$applyOrElse$1(Main.scala:26)
        at Main$$anonfun$1$$Lambda$725/0x00000008005c6c40.apply(Unknown Source)
        at cats.effect.IOFiber.blockingR(IOFiber.scala:1145)
        at cats.effect.IOFiber.run(IOFiber.scala:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11/Thread.java:834)

   Locked ownable synchronizers:
        - <0x000000070de74518> (a java.util.concurrent.ThreadPoolExecutor$Worker)

```

Am I misusing somthing here? What is the purpose of cached pool passed to `BlazeServerBuilder.apply` if computations are still need be shifted manually?

**Comment by danielleontiev** [comment]
Hm, I see this execution context is used only for underlying blaze futures, not for tasks I run as a part of application logic. Missed that point somehow. Will change to `.blocking` for prometheus part in the code
