### ISSUE TITLE
EmberWebSocketSuite: Unknown opcode 3

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5128]
https://github.com/http4s/http4s/pull/5124/checks?check_run_id=3456632732#step:13:3978

```
==> X org.http4s.ember.server.EmberServerWebSocketSuite.respond to pings  0.055s org.java_websocket.exceptions.InvalidFrameException: Unknown opcode 3
    at org.java_websocket.drafts.Draft_6455.toOpcode(Draft_6455.java:865)
    at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:533)
    at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:739)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
    at java.lang.Thread.run(Thread.java:831)
    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:136)
    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:136)
    at complete @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:55)
    at flatMap @ org.http4s.ember.server.EmberServerWebSocketSuitePlatform$Client.close$$anonfun$2(EmberServerWebSocketSuitePlatform.scala:48)
    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:136)
    at >> @ org.http4s.ember.server.EmberServerWebSocketSuitePlatform$Client.connect(EmberServerWebSocketSuitePlatform.scala:46)
    at map @ org.http4s.ember.server.EmberServerWebSocketSuite.$init$$$anonfun$16$$anonfun$3$$anonfun$3$$anonfun$3$$anonfun$3(EmberServerWebSocketSuite.scala:92)
    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:136)
```

**Comment by armanbilge** [comment]
An observation: this error so far only seems to occur on Java 16.

**Comment by rossabaker** [comment]
I wonder if also on 17?

**Comment by armanbilge** [comment]
Yes, I'm wondering that too. I suppose we'll find out.

**Comment by armanbilge** [comment]
Nope, got this similar (?) error on JDK 11.
```
==> X org.http4s.ember.server.EmberServerWebSocketSuite.open and close connection to server  0.185s org.java_websocket.exceptions.InvalidFrameException: Unknown opcode 3
    at org.java_websocket.drafts.Draft_6455.toOpcode(Draft_6455.java:888)
    at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:544)
    at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:762)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
    at java.lang.Thread.run(Thread.java:829)
    at get @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:74)
    at complete @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:56)
    at flatMap @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.$anonfun$close$2(EmberServerWebSocketSuite.scala:100)
    at apply @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.close(EmberServerWebSocketSuite.scala:100)
    at >> @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.connect(EmberServerWebSocketSuite.scala:98)
    at get @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:74)
```
