### ISSUE TITLE
EmberWebSocketSuite: NullPointerException

### ISSUE THREAD

**Issue by tpolecat** [http4s/http4s#5232]
Sporadic, I have only seen this once. Showed up in [this test run](https://github.com/http4s/http4s/pull/5152/checks?check_run_id=3654725372) (ubuntu-latest, 3.0.1, adopt@1.11).

```
org.http4s.ember.server.EmberServerWebSocketSuite:
3896
  + open and close connection to server 0.167s
3897
==> X org.http4s.ember.server.EmberServerWebSocketSuite.send and receive a message  0.046s java.lang.NullPointerException: null
3898
    at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:721)
3899
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:398)
3900
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
3901
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
3902
    at java.lang.Thread.run(Thread.java:829)
3903
    at get @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:73)
3904
    at complete @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:55)
3905
    at flatMap @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.close$$anonfun$2(EmberServerWebSocketSuite.scala:81)
3906
    at apply @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.close(EmberServerWebSocketSuite.scala:81)
3907
    at >> @ org.http4s.ember.server.EmberServerWebSocketSuite$Client.connect(EmberServerWebSocketSuite.scala:79)
3908
    at map @ org.http4s.ember.server.EmberServerWebSocketSuite.$init$$$anonfun$11$$anonfun$3$$anonfun$3$$anonfun$3$$anonfun$3(EmberServerWebSocketSuite.scala:147)
3909
```

**Comment by rossabaker** [comment]
[Again](https://github.com/http4s/http4s/pull/5250/checks?check_run_id=3675918530)

**Comment by danicheg** [comment]
This strikes again.
`ubuntu-latest, 2.13.7, temurin@8, ciJVM`
```
org.http4s.ember.server.EmberServerWebSocketSuite:
Error: Exception in thread "WebSocketConnectReadThread-3709" java.lang.IllegalStateException: dispatcher already shutdown
	at cats.effect.std.Dispatcher$$anon$2.unsafeToFutureCancelable(Dispatcher.scala:281)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed(DispatcherPlatform.scala:59)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed$(DispatcherPlatform.scala:58)
	at cats.effect.std.Dispatcher$$anon$2.unsafeRunTimed(Dispatcher.scala:188)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync(DispatcherPlatform.scala:51)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:50)
	at cats.effect.std.Dispatcher$$anon$2.unsafeRunSync(Dispatcher.scala:188)
	at org.http4s.ember.server.EmberServerWebSocketSuite$$anon$2.onError(EmberServerWebSocketSuite.scala:117)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:523)
	at java.lang.Thread.run(Thread.java:748)
16:42:26.138 [io-compute-0] ERROR o.h.e.s.EmberServerBuilderCompanionPlatform - WebSocket connection terminated with exception
org.http4s.ember.server.internal.WebSocketHelpers$EndOfStreamError: Reached End Of Stream
	at org.http4s.ember.server.internal.WebSocketHelpers$.$anonfun$decodeFrames$2(WebSocketHelpers.scala:224)
	at fs2.Pull$$anon$1.cont(Pull.scala:149)
	at fs2.Pull$.fs2$Pull$$bindBindAux(Pull.scala:681)
	at fs2.Pull$BindBind.cont(Pull.scala:672)
	at fs2.Pull$ContP.apply(Pull.scala:620)
	at fs2.Pull$ContP.apply$(Pull.scala:620)
	at fs2.Pull$Bind.apply(Pull.scala:628)
	at fs2.Pull$Bind.apply(Pull.scala:628)
	at fs2.Pull$StepRunR$1.$anonfun$done$2(Pull.scala:954)
	at fs2.Pull$.$anonfun$compile$2(Pull.scala:903)
	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1153)
	at update @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:77)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at modify @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:83)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at flatMap @ fs2.Pull$.$anonfun$compile$18(Pull.scala:1152)
	at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:160)
	at flatMap @ fs2.Pull$.goCloseScope$1(Pull.scala:1138)
	at get @ fs2.internal.Scope.openScope(Scope.scala:281)
```
https://github.com/http4s/http4s/runs/4619946647?check_suite_focus=true#step:14:4994

**Comment by armanbilge** [comment]
Same suite, but looks like a different error?

**Comment by danicheg** [comment]
Yep. Just to don't duplicate issues about that test suite.
