### ISSUE TITLE
Flaky EmberUnixSocketSuite

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5333]
```
org.http4s.ember.server.EmberUnixSocketSuite:
==> X org.http4s.ember.server.EmberUnixSocketSuite.Should be able to connect to a server created  4.891s java.io.IOException: No such file or directory
    at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:130)
    at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:139)
    at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:68)
    at fs2.io.net.unixsocket.JnrUnixSocketsImpl.$anonfun$openChannel$1(JnrUnixSockets.scala:48)
    at delay @ fs2.io.net.unixsocket.JnrUnixSocketsImpl.openChannel(JnrUnixSockets.scala:48)
    at allocated @ munit.CatsEffectFunFixtures$ResourceFixture$.$anonfun$apply$4(CatsEffectFunFixtures.scala:46)
    at map @ org.http4s.ember.client.EmberConnection$.$anonfun$apply$1(EmberConnection.scala:41)
    at of$extension @ org.typelevel.keypool.KeyPool$Builder.build(KeyPool.scala:340)
    at flatMap @ org.http4s.ember.client.EmberConnection$.apply(EmberConnection.scala:38)
    at make @ fs2.io.net.tls.TLSContextCompanionPlatform$BuilderCompanionPlatform$AsyncBuilder.fromKeyStoreResource(TLSContextPlatform.scala:284)
    at make @ fs2.io.net.tls.TLSContextCompanionPlatform$BuilderCompanionPlatform$AsyncBuilder.fromKeyStoreResource(TLSContextPlatform.scala:284)
    at allocated @ munit.CatsEffectFunFixtures$ResourceFixture$.$anonfun$apply$4(CatsEffectFunFixtures.scala:46)
    at swap @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:71)
    at flatMap @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:71)
```

https://github.com/http4s/http4s/pull/5329/checks?check_run_id=3797287620#step:12:4741

**Comment by armanbilge** [comment]
I think Raas warned us about this in https://github.com/http4s/http4s/pull/5219#discussion_r711812801.
