### ISSUE TITLE
`Retry` doesn't respect `maxRetry` configuration 

### ISSUE THREAD

**Issue by mr-git** [http4s/http4s#5489]
Using http4s **0.22.6**

Recently (for last few months, we used 0.21 branch, now switched to 0.22), during integration tests, we regularly get exceptions like:
```text
16:33:42  2021-10-25 13:33:41,670 INFO [org.http4s.client.middleware.Retry] Request method=POST uri=https://url.url.url.url.url.url.url.url headers=Authorization: <REDACTED>,Content-Length: 30,Content-Type: application/json,Accept: */* threw an exception on attempt #1. Giving up.
16:33:42  java.net.SocketException: HTTP connection closed: https://url.url.url.url.url.url.url.url
16:33:42  	at org.http4s.blaze.client.BlazeClient$$anonfun$1.applyOrElse(BlazeClient.scala:91)
16:33:42  	at org.http4s.blaze.client.BlazeClient$$anonfun$1.applyOrElse(BlazeClient.scala:90)
16:33:42  	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:263)
16:33:42  	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:106)
16:33:42  	at flatMap @ org.http4s.blaze.client.Http1Connection.$anonfun$executeRequest$3(Http1Connection.scala:243)
16:33:42  	at flatMap @ org.http4s.blaze.client.Http1Connection.$anonfun$executeRequest$1(Http1Connection.scala:212)
16:33:42  	at defer @ org.http4s.blaze.client.Http1Connection.executeRequest(Http1Connection.scala:191)
16:33:42  	at defer @ org.http4s.blaze.client.Http1Connection.runRequest(Http1Connection.scala:160)
16:33:42  	at map @ org.http4s.blaze.client.BlazeClient$.$anonfun$makeClient$4(BlazeClient.scala:93)
16:33:42  	at unsafeRunCancelable @ weaver.CatsUnsafeRun.background(CatsUnsafeRun.scala:22)
16:33:42  	at asyncF @ org.http4s.blaze.client.PoolManager.borrow(PoolManager.scala:167)
16:33:42  	at onFinalizeCase @ weaver.CECompat.onErrorEnsure(CECompat.scala:40)
16:33:42  	at use @ weaver.framework.RunnerCompat.run(RunnerCompat.scala:143)
16:33:42  	at unsafeRunCancelable @ weaver.CatsUnsafeRun.background(CatsUnsafeRun.scala:22)
16:33:42  2021-10-25 13:33:41,672 INFO [org.http4s.blaze.client.PoolManager] Shutting down connection pool: curAllocated=1 idleQueues.size=1 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
16:33:51  [0J2021-10-25 13:33:50,917 INFO [org.http4s.blaze.client.PoolManager] Shutting down connection pool: curAllocated=3 idleQueues.size=3 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
16:33:51  [0J2021-10-25 13:33:50,919 INFO [org.http4s.blaze.client.PoolManager] Shutting down connection pool: curAllocated=3 idleQueues.size=3 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
```

This can happen few times during concurrent int-tests at random URL. Each test case creates own http4s client.

We tried to workaround it by using `Retry` middleware:
```scala
      BlazeClientBuilder[IO](global).resource
        .map { client =>
          Retry[IO](RetryPolicy(RetryPolicy.exponentialBackoff(maxWait = 1.second, maxRetry = 5)))(client)
        }
        .map { client =>
          Logger(
            logHeaders = true,
            logBody = true,
            logAction = Some((s: String) => log.debug(s)),
          )(client)
        }
        .use { implicit client => ... }
```
But that didn't provide expected result - client fails on first attempt without making additional retries.
Sadly, the issue doesn't happen always, each test case makes 8..10 http calls, my project has only 3 test cases so far and we can observe this issue in about 2 of 5 builds. 

This looks a bit similar to #5180, but I am not sure, if it is a match and that got fixed for 0.23 branch, while we are at 0.22 and currently we cannot switch to CE3, yet, thus 0.23 is not an option for now.

**Comment by bplommer** [comment]
This is because `POST` is non-idempotent and so is not safely retriable. You can work around this either by using `recklesslyRetriable` (so the retry policy becomes `RetryPolicy(RetryPolicy.exponentialBackoff(maxWait = 1.second, maxRetry = 5), retriable = RetryPolicy.recklesslyRetriable)`) or by using the `Idempotency-Key` header to implement idempotency.

**Comment by mr-git** [comment]
@bplommer, does it mean that this is expected behaviour in particular situation (never retry `POST`, unless header is set)?

Sadly, I do not remember, if I've set `Idempotency-Key` at that time, though it might be nicer to get a bit better explanation in logs, like report error and explain why more attempts are not made in this particular case, like `.. Giving up because request is  not retryable`

Feel free to close the issue, if this is correct and expected behaviour, though it took me a bit of digging into http4s sources to understand that I have to use some other policy or set the header.

**Comment by bplommer** [comment]
> @bplommer, does it mean that this is expected behaviour in particular situation (never retry `POST`, unless header is set)?

Yes, that's correct.

> Sadly, I do not remember, if I've set `Idempotency-Key` at that time, though it might be nicer to get a bit better explanation in logs, like report error and explain why more attempts are not made in this particular case, like `.. Giving up because request is  not retryable`

That's a good idea! I'll create a new ticket for that and then close this issue.
