### ISSUE TITLE
Ember client doesn't shut down quickly when cancelled

### ISSUE THREAD

**Issue by stephenjudkins** [http4s/http4s#6058]
To replicate,  set `fork := true`, in your SBT config and compile the following:

```
import cats.data.Kleisli
import cats.effect.kernel.Resource
import cats.effect.{ExitCode, IO, IOApp}
import org.http4s.ember.server.EmberServerBuilder
import org.http4s.ember.client.EmberClientBuilder
import org.http4s.implicits.http4sLiteralsSyntax
import com.comcast.ip4s._

object TestEmberClientHang extends IOApp.Simple {
  def run: IO[Unit] = EmberClientBuilder.default[IO].build.use(_.statusFromUri(uri"http://localhost:8765")).void
}

object RunServer extends IOApp.Simple {
  def run: IO[Unit] =
    EmberServerBuilder.default[IO].withPort(port"8765").withHttpApp(Kleisli(_ => IO.never)).build.useForever
}
```

1. Run `runMain RunServer`
2. In a different SBT session, run `runMain TestEmberClientHang`
3. Hit ctrl+c in the second SBT session (with `TestEmberClientHang`)

Expected: the `TestEmberClientHang` process terminates immediately, like the version using the blaze client does.
Actual: the `TestEmberClientHang` process continues to run for > 30 seconds

Tested on macOS 12.0.1 (21A559)

**Comment by stephenjudkins** [comment]
Here's a fiber dump of the process:
```
cats.effect.IOFiber@ebb794e WAITING  ├ delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:123)  ├ async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:117)  ├ flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$read$1(SocketPlatform.scala:85)  ├ delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$withReadBuffer$1(SocketPlatform.scala:54)  ├ clear @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:77)  ├ clear @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:77)  ╰ clear @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:77)
 
cats.effect.IOFiber@4689c3fa WAITING  ├ void @ com.hifi.babylon.TestEmberClientHang$.run(TestEmberClientHang.scala:12)  ├ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)  ├ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)  ├ tryModify @ org.typelevel.keypool.KeyPool$.$anonfun$reap$8(KeyPool.scala:167)  ├ flatMap @ org.typelevel.keypool.KeyPool$.$anonfun$reap$8(KeyPool.scala:184)  ├ flatMap @ org.typelevel.keypool.KeyPool$.loop$1(KeyPool.scala:165)  ├ void @ com.hifi.babylon.TestEmberClientHang$.run(TestEmberClientHang.scala:12)  ╰ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:337)
 
cats.effect.IOFiber@141dafa WAITING  ├ timeout @ org.http4s.ember.core.Util$.timeoutMaybe(Util.scala:104)  ╰ timeoutTo @ org.http4s.ember.core.Util$.timeoutToMaybe(Util.scala:110)
 
cats.effect.IOFiber@44ba46ad WAITING  ├ timeout @ org.http4s.ember.core.Util$.timeoutMaybe(Util.scala:104)  ╰ timeout @ org.http4s.ember.core.Util$.timeoutMaybe(Util.scala:104)
 
cats.effect.IOFiber@4b5ae85 WAITING
 
cats.effect.IOFiber@4fd60e08 WAITING
 
cats.effect.IOFiber@9df4e28 WAITING
 
cats.effect.IOFiber@67c199e5 WAITING  ├ main$ @ com.hifi.babylon.TestEmberClientHang$.main(TestEmberClientHang.scala:11)  ├ void @ com.hifi.babylon.TestEmberClientHang$.run(TestEmberClientHang.scala:12)  ╰ main$ @ com.hifi.babylon.TestEmberClientHang$.main(TestEmberClientHang.scala:11)
 
Thread[io-compute-8,5,main] (#7): 0 enqueued Thread[io-compute-7,5,main] (#6): 0 enqueued Thread[io-compute-4,5,main] (#3): 0 enqueued Thread[io-compute-11,5,main] (#9): 0 enqueued Thread[io-compute-1,5,main] (#0): 0 enqueued Thread[io-compute-9,5,main] (#8): 0 enqueued Thread[io-compute-6,5,main] (#5): 0 enqueued Thread[io-compute-5,5,main] (#4): 0 enqueued Thread[io-compute-3,5,main] (#2): 0 enqueued Thread[io-compute-2,5,main] (#1): 0 enqueued
 
Global: enqueued 0, foreign 0, waiting 8
```

**Comment by armanbilge** [comment]
Is this running from outside of sbt?

**Comment by stephenjudkins** [comment]
This is running from inside SBT

**Comment by stephenjudkins** [comment]
(but I confirmed with a debugger that a signal went sent to the process and `IOApp` started the cancellation process)

**Comment by armanbilge** [comment]
Ok, seems to be hung here:
https://github.com/typelevel/fs2/blob/946763f56d2f589797f459458bbd3417f77e3979/io/jvm/src/main/scala/fs2/io/net/SocketPlatform.scala#L123

Which was recently added in:
- https://github.com/typelevel/fs2/pull/2734

What http4s/fs2 version is this? Also maybe try and old http4s/fs2 prior to that change if possible?

**Comment by stephenjudkins** [comment]
fs2 `3.2.4`, http4s `0.23.7`

**Comment by armanbilge** [comment]
Here's a thread dump.
```
Full thread dump OpenJDK 64-Bit Server VM (11.0.13+8-LTS mixed mode):

Threads class SMR info:
_java_thread_list=0x00007f139c005a80, length=17, elements={
0x00007f141c028800, 0x00007f141c1bd800, 0x00007f141c1c1800, 0x00007f141c1d6800,
0x00007f141c1d8800, 0x00007f141c1db000, 0x00007f141c1dd000, 0x00007f141c1df000,
0x00007f141c2b4000, 0x00007f141c87a800, 0x00007f141c87b800, 0x00007f141c87d800,
0x00007f141c87f000, 0x00007f141c881000, 0x00007f1398003000, 0x00007f13ac008000,
0x00007f139843b000
}

"main" #1 prio=5 os_prio=0 cpu=1076.27ms elapsed=13.82s tid=0x00007f141c028800 nid=0x11eb waiting on condition  [0x00007f1423794000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729825c00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.13/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.ArrayBlockingQueue.take(java.base@11.0.13/ArrayBlockingQueue.java:417)
        at cats.effect.IOApp.$anonfun$main$17(IOApp.scala:323)
        at cats.effect.IOApp$$Lambda$151/0x00000008002e5840.apply(Unknown Source)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.package$.blocking(package.scala:124)
        at cats.effect.IOApp.main(IOApp.scala:323)
        at cats.effect.IOApp.main$(IOApp.scala:203)
        at TestEmberClientHang$.main(client.scala:11)
        at TestEmberClientHang.main(client.scala)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.13/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.13/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.13/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.13/Method.java:566)
        at scala.cli.runner.Runner$.main(Runner.scala:15)
        at scala.cli.runner.Runner.main(Runner.scala)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.80ms elapsed=13.80s tid=0x00007f141c1bd800 nid=0x11f2 waiting on condition  [0x00007f14012d6000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.13/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@11.0.13/Reference.java:241)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.13/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.40ms elapsed=13.80s tid=0x00007f141c1c1800 nid=0x11f3 in Object.wait()  [0x00007f14011d5000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.13/Native Method)
        - waiting on <0x0000000729443e18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.13/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x0000000729443e18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.13/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.13/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.19ms elapsed=13.80s tid=0x00007f141c1d6800 nid=0x11f4 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.10ms elapsed=13.80s tid=0x00007f141c1d8800 nid=0x11f5 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 cpu=861.62ms elapsed=13.80s tid=0x00007f141c1db000 nid=0x11f6 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=657.77ms elapsed=13.80s tid=0x00007f141c1dd000 nid=0x11f7 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=0.10ms elapsed=13.80s tid=0x00007f141c1df000 nid=0x11f8 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #10 daemon prio=8 os_prio=0 cpu=1.72ms elapsed=13.76s tid=0x00007f141c2b4000 nid=0x11fa in Object.wait()  [0x00007f14007e7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.13/Native Method)
        - waiting on <0x00000007294445a8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@11.0.13/ReferenceQueue.java:155)
        - waiting to re-lock in wait() <0x00000007294445a8> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@11.0.13/CleanerImpl.java:148)
        at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)
        at jdk.internal.misc.InnocuousThread.run(java.base@11.0.13/InnocuousThread.java:134)

"io-compute-1" #11 daemon prio=5 os_prio=0 cpu=2.09ms elapsed=13.51s tid=0x00007f141c87a800 nid=0x11fe waiting on condition  [0x00007f13f5198000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729444ea0> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:301)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:480)

"io-compute-2" #12 daemon prio=5 os_prio=0 cpu=11.62ms elapsed=13.51s tid=0x00007f141c87b800 nid=0x11ff waiting on condition  [0x00007f13f5097000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729444ea0> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:301)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:480)

"io-compute-3" #13 daemon prio=5 os_prio=0 cpu=11.09ms elapsed=13.51s tid=0x00007f141c87d800 nid=0x1200 waiting on condition  [0x00007f13f4f96000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729444ea0> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:301)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:480)

"io-compute-4" #14 daemon prio=5 os_prio=0 cpu=29.54ms elapsed=13.51s tid=0x00007f141c87f000 nid=0x1201 waiting on condition  [0x00007f13f4e95000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729444ea0> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:301)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:480)

"io-compute-5" #15 daemon prio=5 os_prio=0 cpu=557.86ms elapsed=13.51s tid=0x00007f141c881000 nid=0x1202 waiting on condition  [0x00007f13f4d94000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x000000072955d488> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.13/LockSupport.java:234)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.13/AbstractQueuedSynchronizer.java:2123)
        at java.util.concurrent.ArrayBlockingQueue.poll(java.base@11.0.13/ArrayBlockingQueue.java:432)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:329)

"io-compute-6" #18 daemon prio=5 os_prio=0 cpu=194.31ms elapsed=12.73s tid=0x00007f1398003000 nid=0x120d waiting on condition  [0x00007f13f4186000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x0000000729444ea0> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.13/LockSupport.java:194)
        at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:301)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:480)

"io-scheduler" #19 daemon prio=10 os_prio=0 cpu=1.70ms elapsed=12.57s tid=0x00007f13ac008000 nid=0x120e waiting on condition  [0x00007f13971b8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x000000072983af30> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.13/LockSupport.java:234)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.13/AbstractQueuedSynchronizer.java:2123)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.13/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.13/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.13/ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

"fs2-global-tcp-1" #20 daemon prio=5 os_prio=0 cpu=1.41ms elapsed=12.17s tid=0x00007f139843b000 nid=0x1212 runnable  [0x00007f13968b7000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@11.0.13/Native Method)
        at sun.nio.ch.EPollPort$EventHandlerTask.poll(java.base@11.0.13/EPollPort.java:200)
        at sun.nio.ch.EPollPort$EventHandlerTask.run(java.base@11.0.13/EPollPort.java:281)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(java.base@11.0.13/AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

"VM Thread" os_prio=0 cpu=25.48ms elapsed=13.81s tid=0x00007f141c1b5800 nid=0x11f1 runnable  

"GC Thread#0" os_prio=0 cpu=19.81ms elapsed=13.82s tid=0x00007f141c040000 nid=0x11ec runnable  

"GC Thread#1" os_prio=0 cpu=19.58ms elapsed=13.52s tid=0x00007f13e4001000 nid=0x11fb runnable  

"GC Thread#2" os_prio=0 cpu=18.50ms elapsed=13.52s tid=0x00007f13e4002800 nid=0x11fc runnable  

"GC Thread#3" os_prio=0 cpu=20.68ms elapsed=13.52s tid=0x00007f13e4004000 nid=0x11fd runnable  

"G1 Main Marker" os_prio=0 cpu=0.92ms elapsed=13.82s tid=0x00007f141c092000 nid=0x11ed runnable  

"G1 Conc#0" os_prio=0 cpu=17.14ms elapsed=13.82s tid=0x00007f141c093800 nid=0x11ee runnable  

"G1 Refine#0" os_prio=0 cpu=0.26ms elapsed=13.82s tid=0x00007f141c151000 nid=0x11ef runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=2.11ms elapsed=13.82s tid=0x00007f141c152800 nid=0x11f0 runnable  
"VM Periodic Task Thread" os_prio=0 cpu=6.01ms elapsed=13.77s tid=0x00007f141c289800 nid=0x11f9 waiting on condition  

JNI global refs: 16, weak refs: 0

Heap
 garbage-first heap   total 196608K, used 30237K [0x0000000729400000, 0x0000000800000000)
  region size 1024K, 28 young (28672K), 3 survivors (3072K)
 Metaspace       used 42650K, capacity 44100K, committed 44368K, reserved 1087488K
  class space    used 4895K, capacity 5655K, committed 5712K, reserved 1048576K
```

**Comment by armanbilge** [comment]
Raw, unfiltered tracing events:
https://gist.github.com/armanbilge/a6f1922fe6e591a9a36ac59d12e6968f

**Comment by armanbilge** [comment]
Ok, here's another interesting twist :) I've been able to replicate the bug with ember-client.js. The code for ember JVM/JS is shared but the fs2 socket implementations are (obviously) completely different. So this actually suggests it's a bug in ember after all. Here's the fiber dump.

```
cats.effect.IOFiber@100 YIELDING
 
cats.effect.IOFiber@f4 YIELDING
 
cats.effect.IOFiber@f5 YIELDING
 
cats.effect.IOFiber@fa YIELDING
 
cats.effect.IOFiber@111 YIELDING
 
cats.effect.IOFiber@c3 YIELDING
 
cats.effect.IOFiber@109 WAITING
 ├ flatMap @ <jscode>.null.$f_Lfs2_Compiler$Target__flatMap__O__F1__O(https://raw.githubusercontent.com/typelevel/fs2/v3.2.4/core/shared/src/main/scala/fs2/Compiler.scala:162)
 ├ handleErrorWith @ <jscode>.null.$f_Lfs2_Compiler$Target__handleErrorWith__O__F1__O(https://raw.githubusercontent.com/typelevel/fs2/v3.2.4/core/shared/src/main/scala/fs2/Compiler.scala:160)
 ╰ flatMap @ <jscode>.null.$f_Lfs2_Compiler$Target__flatMap__O__F1__O(https://raw.githubusercontent.com/typelevel/fs2/v3.2.4/core/shared/src/main/scala/fs2/Compiler.scala:162)
 
cats.effect.IOFiber@104 WAITING
 
cats.effect.IOFiber@bc WAITING
 
cats.effect.IOFiber@c1 WAITING
 
cats.effect.IOFiber@10a WAITING
 
cats.effect.IOFiber@119 WAITING
 ╰ flatMap @ <jscode>.null.$f_Lfs2_Compiler$Target__flatMap__O__F1__O(https://raw.githubusercontent.com/typelevel/fs2/v3.2.4/core/shared/src/main/scala/fs2/Compiler.scala:162)
 
cats.effect.IOFiber@11a WAITING
 
cats.effect.IOFiber@1f WAITING
 
cats.effect.IOFiber@1e WAITING
 ╰ null.$f_Lcats_effect_IOApp @ TestEmberClientHang$.main(/workspace/sandbox/client.scala:15)
 
cats.effect.IOFiber@11b WAITING
 
cats.effect.IOFiber@121 WAITING
 
cats.effect.IOFiber@105 WAITING
 
cats.effect.IOFiber@108 WAITING
 ╰ flatMap @ <jscode>.null.$f_Lfs2_Compiler$Target__flatMap__O__F1__O(https://raw.githubusercontent.com/typelevel/fs2/v3.2.4/core/shared/src/main/scala/fs2/Compiler.scala:162)
 
cats.effect.IOFiber@20 WAITING
 
cats.effect.IOFiber@22 WAITING
 ├ void @ TestEmberClientHang$.run(/workspace/sandbox/client.scala:16)
 ├ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(/workspace/sandbox/client.js:46800)
 ├ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(/workspace/sandbox/client.js:46800)
 ├ void @ TestEmberClientHang$.run(/workspace/sandbox/client.scala:16)
 ╰ >>$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(/workspace/sandbox/client.js:46800)
 
cats.effect.IOFiber@bb WAITING
 ╰ null.$f_Lcats_effect_IOApp$Simple @ TestEmberClientHang$.run(/workspace/sandbox/client.scala:15)
 
cats.effect.IOFiber@10f WAITING
 
cats.effect.IOFiber@ff WAITING
 
cats.effect.IOFiber@c2 WAITING
 ╰ null.$f_Lcats_effect_IOApp @ TestEmberClientHang$.main(/workspace/sandbox/client.scala:15)
 
cats.effect.IOFiber@122 WAITING
 
cats.effect.IOFiber@110 WAITING
 ╰ null.$f_Lcats_effect_IOApp @ TestEmberClientHang$.main(/workspace/sandbox/client.scala:15)
 
Global: enqueued 6, waiting 21
java.util.concurrent.TimeoutException: Timed Out on EmberClient Header Receive Timeout: 45 seconds
  at null.$p_Lorg_http4s_ember_client_internal_ClientHelpers$__$anonfun$request$5__Lcats_effect_kernel_Async__s_concurrent_duration_Duration__O(https://raw.githubusercontent.com/http4s/http4s/v0.23.8/ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala:161:17)
  at null.<anonymous>(https://raw.githubusercontent.com/http4s/http4s/v0.23.8/ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala:160:45)
  at null.$f_Lcats_effect_IOApp @ TestEmberClientHang$.main(/workspace/sandbox/client.scala:15)
```

**Comment by ChristopherDavenport** [comment]
The only suspect I have presently is timeoutMaybe in the tracing its the only place that ember shows up while in waiting state. One of these two seems to be the factor.

https://gist.github.com/armanbilge/a6f1922fe6e591a9a36ac59d12e6968f#file-gistfile1-txt-L1261-L1262

**Comment by armanbilge** [comment]
```
[error] java.util.concurrent.TimeoutException: Timed Out on EmberClient Header Receive Timeout: 45 seconds
[error] 	at org.http4s.ember.client.internal.ClientHelpers$.$anonfun$request$5(ClientHelpers.scala:163)
[error] 	at defer @ org.http4s.ember.client.internal.ClientHelpers$.$anonfun$request$4(ClientHelpers.scala:161)
[error] 	at main$ @ io.chrisdavenport.testembertimoeut.TestEmberClientHang$.main(Main.scala:11)
[error] 	at void @ io.chrisdavenport.testembertimoeut.TestEmberClientHang$.run(Main.scala:12)
[error] 	at main$ @ io.chrisdavenport.testembertimoeut.TestEmberClientHang$.main(Main.scala:11)
[error] 	at *> @ org.http4s.client.middleware.Retry$.retryLoop$1(Retry.scala:78)
```

**Comment by rossabaker** [comment]
I can't reproduce this on MacOS 12.2 with a netcat server (`nc -l 8765`), on Java 1.8.0_292 or Java 17.0.1.  Is the Ember server also necessary for anyone who is seeing this?

**Comment by armanbilge** [comment]
This is fascinating! @ChristopherDavenport also cannot reproduce it with `netcat` on macOS for _both_ JVM and JS. I was able to reproduce it in ubuntu, and on macOS 10.9 and 11, all with `netcat`.

**Comment by rossabaker** [comment]
I'm running [Chris' repro](https://github.com/ChristopherDavenport/test-ember-timeout) on what I assume is similar hardware, so I'm not too surprised I'm seeing the same result.

**Comment by stephenjudkins** [comment]
The Ember server is not necessary, I first saw it when interacting with the google pub/sub emulator.

Throwing this out there: I am running on an macOS 12.0.1 on an M1 Pro. What CPU/architecture is everyone else using? (Wouldn't be the first time there's been an ARM-specific bug in scala code!)

**Comment by armanbilge** [comment]
All my stuff is intel FTR.

**Comment by stephenjudkins** [comment]
🤔

**Comment by armanbilge** [comment]
@stephenjudkins btw if you're inclined you can check the JS/M1 combination too 😉

**Comment by dj707chen** [comment]
I'm running [Chris' repro](https://github.com/ChristopherDavenport/test-ember-timeout) on old Mac Mini hardware and OSX version, could not reproduce:
x86_64
Mac OS X: 10.15.7

**Comment by ChristopherDavenport** [comment]
Call for help:
1. Clone https://github.com/ChristopherDavenport/test-ember-timeout
2. Startup netcat either with netcat -l -t -p 8765 or nc -l 8765 
3. sbt coreJVM/run
 4. Ctrl-C in the application once it waits at the server
 
 Then report system, arch, jvm used, anything else you . I am wondering what the common denominator is here.

**Comment by stephenjudkins** [comment]
Confirmed that this occurs on my machine, on both JVM and JS. The SBT subprocesses stick around after ctrl+c in both cases.

```
stephen@ivan-iv test-ember-timeout % java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
stephen@ivan-iv test-ember-timeout % uname -a
Darwin ivan-iv.lan 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
```

**Comment by armanbilge** [comment]
> The SBT subprocesses stick around after ctrl+c in both cases.

Sorry, can you clarify what you mean by this?

**Comment by stephenjudkins** [comment]
> Edit: I think I know what you mean. when I ctrl+c, sbt returns me to the console immediately. but jps shows the process is hanging.

Yes

**Comment by armanbilge** [comment]
So for everyone who is unable to reproduce this (@rossabaker, @ChristopherDavenport, @dj707chen), how did you confirm that it's _not_ hanging? jps?

Maybe I'm the only stupid one in the room, but I briefly thought I was unable to reproduce it anymore because ctrl+c returned me to the sbt console immediately.

**Comment by rossabaker** [comment]
Oh, hell.  I drop back to bash -- not the sbt shell -- but the forked `TestEmberClientHang` is still running.  I didn't expect the forked JVM to outlive the sbt that spawned it.

**Comment by armanbilge** [comment]
Yup. I have a suspicion everyone is reproducing this actually. Nothing weird going on here, except sbt :)

**Comment by ChristopherDavenport** [comment]
Can someone write a script so I can see this directly? I'm sure its relatively straightforward from the above.

**Comment by stephenjudkins** [comment]
I think this might be possible to reproduce in a pure-scala context without any processes or signals, I might take a crack of that if I get a minute

**Comment by ChristopherDavenport** [comment]
Alright, I'm fairly confident that #6085 fixes this. Steps to reproduce. 

1. Pull down the branch from 6085 and `sbt publishLocal`
2. Pull down https://github.com/ChristopherDavenport/test-ember-timeout
3. Run either `./js-example.sh` or `./java-example.sh`. This will reproduce on current 0.23, and return after 2 seconds with this new branch. You may need to replace the netcat command with the nc command provided by switching the commented lines in the script.


@stephenjudkins  @armanbilge  Can you confirm this fixes for you?

**Comment by stephenjudkins** [comment]
I can confirm that this fixes it for me!

FWIW, the `nc` version of the test doesn't work and I had to do ` brew install netcat` on macOS to get both the fixed and unfixed versions working as expected without throwing exceptions.

I'd like to express my gratitude for everyone who worked hard to reproduce/investigate/fix this issue

**Comment by armanbilge** [comment]
Yes, @ChristopherDavenport zeroed-in on it real fast once he reproduced :)

Let the next cancellation bug be so interesting! 😆 

![](https://imgs.xkcd.com/comics/zealous_autoconfig.png)
