### ISSUE TITLE
MimeDB-initialization deadlock

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#6242]
This has been plaguing our builds since https://github.com/http4s/http4s/pull/6211, but Ross noticed it first in https://github.com/http4s/http4s/pull/6238#issuecomment-1088035957.

I was able to get a `jstack` dump that reveals the deadlock relating to `lazy val` intialization. Would appreciate some help solving it :)

https://gist.github.com/armanbilge/a1759c829bb579484a9e1542dc0443c1

**Comment by armanbilge** [comment]
In https://github.com/http4s/http4s/pull/6211 I made a `val` into a `lazy val`. One fix would be to split that file across JVM/JS, revert the change on JVM and keep it on JS.

Note that previously all these `lazy val`s were kind of pointless on JVM: because of that `val` which I changed, the entire MimeDB was being initialized at startup. This may or may not have been a big deal.

So the change in https://github.com/http4s/http4s/pull/6211 was kind of a fix for that, except now since things are properly lazily initialized we get into deadlock territory.

**Comment by armanbilge** [comment]
Zeroing in, this deadlock seems to occur when one thread access `MediaType.application.json` while another accesses `MediaType.all`. Dare I point out, this was a pre-existing problem that we weren't observing since the MimeDB was being forced to initialize in its entirety when loading first loading the `MediaType` class anyway?

```
"io-compute-2":
	at org.http4s.MediaType$.application_parts$lzycompute$1(MediaType.scala:252)
	- waiting to lock <0x0000000754d4de80> (a org.http4s.MediaType$)
	at org.http4s.MediaType$.application_parts(MediaType.scala:252)
	at org.http4s.MimeDB$application$.org$http4s$MimeDB$application_parts$application_0$$$outer(MimeDB.scala:6207)
	at org.http4s.MimeDB$application_parts$application_0.json(MimeDB.scala:376)
	at org.http4s.MimeDB$application_parts$application_0.json$(MimeDB.scala:375)
	at org.http4s.MimeDB$application$.json$lzycompute(MimeDB.scala:6207)
	- locked <0x000000075400e878> (a org.http4s.MimeDB$application$)
	at org.http4s.MimeDB$application$.json(MimeDB.scala:6207)
```

```
"io-compute-4":
	at org.http4s.MimeDB$application$.all$lzycompute(MimeDB.scala:6212)
	- waiting to lock <0x000000075400e878> (a org.http4s.MimeDB$application$)
	at org.http4s.MimeDB$application$.all(MimeDB.scala:6212)
	at org.http4s.MimeDB.allMediaTypes(MimeDB.scala:22)
	at org.http4s.MimeDB.allMediaTypes$(MimeDB.scala:21)
	at org.http4s.MediaType$.allMediaTypes$lzycompute(MediaType.scala:252)
	- locked <0x0000000754d4de80> (a org.http4s.MediaType$)
	at org.http4s.MediaType$.allMediaTypes(MediaType.scala:252)
	at org.http4s.MediaType$.all$lzycompute(MediaType.scala:267)
	- locked <0x0000000754d4de80> (a org.http4s.MediaType$)
	at org.http4s.MediaType$.all(MediaType.scala:266)
	at org.http4s.MediaType$.getMediaType(MediaType.scala:303)
```

**Comment by rossabaker** [comment]
Would it be possible to do a null-init pattern in a couple strategic places, like perhaps `allMediaTypes`?

**Comment by armanbilge** [comment]
Hmm, maybe, but I'm not sure. It's still not 100% clear to me how initializing `all` and `json` concurrently to get tangled up with each other. `all` depends on `json`, but not the other way around.

**Comment by rossabaker** [comment]
Inner objects act just like lazy vals, don't they?  `json` locks `application`, which initalizes `application_parts`, which locks `MimeDB`.  And `MimeDB` was locked by `all`.

**Comment by armanbilge** [comment]
Do they? So couldn't this happen even if you try and access two mime type constants at the same time?

**Comment by armanbilge** [comment]
Oh, I think I'm wrapping my head around it. Ok, yeah I see how some strategically placed null-inits could do the trick.
