### ISSUE TITLE
tomcat-8.5: java.lang.NoClassDefFoundError: javax/security/auth/message/config/RegistrationListener

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#639]
This is related to JASPIC.  Is anybody trying to use this?  Has anybody solved this problem yet?

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax/security/auth/message/config/RegistrationListener
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:913)
    at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1405)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1395)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javax/security/auth/message/config/RegistrationListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.catalina.startup.Tomcat$FixContextListener.lifecycleEvent(Tomcat.java:908)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:401)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:104)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:141)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: javax.security.auth.message.config.RegistrationListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 33 more
```

**Comment by basil** [comment]
The tarball distribution of Tomcat 8.5 has a new `jaspic-api.jar` file, but that JAR isn't published on Maven Central and it's not listed as a dependency of the Tomcat 8.5.x JARs on Maven Central. This looks like an upstream Tomcat build issue.

**Comment by rossabaker** [comment]
I think this might [finally be fixed](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.tomcat%22%20AND%20a%3A%22tomcat-jaspic-api%22), if someone wants to give it a try.

**Comment by rekhaMokshank** [comment]
I still see this issue:

04-Jul-2017 07:25:26.344 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.authenticatorConfig Cannot instantiate an authenticator of class [org.apache.catalina.authenticator.NonLoginAuthenticator]
 java.lang.NoClassDefFoundError: javax/security/auth/message/config/RegistrationListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)


Has anyone resolved it

**Comment by rossabaker** [comment]
Is tomcat-jaspic-api pulled in as a transitive dependency?

If not, what happens if you explicitly add:
`libraryDependencies += "org.apache.tomcat" % "tomcat-jaspic-api" % "8.5.16"`

**Comment by ChristopherDavenport** [comment]
If this fixes it, it can probably be integrated into the `tomcat` project.

**Comment by rossabaker** [comment]
It's a compile-scoped dependency of tomcat-catalina, so it would be very surprising for it to not be on the classpath. :thinking:

Is this a war-based deployment or an embedded Tomcat server?

**Comment by rossabaker** [comment]
If anyone can reproduce this on Tomcat 9, please reopen.
