### ISSUE TITLE
Using the client to decode Server Sent Events misbehaves on both JVM and JS

### ISSUE THREAD

**Issue by Koroeskohr** [http4s/http4s#6694]
Re: https://discord.com/channels/632277896739946517/632286375311573032/1020733581703786608

Repro: https://gist.github.com/Koroeskohr/facf22a21bb955d1df6cac384ac811bc
`scala-cli test https://gist.github.com/Koroeskohr/facf22a21bb955d1df6cac384ac811bc`

As discussed with @armanbilge, we observed on both JVM and JS two different wrong behaviours, the JVM will throw a `ClosedChannelException`, the JS runtime will hang after the first event, when the source advertises an event every 2 seconds, observable through:
```$ curl -N --location --compressed --request GET 'https://sse.dev/test' --header 'Accept: text/event-stream'```

**Comment by armanbilge** [comment]
Here's my JS reproducer. I inlined the `EventStream` decoder and added a `.debugChunks()`. It seems that only one chunk is arriving before the hang, which makes me suspect ember.

<details>

```scala
//> using lib "org.scalameta::munit::1.0.0-M6"
//> using lib "org.typelevel::munit-cats-effect::2.0.0-M3"
//> using lib "org.http4s::http4s-ember-client::0.23.16"
//> using lib "org.http4s::http4s-circe::0.23.16"
//> using lib "org.http4s::http4s-dsl::0.23.16"
//> using lib "io.circe::circe-generic::0.14.3"
//> using platform "js"
//> using jsModuleKind "common"

import munit.CatsEffectSuite
import fs2.Stream
import org.http4s.ember.client.EmberClientBuilder
import cats._
import cats.effect._
import org.http4s._
import org.http4s.implicits._
import org.http4s.Method._
import org.http4s.client.dsl.io._

class Repro extends CatsEffectSuite {

  def eventStream[F[_]: Applicative]: EntityDecoder[F, EventStream[F]] =
    EntityDecoder.decodeBy(MediaType.`text/event-stream`) { msg =>
      DecodeResult.successT(msg.body.debugChunks().through(ServerSentEvent.decoder))
    }

  test("repro") {
    val io = Stream.resource(EmberClientBuilder.default[IO].build).flatMap { client =>
      val req: Request[IO] = GET(uri"https://sse.dev/test")

      Stream.eval(client.expect[EventStream[IO]](req)(eventStream)).flatMap { eventStream => 
        eventStream.debug()
      }
    }.compile.drain
    
    assertIO(io, ())
  }
}
```

</details>

Which gets

```
Repro:
Chunk(100, 97, 116, 97, 58, 32, 123, 34, 116, 101, 115, 116, 105, 110, 103, 34, 58, 116, 114, 117, 101, 44, 34, 115, 115, 101, 95, 100, 101, 118, 34, 58, 34, 105, 115, 32, 103, 114, 101, 97, 116, 34, 44, 34, 109, 115, 103, 34, 58, 34, 73, 116, 32, 119, 111, 114, 107, 115, 33, 34, 44, 34, 110, 111, 119, 34, 58, 49, 54, 54, 51, 52, 51, 53, 50, 55, 57, 51, 55, 53, 125, 10, 10)
ServerSentEvent(Some({"testing":true,"sse_dev":"is great","msg":"It works!","now":1663435279375}),None,None,None)
==> X Repro.repro 30.20s java.util.concurrent.TimeoutException: test timed out after 30 seconds
```
---

With some pain I got the Scala Native version working as well, which got me this.
```
Repro:
ServerSentEvent(Some({"testing":true,"sse_dev":"is great","msg":"It works!","now":1663434391243}),None,None,None)
==> X Repro.repro 0.80s fs2.io.net.tls.S2nException: cannot resize a static stuffer
```

I'm not sure what that means, but possibly that ember is somehow giving bad input to the TLS stuff? No idea.

**Comment by Koroeskohr** [comment]
Reproducing with http4s-jdk-http-client

<details>

```scala
//> using lib "org.scalameta::munit::1.0.0-M6"
//> using lib "org.typelevel::munit-cats-effect::2.0.0-M3"
//> using lib "org.http4s::http4s-jdk-http-client::1.0.0-M5"
//> using lib "org.http4s::http4s-circe::1.0.0-M35"
//> using lib "org.http4s::http4s-dsl::1.0.0-M35"
//> using lib "io.circe::circe-generic::0.14.2"
//> using scala "2.13.8"

import munit.CatsEffectSuite
import fs2.Stream
import org.http4s.jdkhttpclient.JdkHttpClient
import cats.effect.IO
import org.http4s._
import org.http4s.implicits._
import org.http4s.Method._
import org.http4s.client.dsl.io._

class Repro extends CatsEffectSuite {

  test("repro") {
    val io = Stream.resource(JdkHttpClient.simple[IO]).flatMap { client =>
      val req: Request[IO] = GET(uri"https://sse.dev/test")

      Stream.eval(client.expect[EventStream[IO]](req)).flatMap { eventStream => 
        eventStream.debug()
      }
    }.compile.drain
    
    assertIO(io, ())
  }
}
```

</details>

Output:

<details>

```
repro$Repro:
==> X repro$Repro.repro  1.016s java.lang.IllegalStateException: This publisher has already one subscriber
    at jdk.internal.net.http.ResponseSubscribers$PublishingBodySubscriber.subscribe(ResponseSubscribers.java:973)
    at org.reactivestreams.FlowAdapters$ReactivePublisherFromFlow.subscribe(FlowAdapters.java:348)
    at org.http4s.jdkhttpclient.JdkHttpClient$.$anonfun$apply$13(JdkHttpClient.scala:219)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:929)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:929)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at get @ fs2.internal.Scope.openScope(Scope.scala:281)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
    at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:929)
```
</details>

**Comment by armanbilge** [comment]
.... and it works with the Node.js built-in client. 🤯 

<details>

```scala
//> using lib "org.scalameta::munit::1.0.0-M6"
//> using lib "org.typelevel::munit-cats-effect::2.0.0-M3"
//> using lib "org.http4s::http4s-ember-client::0.23.16"
//> using lib "org.http4s::http4s-circe::0.23.16"
//> using lib "org.http4s::http4s-dsl::0.23.16"
//> using lib "io.circe::circe-generic::0.14.3"
//> using platform "js"
//> using jsModuleKind "common"

package org.http4s.client

import munit.CatsEffectSuite
import fs2.Stream
import org.http4s.ember.client.EmberClientBuilder
import cats._
import cats.effect._
import org.http4s._
import org.http4s.implicits._
import org.http4s.Method._
import org.http4s.client.dsl.io._

class Repro extends CatsEffectSuite {

  def eventStream[F[_]: Applicative]: EntityDecoder[F, EventStream[F]] =
    EntityDecoder.decodeBy(MediaType.`text/event-stream`) { msg =>
      DecodeResult.successT(msg.body.debugChunks().through(ServerSentEvent.decoder))
    }

  test("repro") {
    val io = Stream.resource(NodeJSClientBuilder[IO].resource).flatMap { client =>
      val req: Request[IO] = GET(uri"https://sse.dev/test")

      Stream.eval(client.expect[EventStream[IO]](req)(eventStream)).flatMap { eventStream => 
        eventStream.debug()
      }
    }.compile.drain
    
    assertIO(io, ())
  }
}
```

</details>

It emits the event every two seconds exactly as expected.

So all of our other clients are broken 😛

**Comment by armanbilge** [comment]
@Koroeskohr thanks, I tried running your repro, but I'm not sure if I was able to reproduce. For this test:

```scala
  // still fails
  s("repro byte".only) {
```

You say that it still fails. Can you clarify what you mean by that? For me it printed out chunks periodically for 30 seconds until the test timeout. Which is the expected behavior I believe.

**Comment by Koroeskohr** [comment]
ah, that's running the wrong test probably, I was not aware of `"".only` and added a function (`s`) to quickly skip over tests I didnt want to run while testing, you're likely running `"repro byte no expect"`

**Comment by armanbilge** [comment]
Oh, d'oh 😂 let me try that again

**Comment by armanbilge** [comment]
ok thanks I just reproduced! nice work!

**Comment by armanbilge** [comment]
Ah, I understood the problem. Crap 😕 there was a reason this didn't exist, and now I know why. My PR https://github.com/http4s/http4s/pull/6413 was a mistake and we're going to have to deprecate this as broken.

The problem is quite simple: `expect` cannot be used with streaming results because `expect` does not return a `Resource`. It returns an `F[_]` and therefore must consume the entirety of the entity body before returning. This is incompatible with the notion of streaming the result.

Thanks for your minimization efforts, it took an embarrassing amount of further minimization to realize what is actually fairly obvious 🤦
