### ISSUE TITLE
Broken Pipe in Ember Server when using http2

### ISSUE THREAD

**Issue by zAPFy** [http4s/http4s#7014]
scala: 2.13.10
cats-effect: 3.4.8
http4s: 0.23.18

When running Ember server with http2, closing a long running request from client side will logg while app keeps running:
```java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:60)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:602)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$write$1(SocketPlatform.scala:136)
	at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:130)
	at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:140)
	at modify @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:83)
	at flatten$extension @ org.http4s.ember.server.internal.Shutdown$$anon$1.<init>(Shutdown.scala:71)
	at apply @ org.http4s.ember.server.EmberServerBuilder.$anonfun$build$2(EmberServerBuilder.scala:182)
	at acquire @ fs2.Stream$NestedStreamOps$.$anonfun$parJoin$19(Stream.scala:4238)
```

Steps to reproduce: 
```
import cats.effect.{ExitCode, IO, IOApp}
import com.comcast.ip4s.IpLiteralSyntax
import fs2._
import org.http4s.dsl.Http4sDsl
import org.http4s.ember.server.EmberServerBuilder
import org.http4s.{HttpApp, ServerSentEvent}

import scala.concurrent.duration.DurationInt

object SSETest extends IOApp with Http4sDsl[IO] {
  private val stream =
    Stream.fixedRate[IO](3.seconds).as(ServerSentEvent(data = Some("hi"), eventType = Some("greeting")))
  private val httpApp = HttpApp.liftF(Ok(stream))

  override def run(args: List[String]): IO[ExitCode] =
    EmberServerBuilder
      .default[IO]
      .withHttp2
      .withPort(port"9876")
      .withHttpApp(httpApp)
      .build
      .use(_ => IO.never.as(ExitCode.Success))
}
```
then `curl --http2 http://localhost:9876` and then cancel with crtl+C

Note: if disabling http2, either on client or server side, no error is logged. 
Note2: Blaze server does not seem to have this issue.

Not sure if related to #6219

**Comment by armanbilge** [comment]
Thanks for reporting the issue, with the excellent reproducer! Just to clarify, are you concerned about:

1. The `Broken pipe` error itself? When you do ctrl+C in curl you are indeed breaking the pipe by terminating the connection, so it's a legitimate error.
2. The fact that this error is being logged. Probably Blaze is silencing it.

I'm looking at (2) to make sure that the error reporting is configurable.

**Comment by armanbilge** [comment]
Adding this to your `IOApp` appears to silence it.

```scala
override def reportFailure(err: Throwable) = IO.unit
```

**Comment by zAPFy** [comment]
@armanbilge was mostly the fact that it was logged, it might be a legit error but should probably be caught and logged at a lower logg level, as per you PR.
