### ISSUE TITLE
Deprecate/discourage global circe codecs

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s#7054]
Specifically, I think we should deprecate/discourage the imports that promise an http4s codec for anything with a Circe codec.

As a motivating case: one frequently recurring issue I see is that `expect[Unit]` stops behaving as expected with the Circe import in scope, because Circe promises a Json codec for `Unit` as `{}` which "overrides" the http4s "void" codec.

Instead, users can create implicit entity codecs for their dataclasses.

**Comment by ChristopherDavenport** [comment]
I dont know I agree with this, that's a special import and when that's what you are using its absolutely a lifesaver. Can make writing clients for json services massively easier and free of boilerplate.

**Comment by rossabaker** [comment]
```mermaid
flowchart TD
    A{Is there more to life than JSON?}
    A -->|No| B[That import is handy!]
    A -->|Yes| C[That import is brutish!]
```

**Comment by bplommer** [comment]
Your motivating case seems to raise the question of whether `expect[Unit]` is actually an appropriate way to express "I don't care about the value". In particular, it's quite confusing that http4s interprets `Unit` that way but Circe interprets it specifically as "I want something empty or null". I kind of want to suggest that `Any` would express "I don't care" better - it could still always decode as `()`, though I get that this would feel weird.

**Comment by armanbilge** [comment]
@bplommer it's not just `Unit` :) someone else on Discord just butted heads with this for `String`.

```scala
//> using lib "org.http4s::http4s-circe::0.23.18"

import cats.effect._
import org.http4s._
import org.http4s.circe.CirceEntityDecoder._

object App extends IOApp.Simple {
  def run = {
    Response[IO]().withEntity("hello").as[String].void
  }
}
```

```
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
        at org.http4s.MalformedMessageBodyFailure$.apply(MessageFailure.scala:107)
        at org.http4s.circe.CirceInstances$.defaultCirceParseError$$anonfun$1(CirceInstances.scala:265)
        at org.http4s.circe.CirceInstances.jsonDecoderByteBufferImpl$$anonfun$1$$anonfun$1(CirceInstances.scala:60)
        at cats.syntax.EitherOps$.leftMap$extension(either.scala:193)
        at org.http4s.circe.CirceInstances.jsonDecoderByteBufferImpl$$anonfun$1(CirceInstances.scala:60)
        at scala.util.Either.flatMap(Either.scala:352)
        at cats.data.EitherT.subflatMap$$anonfun$1(EitherT.scala:456)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at rethrow$extension @ fs2.Compiler$Target.compile$$anonfun$1(Compiler.scala:157)
        at run$ @ App$.run(test.scala:7)
        at get @ fs2.internal.Scope.openScope(Scope.scala:281)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Pull$.goCloseScope$1$$anonfun$1$$anonfun$3(Pull.scala:1215)
        at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:227)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
Caused by: io.circe.ParsingFailure: expected json value got 'hello' (line 1, column 1)
```

**Comment by rossabaker** [comment]
These problems occur only when you begin to think of HTTP as more than JSON with Front Matter.  A lot of apps don't!  It's a documentation issue: "import if and only if your entire soul is snugly nestled in curly braces."

**Comment by bplommer** [comment]
> These problems occur only when you begin to think of HTTP as more than JSON with Front Matter.

That's the case with `String`, not with `Unit`. I frequently use `expect[Unit]` with endpoints that return arbitrary JSON that I don't care about, so I'm surprised I haven't run into this problem.

I kind of want to suggest that the circe implicits should have a lower priority than the default `Unit` and `String` ones, but I'm not sure if that's possible?

**Comment by armanbilge** [comment]
> I frequently use `expect[Unit]` with endpoints that return arbitrary JSON that I don't care about, so I'm surprised I haven't run into this problem.

Right, they are still returning JSON, so using a JSON decoder for `Unit` is fine actually. The issue is when the endpoint is _not_ returning JSON e.g. a 204 no-content.

**Comment by bplommer** [comment]
> Right, they are still returning JSON, so using a JSON decoder for `Unit` is fine actually (note you are paying the cost of parsing for no good reason). The issue is when the endpoint is _not_ returning JSON e.g. a 204 no-content.

The Circe [Unit] decoder specifically expects `{}`, `[]` or `null`:
https://github.com/circe/circe/blob/172c9a4d9e14270bab59700d9ffe439462c23db7/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L622-L630

**Comment by bplommer** [comment]
> Hmm, yes, I think we can do this actually 🤔 we'd have to re-expose these specific implicits on the `CirceEntity{Encoder,Decoder}` objects and put the derived codecs at a lower priority. WDYT?

I'm not sure. This would still be a footgun, just in the other direction.

For `String` I'm actually wondering if we should go the other way and deprecate/discourage implicit use of `EntityDecoder.text` - so instead of `expect[String]` tell people to use `expect(EntityDecoder.text)`. (The deprecation cycle would require making `EntityDecoder.text` non-implicit and introducing a new, deprecated implicit version - that seems ok.).  I can't imagine raw text is actually a very common message format in production scenarios, so do we really want to privilege it the way we currently do?

For `Unit` I'd tend to go ahead with having the default `Unit` codecs be higher priority than the Circe ones, mainly because I don't like the circe ones and would prefer they don't exist. But I also still think `expect[Unit]` is an odd way to express "I don't care" - WDYT about adding variants of the `expect` methods called `ignore` or `discard` that don't take a type parameter?

**Comment by armanbilge** [comment]
> This would still be a footgun, just in the other direction.

Agreed to that :)

What's the issue with `String`? Are there really JSON endpoints in practice that return a raw `String` not in an object? This seems even less common :)

---

> we should go the other way and deprecate/discourage implicit

I mean, this is a good general solution to this entire mess 😁 

---

> WDYT about adding variants of the `expect` methods called `ignore` or `discard` that don't take a type parameter?

I mean, that will solve it for that specific usecase on client, but it wouldn't solve my `.as` example above. It also wouldn't solve it on the server side.

**Comment by bplommer** [comment]
> What's the issue with `String`? Are there really JSON endpoints in practice that return a raw `String` not in an object? This seems even less common :)

Good point, I don't think it's something I can remember seeing. It feels weird to end up with the raw text codecs in scope for `String` when json ones are in scope for other types, but maybe it's not an actual problem.

> > WDYT about adding variants of the `expect` methods called `ignore` or `discard` that don't take a type parameter?
> 
> I mean, that will solve it for that specific usecase on client, but it wouldn't solve my `.as` example above. It also wouldn't solve it on the server side.

What's the use case for `.as[Unit]`? And what would the problem look like on the server side - calling `.withEntity(())` on a `Response`? I'd want to strongly encourage doing `.withEmptyBody` instead in that case.

**Comment by armanbilge** [comment]
> json ones are in scope for other types, but maybe it's not an actual problem.

Sending "raw" JSON primitives over the wire in general seems strange (string, numbers, whatever). I'd expect them to be encapsulated as objects or arrays.

---

> Given that, what's the use case for `.as[Unit]`

See https://github.com/http4s/http4s/issues/4935#issuecomment-1279647970. If a server is expecting a request with no body, it must still drain the body with `.as[Unit]`.

However on second, I see your point: if we can count on servers and clients to automatically drain unconsumed bodies (not in 0.23, but in 1.0) then `.as[Unit]` should never be needed: users can simply ignore the body.

**Comment by satorg** [comment]
> Sending "raw" JSON primitives over the wire in general seems strange (string, numbers, whatever). I'd expect them to be encapsulated as objects or arrays.

I agree with that one. I can image that someone can use DSL to build a response like this: `Ok("hello, I'm done here")`, but in most cases (I believe) it is expected to be just a regular text string returned, but not a JSON string. And I think that pretty much same logic is applicable to `expect[String]` or whatever.

So yeah, I think it would be nice to have JSON-based entity codecs de-prioritized for primitive values.

**Comment by rossabaker** [comment]
The only top-level values that are valid for `application/json` are arrays and objects (RFC4627), so while there's justification to hide string / number / boolean / null, it's gets bonkers fast.

- Circe's String is invalid by itself, so we hide it.  Alright.
- We'd be hiding Unit because ... we don't like it?  We asked for Circe's model with this import, and it's valid.  Fine, new rule, we won't shadow core encoders.
- What of the myriad types that have a Circe encoder to the forbidden values but no core encoder to hide it with?  (Long, BigDecimal, Char, None...)  If we don't deal with that, we lose the moral high ground of the spec.
- What about custom Circe encoders that encode to a forbidden value?  We can't even detect those.

This all seems so confusing vs. "opt into the Circe bridge, get the Circe codecs; play stupid games with them, win stupid prizes."

**Comment by bplommer** [comment]
> The only top-level values that are valid for `application/json` are arrays and objects (RFC4627)

That makes me happier about hiding Circe's string encoder (it removes a reason not to), but I don't see it as the reason to do so. The reason for doing so can be stated very concisely:

> Fine, new rule, we won't shadow core encoders.

This is a good general rule - having imported implicits silently change the behaviour of already-compiling code tends to be poor UX. I think this in itself is a simple, non-confusing explanation. However...

> We'd be hiding Unit because ... we don't like it? We asked for Circe's model with this import, and it's valid.

RFC compliance aside, I see the issue with `Unit` as being much deeper than the one with `String`. The circe codec changes the wire format, but it keeps the semantic meaning the same - "an arbitrary bit of unstructured text". With `Unit`, it completely changes the semantic meaning: in http4s, `Unit` doesn't represent message content at all, but rather has the meta-level meaning "I don't care about the content of the message body, but I want to drain it". That's a concern completely orthogonal to choice of wire formats, which makes it really surprising that the circe imports change that meaning. 

Actually the more I think about this, the more it makes me think we should deprecate this current meta-level meaning of `Unit` - in addition to `.ignore` or `.discard` on `Client`, I'd suggest adding `.drain` on `Message` as a replacement for `.as[Unit]`. What we have at the moment is kind of the reverse of a leaky abstraction (a leaky concretion?) - we're telling people to use encoding/decoding facilities in a particular way to achieve a particular result, but we can't actually guarantee it will have that result.

> This all seems so confusing vs. "opt into the Circe bridge, get the Circe codecs; play stupid games with them, win stupid prizes."

I get that you're being flippant here, but I do think the circe imports are a useful facility to have and we should try to make them as helpful as possible in real-life use cases. In the overwhelming majority of cases, this would be best achieved by prioritising the default codecs.

**Comment by armanbilge** [comment]
For RFC compliance, we can replace `Encoder` with `Encoder.AsRoot`, this will enforce that it is encoding either an array or an object I believe. Unfortunately there is no equivalent on the `Decoder` side AFAIK.

https://github.com/http4s/http4s/blob/43efe6d466d9774d66806fc687895cc8e2845bb8/circe/src/main/scala/org/http4s/circe/CirceEntityEncoder.scala#L26

Regarding `Unit` ... I think I am coming around to @bplommer's point. We could also have a bespoke e.g. `object Drain` in the style of Skunk's [`Void`](https://javadoc.io/doc/org.tpolecat/skunk-core_2.12/latest/skunk/Void.html).

**Comment by bplommer** [comment]
> For RFC compliance, we can replace `Encoder` with[ `Encoder.AsRoot`](https://circe.github.io/circe/api/io/circe/Encoder$$AsRoot.html)

Wouldn’t that require user code to narrow static types of Circe encoders to `Encoder.AsRoot`? That seems quite disruptive and I’m not convinced it would be worth the extra hassle.

> Regarding `Unit` ... I think I am coming around to @bplommer's point. We could also have a bespoke e.g. `object Drain` in the style of Skunk's [`Void`](https://javadoc.io/doc/org.tpolecat/skunk-core_2.12/latest/skunk/Void.html).

I’d be fine with this option. I don’t like `Drain` as a name though - `expect[Drain]` sounds weird. I’m sure we can come up with something better though - my main reservation about this is that it would require an extra import.

**Comment by satorg** [comment]
<sub>Just thinking aloud and perhaps I'm going to say something stupid but anyway...</sub>

Perhaps it might make sense simply to get rid of default `EntityEncoder` and `EntityDecoder` for `String` and `Unit` (only).
Currently those are available by default because they're located in `EntityEncoder` / `EntityDecoder` companion objects.

I could imagine extracting them into some separate package/object and thus require importing them explicitly, only if a user needs them. This way we would let users to avoid the ambiguity: i.e. a user has to either import the default codecs or the circe's ones.

Note that we don't have to move _all_ the default encoders/decoders into separate objects. I think, it should be just codecs for `String` and `Units`.

**Comment by fredshonorio** [comment]
With some slight  indirection (compile-time only, i think?):
`superExpect[IRealyWantJson, Blorp]`
`http4s-circe` would provide `SuperEntityDecoder[IRealyWantJson, F, A]`
The same could be done for `EntityEncoder`.

**Comment by fredshonorio** [comment]
@bplommer sorry, that was too obtuse. I mean something like this:

``` scala
//> using scala "2.13.10"
//> using lib "org.http4s::http4s-dsl:1.0.0-M37"
//> using lib "org.http4s::http4s-circe:1.0.0-M37"
//> using lib "org.http4s::http4s-client:1.0.0-M37"

import cats.effect._
import cats.syntax.all._
import org.http4s.HttpRoutes
import org.http4s.client.Client
import org.http4s.circe._
import org.http4s._
import org.http4s.dsl.io._
import org.http4s.implicits._
import io.circe.Decoder

object Main extends IOApp.Simple {
  sealed trait PlainText
  sealed trait Json

  trait Format[F[_], FMT, A] {
    def decoder: EntityDecoder[F, A]
  }

  implicit def circeFmt[A](implicit e: Decoder[A]) = new Format[IO, Json, A] {
    def decoder: EntityDecoder[IO, A] = jsonOf
  }

  implicit def stringFmt[A](implicit e: Decoder[A]) = new Format[IO, PlainText, String] {
    def decoder: EntityDecoder[IO, String] = org.http4s.EntityDecoder.text[IO]
  }

  implicit class Ops(c: Client[IO]) {
    def expectFormat[F, A](uri: Uri)(implicit f: Format[IO, F, A]): IO[A] =
      c.expect(uri)(f.decoder)
  }

  val c = Client.fromHttpApp(HttpRoutes.of[IO] { case _ => Ok("\"a\"") }.orNotFound)

  def run: IO[Unit] =
    c.expectFormat[Json, String](uri"/").flatMap(IO.println(_)) >>
      c.expectFormat[PlainText, String](uri"/").flatMap(IO.println(_))
}
```
Writing this out fully I realised that each of the inbuilt decoders would need to be "wrapped" like this, which is annoying.
