### ISSUE TITLE
Getting None.get when providing an invalid host or port

### ISSUE THREAD

**Issue by keuhdall** [http4s/http4s#7108]
I tried creating a function to create URIs looking like this:
```scala
    private def getUri(path: String*): F[Uri] =
      UriTemplate(
        scheme = Uri.Scheme.https.some,
        authority = Uri.Authority(host = Uri.RegName(ctx.provider)).some,
        path = path.toList.map(PathElm.apply)
      ).toUriIfPossible.liftTo[F].adaptErr(_ => InvalidUri)
```
When executing my code I end up with following stacktrace:
```
java.util.NoSuchElementException: None.get
      at scala.None$.get(Option.scala:627)
      at scala.None$.get(Option.scala:626)
      at org.http4s.ember.client.internal.ClientHelpers$.getAddress$$anonfun$1(ClientHelpers.scala:220)
      at delay @ org.http4s.ember.client.internal.ClientHelpers$.getAddress(ClientHelpers.scala:220)
      at map @ org.http4s.ember.client.EmberConnection$.apply$$anonfun$1(EmberConnection.scala:46)
      at of$extension @ org.typelevel.keypool.KeyPool$Builder.build(KeyPool.scala:373)
      at flatMap @ org.http4s.ember.client.EmberConnection$.apply(EmberConnection.scala:46)
      at <* @ org.http4s.ember.client.EmberClientBuilder.$anonfun$1(EmberClientBuilder.scala:246)
```
as I'm not failing at the URI creation (I'm getting a `Success`), but later on in the process.
I'm using http4s version 1.0.0-M39 but the issue seems to be on 0.23 as well: https://github.com/http4s/http4s/blob/series/0.23/ember-client/shared/src/main/scala/org/http4s/ember/client/internal/ClientHelpers.scala#L246

**Comment by ChristopherDavenport** [comment]
Did you want a more specific error? The host type of ip4s does recognize the host which is how we reference who we call. 

Or is Uri too permissive and we need a secondary layer of validation to confirm it's a valid Uri for a backend.

**Comment by keuhdall** [comment]
To give you some more context on that issue I initially had misconfigured the value for `ctx.provider` to `https://someapi.com/oauth/token` instead of just `someapi.com` in the first code snippet, resulting in an uri being `https://https://someapi.com/oauth/token/oauth/token`.

With that, `.toUriIfPossible.liftTo[F].adaptErr(_ => InvalidUri)` wouldn't fail, and I would instead get the None.get error later on shown above, which I found somewhat misleading.

I don't really have a strong opinion on whether the change should be more towards the uri validation or raising a custom error instead of performing None.get, or both.
