### ISSUE TITLE
Handling of faults tends to lead to duplication with external handling and over-verbose logging

### ISSUE THREAD

**Issue by SteveDraper** [http4s/http4s#728]
Exceptions thrown by various Java functions called rom HTTP4s are (at least sometimes) handled with full logging of the exception (including stack dumps) within HTTPS, but then still propagated out, where the condition needs to be also handled by the calling code.

This has two impacts:

1) Some logical duplication of effort between HTTP4S internal code, and external calling code
2) Inability to control logging behavior in a calling service/app

Suggestion is that internal (to HTTP4s) handling that propagates the fault to the caller (see example below) should not log (or at least not log verbosely with full stack information), since the caller anyway has to handle the fault.

Known example is when the `PoolManager` attempts to establish a connection to  server that is not contactable.  This results in a Java exception with the stack dump below, and then propagates the same exception in the resulting `Task[Response]` the client ultimately surfaces:

```
java.nio.channels.UnresolvedAddressException: null
           at sun.nio.ch.Net.checkAddress(Net.java:101) ~[na:1.8.0_102]
           at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:301) ~[na:1.8.0_102]
           at sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:209) ~[na:1.8.0_102]
           at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:27) ~[org.http4s.blaze-core_2.11-0.11.0.jar:0.11.0]
           at org.http4s.client.blaze.Http1Support.org$http4s$client$blaze$Http1Support$$buildPipeline(Http1Support.scala:72) ~[org.http4s.http4s-blaze-client_2.11-0.12.4.jar:0.12.4]
           at org.http4s.client.blaze.Http1Support$$anonfun$makeClient$1.apply(Http1Support.scala:67) ~[org.http4s.http4s-blaze-client_2.11-0.12.4.jar:0.12.4]
           at org.http4s.client.blaze.Http1Support$$anonfun$makeClient$1.apply(Http1Support.scala:67) ~[org.http4s.http4s-blaze-client_2.11-0.12.4.jar:0.12.4]
           at org.http4s.util.TaskFunctions$$anonfun$futureToTask$1.apply(Task.scala:21) ~[org.http4s.http4s-core_2.11-0.12.4.jar:0.12.4]
           at org.http4s.util.TaskFunctions$$anonfun$futureToTask$1.apply(Task.scala:20) ~[org.http4s.http4s-core_2.11-0.12.4.jar:0.12.4]
```

**Comment by ioganegambaputifonguser** [comment]
I will take it

**Comment by ioganegambaputifonguser** [comment]
@SteveDraper There is PR which should resolves over logging https://github.com/http4s/http4s/pull/1683

Could you please support a little?
If I add test in the `blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala`, something like this 
```
"raise error UnresolvedAddressException if attempts to establish a connection to server that is not contactable" in {
      val u = uri("https://httpbin1.org/get")
      val resp =
        successClient.expect[String](u).unsafeRunTimed(timeout)
      resp must_== (Some(
        Left(new UnresolvedAddressException)))
    }
```
it does not work and I dont receive `IO(callback(Left(error)))` from the `createConnection:client/src/main/scala/org/http4s/client/PoolManager.scala`

but it works with the internal http4s `NoConnectionAllowedException` error
```
"raise error NoConnectionAllowedException if no connections are permitted for key" in {
      val u = uri("https://httpbin.org/get")
      val resp = failClient.expect[String](u).attempt.unsafeRunTimed(timeout)
      resp must_== (Some(
        Left(
          NoConnectionAllowedException(
            RequestKey(
              u.scheme.get,
              u.authority.get
            )))))
```

what is the reason?
