### ISSUE TITLE
Connection reset exception on websocket server

### ISSUE THREAD

**Issue by CEikermann** [http4s/http4s#7598]
Ember server @ 1.0.0-M43

Connection resets are currently being logged as error in WebSocketHelpers: 
https://github.com/http4s/http4s/blob/v1.0.0-M43/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala#L104

Exception trace:
```
[info] java.io.IOException: Connection reset
[info] 	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:425)
[info] 	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195)
[info] 	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
[info] 	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
[info] 	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[info] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info] 	at java.base/java.lang.Thread.run(Thread.java:840)
[info] 	at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:120)
[info] 	at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:114)
```

Its hard to reproduce, basically closing the connection on client side while the underlying logic is trying to read from its connection

As this behavior is driven by the client, should this log level changed to debug, like the other cases (end of stream and broken pipe) - or is there any other way to catch this exception?

**Comment by CEikermann** [comment]
I can see that the errorHandler is not called by connection exception like this, should we change this logic to call errorHandler in order to be able to catch exceptions like this from outside?
